### ISSUE TITLE
Add horizontal scroll buttons to revenue filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#100]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c1af026f-8332-4f83-aab0-ecfd476941db)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/646aae03-0b55-4531-9844-fb81086eb348)

**Comment by mcharg** [comment]
Still an issue in the new version.

**Comment by jennmalcolm** [comment]
@master12, this is done with the horizontal scroll bars right?

**Comment by mcharg** [comment]
We had this because people didn't see the horizontal scrollbars at the bottom of the table.  I do think it is mitigated by defaulting to 3 years, so people will only need to scroll horizontally if they actively pick more years, so we can watch in testing and see if it's still a problem.
