### ISSUE TITLE
Detail card county map improvements

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1000]
For some states I think it would be hard to figure out the county maps on the detailed cards. I think the counties outside of the state showing makes it harder to figure out the maps. How difficult would it be to not show any of the county borders outside of the selected state?

![image](https://user-images.githubusercontent.com/30806839/94857119-3b7bc900-03ee-11eb-956d-051d548fc145.png)

It would also be nice if we could zoom in a little more on the selected state so it takes up more of that space on the card.

**Comment by mojobnichols** [comment]
@jennmalcolm since this was fixed in lazy loading and now in production.   Shall we close it and I can get bonus points ... or really in this case credit since it was a pretty big undertaking to get explore data performance improvements in place and involved fixing this.

**Comment by jennmalcolm** [comment]
Yes I agree @mojobnichols; you should get the points. I will close it.
