### ISSUE TITLE
Make query tool usable on mobile

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#101]
Follow the pattern designed for disbursements:
https://oajgix.axshare.com/#g=1&p=disbursements_table&view=e

**Comment by jennmalcolm** [comment]
We will need to haver further discussion on our solution for this.

**Comment by mcharg** [comment]
Looking at analytics, 100% of usage of the query tool in the last 3 months was on desktop, so we don't need to worry about optimizing for mobile.
