### ISSUE TITLE
Plan OGOR B design studio

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1011]

**Comment by mcharg** [comment]
Here's the deck I started a while ago. https://teams.microsoft.com/l/file/7E0FC5B7-A27B-4A7A-9642-01913219C99D?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FOGOR%20B%2FOGOR%20B%20Shaping.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review. https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/NRRD/Design/OGOR%20B/OGOR%20B%20Shaping.pptx?d=w7e0fc5b7a27b4a7a964201913219c99d&csf=1&web=1&e=iemNK2

**Comment by Maroyafaied** [comment]
@mcharg I added a comment on slide 6. I just look at the user questions study findings and it seems that Domain Learners and Storytellers are the main users looking for this type of data. 
![image](https://user-images.githubusercontent.com/40175688/99290067-0b9c4f80-27fb-11eb-91d4-7f062b2d9a4c.png)

**Comment by mcharg** [comment]
@maroyafaied Good catch.  I changed it to be about storytellers and domain learners and changed the scenario I had to be a journalist and added one for a BLM analyst to cover domain learners.

**Comment by Maroyafaied** [comment]
@mcharg it looks good, are slide 40 -47 going to be deleted or need to be updated as well? Thanks for your work on this.

**Comment by mcharg** [comment]
I deleted them.
