### ISSUE TITLE
Redirect state pages to the explore data page with the card selected

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1032]
https://revenuedata.doi.gov/explore/tx/

returns a 404 page, but I thought we set up redirects for the state pages, so we don't lose SEO power.

**Comment by jlouis-onrr** [comment]
@mcharg, I think we just need to handle the casing, if you try:  https://revenuedata.doi.gov/explore/TX/  you'll see the redirect take place.
Seems to just be a casing issue.
