### ISSUE TITLE
Revise scrolling and zooming functionality in the map

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1044]
Six participants had trouble scrolling and zooming within the map and to the sections below the map.  They didn't get the concept of going back to the map and tried to scroll using the wheel and were surprised when it zoomed.

**Comment by Maroyafaied** [comment]
1.Take off "scroll down" and move button outside the map. 
2.Make zoom disabled until map is clicked. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/90015809-8cd9-4c45-bb7c-81bfb1a9f8bc)

**Comment by mcharg** [comment]
It might also be good to change "Explore more revenue" to something like "Revenue comparison and nationwide summaries" to differentiate it from the "Explore more revenue" tab above and to clarify what you'll get when you scroll down.

**Comment by mojobnichols** [comment]
Okay pan and zoom is disabled until the map is clicked but it opened a can of worms.   The upside is when the work in progress is done the map (and page) will be a lot faster.  Also the little bugs like on scrolling down the zoom resets or changing from state to county will go away.  I propose we close this and create three more issues (outlined in PR WIP).
