### ISSUE TITLE
Homepage revenue chart - not tied to lease improvements

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#105]
Follow up from ONRR/doi-extractives-data#4728 to address confusion created by having a swatch for not tied to lease, but the number is too small to ever show up on the chart.

We may need more user feedback to confirm the problem before we determine the solution.

**Comment by mcharg** [comment]
@jlouis-onrr You should consider this when styling the homepage charts.

**Comment by mcharg** [comment]
I asked @arcasarana to include a question about this in the user interview plan for the new trends, so we can either close this or prioritize it.
