### ISSUE TITLE
Consider adding a worksheet to download files with documentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1050]
Two participants requested this.

**Comment by Maroyafaied** [comment]
Try putting a link in the excel sheets for documentations that would take users to the download pages. Flag the link for google analytics and tracking.

**Comment by mcharg** [comment]
@Maroyafaied Do we need this now that we have the data dictionary?

**Comment by Maroyafaied** [comment]
@mcharg we can close this.
