### ISSUE TITLE
Clarify the difference between compare and nationwide sections

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1053]
Four participants weren't clear that there was a difference between the nationwide and compare sections on Explore Data. Maybe put a US map on the headers for the nationwide sections.

**Comment by Maroyafaied** [comment]
Consider moving paragraph down and re design nationwide label. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/bf8f3cc4-090c-41ba-a5ba-c4755323ac50)

**Comment by mcharg** [comment]
Here's what it look like if we:
* Relabel the scroll down button
* Change the "top" link in the sub nav to "map" to get back to the map
* Group all the nationwide summaries into one section
* Move the paragraph into the nationwide summary
* Relabel the first nationwide summary to differentiate it from the nationwide summary title.

https://nengr9.axshare.com/#g=1&p=redesigned

**Comment by jlouis-onrr** [comment]
@mcharg, are doing the same for disbursements and/or production?

**Comment by mcharg** [comment]
@jlouis-onrr Yes
