### ISSUE TITLE
Add tool tips like we have on the circle charts to bar charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1055]

**Comment by Maroyafaied** [comment]
also highlight relevant legend area if not collapsed.

**Comment by jlouis-onrr** [comment]
@mcharg, is this just for the horizontal charts or all stacked charts?

**Comment by mcharg** [comment]
@jlouis-onrr I don't think we need it on the vertical bar charts, since we have the mouseover changes on the table below.
