### ISSUE TITLE
Consider different visual for sort arrow

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1057]
A couple participants didn't understand what it was for. Consider using a different icon or having arrows visible on all columns.

**Comment by Maroyafaied** [comment]
Choose something from MUI.

**Comment by mcharg** [comment]
Here's a good icon from the MUI icons. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5f5087b9-af9e-43f3-9aad-f1f50597705d)

**Comment by jlouis-onrr** [comment]
@mcharg, the sortByAlpha icon actually has the AZ embedded within the icon.  Is that what you are hoping for?  It would look something like:

![sortbyalphaexample.PNG](https://images.zenhubusercontent.com/5d893e494c2d9e0001fa99ad/c2ba0b18-e76c-44fb-b949-57befd07e3d0)

Or were you hoping to have just the up/down arrows placed above and below the label?

**Comment by jlouis-onrr** [comment]
@mcharg, heres a version that uses two mui icons, one above and below:

https://nrrd-preview.app.cloud.gov/sites/1057-VisualSortArrow/query-data

**Comment by mcharg** [comment]
@jlouis-onrr I picked that icon because the AZ makes it super clear that it's sorting, but I like what you did the the arrows above and below the years.

**Comment by mcharg** [comment]
@jlouis-onrr Can you right align the labels, so they have the same alignment as the numbers?

**Comment by jlouis-onrr** [comment]
@mcharg, yep Ill try that out.
