### ISSUE TITLE
Change "American Indian Tribes" in FY disbursements file to "Native American Tribes & Allottees"

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1078]
We should be consistent with monthly files. We should also change other things like using land category instead of onshore/offshore
We'll  need to adjust the db load for the FY file.

**Comment by lpgoldstein** [comment]
Also will change "Total" to "disbursement" as in the monthly file

**Comment by mojobnichols** [comment]
Reopening for catch up of loaddb.
