### ISSUE TITLE
Fix nationwide federal card for disbursement

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1086]
In explore data fiscal year 2020, the nationwide federal card should not be displaying Native American data and the recipients should be listed out. 

![image](https://user-images.githubusercontent.com/40175688/97479458-de553380-1917-11eb-9522-007d810edf96.png)

**Comment by mojobnichols** [comment]
Shoulld be fixed here.   Looking at issue @Maroyafaied found this am

**Comment by Maroyafaied** [comment]
The Native American data should not be displayed on the Nationwide federal card but should be displayed in the nationwide circle chart.
