### ISSUE TITLE
Plan design studio for homepage trends

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1091]

**Comment by mcharg** [comment]
https://teams.microsoft.com/l/file/72514004-2C66-4E2B-9D1D-F802AC68F678?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FHomepage%20Trends%2FHomepage%20Trends%20Shaping.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied Do you want to review?

**Comment by Maroyafaied** [comment]
@mcharg it looks great, the only thing I would maybe add is a slide on how question answerers use the site, similar to slide 11 for domain learners since we identify both user types in our the raw idea slide 5.

**Comment by mcharg** [comment]
@Maroyafaied I actually meant to replace Question Answerers with Storytellers after I saw the numbers from the user questions study.  I added slides for how they use the site.
