### ISSUE TITLE
Create Data API (suggestion)

### ISSUE THREAD

**Issue by Noobiest9** [ONRR/nrrd#1096]
Hello, 

Would it be possible for you to develop a REST API similar to what the EIA has for their data?  Downloads are great and all, but an API would be more useful to external developers.   

Really enjoying the new layout and functionality, keep up the good work.  Thanks!

**Comment by Maroyafaied** [comment]
Thank you for the suggestion. We will post initial documentation on pattern library and put a link on  download page.

**Comment by Noobiest9** [comment]
Just circling back here... its been 6 months.  Are you guys planning to open up any data via API or not? I work for the BLM and we consume a lot of ONRR's production data to produce annual reports.   Having a programmatic means of gathering and processing that data would be very beneficial to us (me).  Thanks for the consideration, and a yes or no answer is fine.

**Comment by master12** [comment]
@Noobiest9 Thanks for pinging us on this topic. We are almost ready to provide an open api endpoint. I would expect it to be done in the next few weeks. It would be great to speak to you directly and get your feedback on it. Maybe once we release the api you can test it out and give us some feedback on it?

**Comment by Noobiest9** [comment]
Wow, that's great to hear! Just point me to some docs on how to hit the endpoint, and I'd be happy to provide some feedback  once its up and running.

**Comment by master12** [comment]
@Noobiest9 We have setup our initial api service for accessing our graphql server. 
URL:
https://hasura-prod.app.cloud.gov/v1/graphql
* The url will change once we get a provisioned DNS to use. 

To see the data available you can use this simple online tool:
https://graphiql-online.com/
* Input the url above and this will show you an explorer of the available graphql nodes

As far as programmatically accessing the graphql API, we use Apollo Client but you will need to do some research for what makes sense for you to use.

We are going to be working on documentation over the next few weeks. Please feel free to email our support email with any questions.
