### ISSUE TITLE
Count number of manual steps done to update data

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#1100]
Count number of manual steps done to update the data.

**Comment by lpgoldstein** [comment]
@mojobnichols Here is the link to the manual steps in data updates https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EeQrmJWSSClOowypqfHtHL4BbLivDPtynCUnaqBAb3ryvQ?email=mojo.nichols%40onrr.gov&e=uGapdh
Please fill out your database steps. I've highlighted in green where you can add that to the sheet.

**Comment by mojobnichols** [comment]
I added my steps

**Comment by lpgoldstein** [comment]
@Nichols, Mojo B<mailto:mojo.nichols@onrr.gov> Thank you!
________________________________
