### ISSUE TITLE
Load time performance

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#1101]
Test load time with lighthouse when push a branch and push to production. Establish the baseline and then decide on appropriate % improve on needed pages. This will be tracked quarterly.

**Comment by Maroyafaied** [comment]
Figure out how to add notification for low performing pieces of website.

**Comment by Maroyafaied** [comment]
@Maroyafaied enable permission in CirCleCI (organization security) , make Jerome and Mojo as admin.

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr I changed both your roles as "owner". Can you check if you have permission now?

**Comment by Maroyafaied** [comment]
Details on how often to we pull the report, where to store it, and if high level data?

- Store in Circle CI and have a program analyst  pull the report or copy the data.
- High level data
