### ISSUE TITLE
Continuing data issue in revenue by company

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1119]
It seems like most of these issues were fixed but some are lingering. Totals do not add up to legend amounts. This is for wind, and it's in dev. 

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/c4785813-d4e9-48d9-ac78-8f2bbe0b5e79)

**Comment by Maroyafaied** [comment]
@mojobnichols can you look into this before we have to do a release?
