### ISSUE TITLE
Stacked Bar Chart content management

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#112]
Provided needed mui integration and componet properties to allow content managment to customize stacked bar charts as need for home page charts.

**Comment by jlouis-onrr** [comment]
Initial thoughts on a start to managing the barchart component:
`<BarChart data={barChartData} color={barChartColor}>`
  `<Title text="Barchart title" subtitle="Barchart subtitle" />`
  `<XAxis labels={xAxisLabels} />`
  `<YAxis labels={yAxisLabels} />`
  `<Legend labels={legendLabels} position={legendPosition} />`
`</BarChart>`
