### ISSUE TITLE
Fix hover functionality monthly bar charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1134]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/bc22321f-0849-41d9-8329-a176fd39f8be)

**Comment by mcharg** [comment]
This is probably me mousing over another month.  We should change the functionality so that it goes back to the selected bar after mousing off another bar.

**Comment by Maroyafaied** [comment]
Works now.

**Comment by Maroyafaied** [comment]
This is happening in monthly for revenue and disbursements.
