### ISSUE TITLE
Plan usability study for homepage trends, OGOR B, and monthly data in the query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1171]

**Comment by mcharg** [comment]
@Maroyafaied @jennmalcolm This is ready for you to review.
https://teams.microsoft.com/l/file/E7AADAFE-8345-4C03-AC38-F1C56BBA92DE?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F35_Trends_OGORB_MonthlyQueryTool%2FStudy%20Plan%20and%20Interview%20Guide%20-%20Trends%20OGORB%20MonthlyQueryTool.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg it looks good, I added one comment. Thanks

**Comment by jennmalcolm** [comment]
I reviewed. My only concern is that it is a lot of content to fit into one study.

**Comment by mcharg** [comment]
@jennmalcolm Good point.  I'll take a look and prioritize, so the things we care about less drop off if we run out of time.
