### ISSUE TITLE
Upload revenue FY 20 file 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1187]
DORC provided the file, for FY 20 these fields will not be populated;  offshore planning area, offshore block, or offshore protraction.

**Comment by lpgoldstein** [comment]
@Maroyafaied @jennmalcolm Please take a look a the new FY revenue file

**Comment by Maroyafaied** [comment]
@lpgoldstein can you change eastern states to Gulf of Mexico and add the FIPS codes according to Andrew's email. Thanks
