### ISSUE TITLE
Production county map scale problem

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1189]
Sizes are vastly different. This is CO and OK cards next to each other in production.

![image](https://user-images.githubusercontent.com/30806839/101695410-85aea580-3a42-11eb-9191-1d396961332a.png)

They look ok in revenue

**Comment by mcharg** [comment]
This is also sizing differently for the same state at different times.  I got two wildly different sizes for California when taking screenshots for wireframes.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7aef407d-168b-4497-8683-29a3245bc18d)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/df465ea3-dbd2-43a0-9b07-ca33c63e3884)
