### ISSUE TITLE
Typo in explore data 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#1190]
Nationwide is missing an "n" in the production view 
![image](https://user-images.githubusercontent.com/39419003/101794862-8b4ccf80-3ac4-11eb-829e-9cf611185316.png)

**Comment by jlouis-onrr** [comment]
@lpgoldstein, this update is now in dev

**Comment by lpgoldstein** [comment]
@jlouis-onrr looks good! Thanks!
