### ISSUE TITLE
Random wrong color on chart

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#1194]
I'm not sure if it was introduced by lazy loading or just became more apparent with lazy laoding.   Sometimes a chart comes in with blue instead of purple.

**Comment by mcharg** [comment]
We've also seen this a couple times in user interviews, but haven't found root cause.

**Comment by mcharg** [comment]
Also happening in dev. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/21a8e49f-5e74-4d08-a829-93e5fe472a15)

**Comment by mcharg** [comment]
Got a random blue in dev.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c84b9796-a341-4568-b9d9-b15107de847c)

**Comment by mcharg** [comment]
And again in dev.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f2ffa8de-a581-431c-84ac-4787c6c170a2)
