### ISSUE TITLE
Create Code for America Summit presentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#120]
Based on this outline (limited access).
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B30532107-4733-4DED-B78D-849030AE5D44%7D&file=Shaping%20Presentation%20Outline.docx&action=default&mobileredirect=true&cid=eaf2e9e0-4650-4454-bc41-d6c7daf89e32

**Comment by mcharg** [comment]
I copied the International Design in Government Day presentation to use as a starting point (limited access).
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY20/Code%20for%20America%20Summit/Code%20for%20America%20Summit%20presentation.pptx?d=w861da1d586fb4196a2864f3e20ea0eb0&csf=1&e=buPitA

**Comment by mcharg** [comment]
@jennmalcolm This is ready for you to review (limited access).
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY20/Code%20for%20America%20Summit/Code-for-America_Shaping.pptx?d=w016d7d6d77f7408ca019171b80a78d0f&csf=1&e=AdILFo

**Comment by jennmalcolm** [comment]
This is looking very good. Thank you to both of you @mcharg and @brentryanjohnson. @mcharg should we have an issue for next sprint for you and I to do a practice, decide who presents what, and make sure it all flows when we're actually talking it through? Also, do I need to contact CFA about me presenting?
