### ISSUE TITLE
Refine disposition categories for OGOR B

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1205]
Includes both determining how we want to roll them up and what labels we want to use to make them user friendly.

**Comment by Baymatt** [comment]
I based my breakdowns on the sample data and the Appendix I found at https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MPRH-Appendix-I.pdf

I decided to break it down by oil and gas because there were categories unique to one or the other. If we don't want to break it down this way, we could just go with the four to five main categories with some changes. It looks a bit confusing since I couldn't create my own drill down bubble chart, but each bullet point represents a bubble, with the numbers next to it signifying what categories they contain.

- Oil
    - Sales
        - Royalty Due (1, 4, 7)
        - Royalty Not Due (5, 9, 43)
        - Buy Back (25) (15 and 26 must combine to equal 25)
            - Sales - Buy Back - Measured - Royalty Not Due (15)
            - Buy Back - Used on L/A (26)
    - Load Oil (3)
    - Waste/Slop Oil (29)
    - Facility
        - Transferred To (11, 12)
        - Transferred From (13)
        - Pipeline drip/condensate/retrograde/scrubber Production (16)
        - Produced Into Inventory (10)
    - Others
        - Theft (24)
        - Differences/Adjustments (42)
        - Lease Agreement 
            - Injected On (14)
            - Used On (20)
        - Spilled/Lost
            - Avoidable (8)
            - Unavoidable (23)


- Gas
    - Sales
        - Royalty Due (1, 4)
        - Royalty Not Due (5, 9, 43)
        - Non Hydrocarbon Gas (6)
        - Buy Back (25) (15 and 26 must combine to equal 25)
            - Sales - Buy Back - Measured - Royalty Not Due (15)
            - Buy Back - Used on L/A (26)
    - Vented & Flared
        - Vented (61, 62, 63)
        - Flared (21, 22, 33)
    - Facility
        - Transferred To (11, 12)
        - Transferred From (13)
    - Others
        - Theft (24)
        - Differences/Adjustments (42)
        - Lease Agreement 
            - Injected On (14)
            - Used On (20)
        - Spilled/Lost
            - Avoidable (8)
            - Unavoidable (23)

**Comment by mcharg** [comment]
@Maroyafaied Should we schedule a meeting with Wendy and whomever Kimbra asked us to include (and I think there was also someone else Nathan said to involve) to review these categories?

**Comment by jennmalcolm** [comment]
I think it was Lydia that Nathan mentioned. I know she would be good.

**Comment by jennmalcolm** [comment]
@Baymatt the only thing I would suggest with your breakdowns is to combine load oil with injected on lease agreement. I would also put waste/slop under others.

**Comment by Maroyafaied** [comment]
@mcharg Yes that can be one of our goals next sprint to co- work with SME and show them with @Baymatt came up with.

**Comment by Maroyafaied** [comment]
Next step is to talk to SME , issue #1302.
