### ISSUE TITLE
Q/A consolidated revenue file 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1214]
**Revenue** 	

Homepage - Yearly Breakdown
- [x] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- [x] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Source File
- [x] Check source file links are correct.
 
Explore Data - Map and Detail Card
- [x] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- [x] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [x] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [ ] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data
- [ ] With a selected fiscal year range, verify the data is correct and then for the conditions below. Then repeat with a selected calendar year range and monthly range. 
    - [ ] One Land Type filter
    - [ ] One Revenue Type filter
    - [ ] One State
    - [ ] One Offshore Region
    - [ ] One to three Commodities
    - [ ] Clear All and change grouping

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
start checklist specific to this.

**Comment by Maroyafaied** [comment]
**Revenue Monthly** 	

Homepage 
- [ ] Monthly bar charts (most recent 12 months, FY & CY)
- [ ] CY bar charts
- [ ] FY bar charts
- [ ] Check Breakouts (Source & Revenue type, commodity)
- [ ] Check year over year comparison
- [ ] Check month over month comparison
- [ ] Source file links

Download 
- [ ] xls and csv files updated with correct dates and file size

Explore Data 
- [ ] Switch between state and county 
- [ ] Show offshore 
- [ ] Choose different commodities 
- [ ] Switch between FY and CY 
- [ ] Add Nationwide federal card 
- [ ] Add Native American Card 
- [ ] Explore data accuracy 
- [ ] Select different commodities  
- [ ] Select different years, correct FY or CY displaying 
- [ ] Summary Cards: correct state title, correct county & state title, trendline, accurate year, commodities data, total # of commodities 
- [ ] Nationwide Federal Card:  % of federal land, total revenue for specified year,  trendline, accurate year, commodities data, revenue type data 
- [ ] Detailed state cards: % of federal land, total revenue for specified year, correct state title, trendline, total revenue for specified year, county map 
- [ ] Detailed county cards: correct county & state title, total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [ ] Native American card: total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [ ] Offshore card: total revenue for specified year, trendline, accurate year, commodities data, revenue type data 
- [ ] Check cards for states with no data 
- [ ] Revenue over time trend line data 
- [ ] Nationwide revenue summary bar chart data 
- [ ] Top Nationwide locations data 

Query Data 
- [ ] Land type filter 
- [ ] Revenue type filter 
- [ ] State/Offshore region filter 
- [ ] Commodity filter 
- [ ] Grouping 
- [ ] Change between fiscal and calendar year and change years 
- [ ] Download matches selected data  

Download  
- [ ] xls and csv files updated with correct dates and file size

**Comment by Maroyafaied** [comment]
While @mojobnichols works on the format of the download files, we can use this file and this link to start the Q/A.

 https://preview-data.app.cloud.gov/

[Formatted monthly revenue.xlsx](https://github.com/ONRR/nrrd/files/6149617/Formatted.monthly.revenue.xlsx)

**Comment by mcharg** [comment]
@Maroyafaied @Baymatt I added a FY column, so it's easier to check FY data.
[Formatted monthly revenue_FY.xlsx](https://github.com/ONRR/nrrd/files/6149940/Formatted.monthly.revenue_FY.xlsx)

**Comment by Maroyafaied** [comment]
@mcharg @Baymatt here is the formatted FY and CY file I did, I noticed there is "East States" and "New Mexico" listed in the offshore region so I'm asking the DORC team what to do with that. 
[Formatted Fiscal  Year revenue.xlsx](https://github.com/ONRR/nrrd/files/6152089/Formatted.Fiscal.Year.revenue.xlsx)
[Formatted CY revenue.xlsx](https://github.com/ONRR/nrrd/files/6152090/Formatted.CY.revenue.xlsx)

**Comment by mcharg** [comment]
@Maroyafaied I rechecked the homepage charts against the yearly files and they still look good.

**Comment by Maroyafaied** [comment]
@mcharg thank you. I will also use the raw files send to us to check data to be sure everything is accurate.
