### ISSUE TITLE
Write notes for components in the pattern library

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1222]

**Comment by Maroyafaied** [comment]
@master12  write instructions on how to do this.

**Comment by mcharg** [comment]
@arcasarana is starting to draft notes for the components.  @master12 have you started instructions for how to update them?

**Comment by arcasarana** [comment]
@mcharg

Here's my first take on notes for the Pattern Library Components.

[https://teams.microsoft.com/l/file/fb78912d-b574-4d41-90a6-2ed17d586d93?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%2520Documents%2FGeneral%2FPattern%2520Library%2520Component%2520Notes.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=aggregatefiles](url)

**Comment by mcharg** [comment]
Updated doc link: https://teams.microsoft.com/l/file/fb78912d-b574-4d41-90a6-2ed17d586d93?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%2520Documents%2FGeneral%2FPattern%2520Library%2520Component%2520Notes.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=aggregatefiles

**Comment by arcasarana** [comment]
@mcharg

Here's my second take:

https://teams.microsoft.com/_?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494#/docx/viewer/aggregatefiles/https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD~2FShared%2520Documents~2FGeneral~2FPattern%2520Library%2520Component%2520Notes.docx?baseUrl=https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD&fileId=fb78912d-b574-4d41-90a6-2ed17d586d93&viewerAction=view
