### ISSUE TITLE
Problem with dive-in pages in preview branch

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1223]
Path prefix problem (?) causing issues with dive in pages   

https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works/offshore-oil-gas/
https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works/coal
https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works/minerals
https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works/onshore-renewables

Problems with these pages include background images not coming through and 404 errors when you go to a different tab (oil and gas, renewables)

**Comment by mcharg** [comment]
Is this the same as #1224?

**Comment by jennmalcolm** [comment]
Looks like it to me @mcharg

**Comment by jennmalcolm** [comment]
I will close this because PR #1225 fixes it and references #1224.
