### ISSUE TITLE
Simplify opening paragraph on home page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1226]
The current paragraph has a grade level of 15--which is well above our target and not the easiest introduction to our site .

I worked with it a bit, and here is what I suggest for a start at revising. This is grade level 12.

Companies pay to extract energy and mineral resources on federal  and Native American property. The payments include bonuses, rents, and royalties. The Office of Natural Resources Revenue collects and disburses these revenues. The funds from federal resources support land conservation, public infrastructure, and local governments. All revenues from Native American resources go to Native American tribes, nations, or individuals.

**Comment by arcasarana** [comment]
Is there a particular grade level we're aiming for?  And also, is there a specific tool you use to determine grade level?

**Comment by mcharg** [comment]
I think it's 10th grade.  @jennmalcolm is out until Thursday.  @lpgoldstein or @Maroyafaied Do you know what we use to determine grade level?

**Comment by Maroyafaied** [comment]
@mcharg @arcasarana , yes we aim for grade level 10, and we use this website to check. http://hemingwayapp.com/

**Comment by arcasarana** [comment]
That's a useful site. Thanks for sharing.  So here's my first take below.  Scored a grade level 10 on the Hemingway site; I had to simplify a lot!  Feedback, of course, warmly welcomed.

---

Companies can pay to get natural resources from government and Native American lands. The payments these companies make are in the form of bonuses, rents, and royalties.

The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. Some go to land conservation, public infrastructure, and local governments.  Some go to Native American tribes, nations, or individuals.

**Comment by mcharg** [comment]
@arcasarana Nice start.  

Some feedback:
* We have data both for lands and offshore waters, so something like property would be more accurate than just lands.  
* We should specify federal when referencing government, so people don't think it includes anything owned by state or local governments.
* The last two sentences could maybe be combined into one if we're not specifying that federal revenue goes to the the things in the first and Native American revenue goes to the ones in the second.

**Comment by mcharg** [comment]
Here's a stab at combining those last two sentences.  I also replaced "get" in the first sentence because I was tripping up on it.

Companies pay to collect natural resources from federal government and Native American property. The payments these companies make are in the form of bonuses, rents, and royalties.

The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to land conservation, public infrastructure, local governments and Native Americans.

**Comment by mcharg** [comment]
We may also have to break out natural resources the way Jennifer has it in her version because people often think out scope includes things like forestry and other natural resources.

**Comment by jennmalcolm** [comment]
Yeah, I do think we should specify "energy and mineral resources." Even though it might impact the grade level, it's better to have a slightly higher grade level but not confuse people about the scope of the site.

**Comment by mcharg** [comment]
I think "produce" is a good word.  "Withdraw" might be another option.  Though "get" does keep it at a grade level 10 even with specifying energy and mineral resources.

Companies pay to get energy and mineral resources from property owned by the federal government and Native Americans. The payments these companies make are in the form of bonuses, rents, and royalties.

The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to land conservation, public infrastructure, local governments and Native Americans.

**Comment by jennmalcolm** [comment]
"Produce" would align better with our use of "production" throughout the site.

**Comment by arcasarana** [comment]
Thanks for the feedback.  I've got 3 versions.

---

**Version 01**

Companies pay to **withdraw then produce** energy and mineral resources from property owned by the federal government and Native Americans.

_Note: I'm avoiding using "and" too much in the first sentence, so I use "then".  This may be the most accurate description._

---

**Version 02**

Companies pay to **produce** energy and mineral resources from property owned by the federal government and Native Americans.


---

**Version 03**

Companies pay to **process** energy and mineral resources from property owned by the federal government and Native Americans.

**Comment by mcharg** [comment]
I defer to @jennmalcolm to pick the right word.

**Comment by jennmalcolm** [comment]
I would go with version 2 because produce encompasses both withdrawal and processing, but not all commodities are processed.

**Comment by arcasarana** [comment]
What do you think of adding a heading to provide more context for users?  When I looked at the page the first time, I wasn't sure what that info was for.

I don't know how accurate the hemingwayapp.com is but just adding that heading brings the grade level down from 13 to 11.

---

### **What we do**

Companies pay to produce energy and mineral resources from property owned by the federal government and Native Americans. The payments these companies make are in the form of bonuses, rents, and royalties.

The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to land conservation, public infrastructure, local governments and Native Americans.

**Comment by jennmalcolm** [comment]
Seems like a good idea to me @arcasarana. The only thing I'm not sure about is the use of "we." We don't use first person like that in any other part of the site, so it would seem like we should be consistent with our tone in the heading, too. It's also unclear who the we would be referring to, in my mind. I can't think of the right phrasing for this heading, but I'll think on it.

**Comment by jennmalcolm** [comment]
Although I guess we use "we" in what's new, so maybe it works.

**Comment by mcharg** [comment]
Should we use the same intro on onrr.gov?  This is what I have right now, which is grade 13.

The Office of Natural Resources Revenue (ONRR - pronounced like "honor") collects and disburses natural resource revenue from leased federal lands and waters and Native American lands.

**Comment by mcharg** [comment]
If we drop the parts about the types of payments and distributions, which I think are less important for onrr.gov, it's grade 10.

What we do

Companies pay to produce energy and mineral resources from property owned by the federal government and Native Americans. 
The Office of Natural Resources Revenue (ONRR - pronounced like "honor") collects these payments and distributes them.

**Comment by mcharg** [comment]
I'm also getting a grade 10 for what @arcasarana has above.  I think if there are extra blank rows it impacts the level, which is weird.

**Comment by mcharg** [comment]
Just realized I had the title for the Hemingway app as part of my entry, which lowered the reading level.  Now both are showing as grade 11.

**Comment by mcharg** [comment]
Should we also bring the intro paragraphs on the homepage tabs into alignment with what we're saying in the main intro?

Revenue
The amount of money collected from energy and minerals on property owned by the federal government and Native Americans.
Grade 7 from Grade 15

Disbursements
The amount of money paid to funds, agencies, local governments, and Native Americans.
Grade 10 from Grade 16.

Production
The volume produced on property owned by the federal government and Native Americans.
Grade 11 from Grade 12

**Comment by mcharg** [comment]
Got the onrr.gov one down to Grade 10.

What we do

Companies pay to produce energy and mineral resources from property owned by the federal government and Native Americans. The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to funds, agencies, local governments and Native Americans.

**Comment by Maroyafaied** [comment]
@arcasarana @jennmalcolm @mcharg here is my suggestions,  I checked the grade level, for NRRD its grade 8, for onrr.gov it's grade 10.

NRRD (Grade 8 reading level)
About Us
Companies that obtain federal or Native American leases are obligated to pay royalties to produce energy and mineral resources. The Office of Natural Resources Revenue (ONRR) ensures accurate collection of these payments and distributes them. The payments go to funds, agencies, local governments and Native Americans. 

ONRR.gov (Grade 10 reading level)
About Us
Companies that obtain federal or Native American leases are obligated to pay royalties to produce energy and mineral resources. The Office of Natural Resources Revenue (ONRR) has many responsibilities including royalty and revenue collections, distribution, auditing and compliance, enforcement, and asset valuation.

**Comment by mcharg** [comment]
Here's an alternate version for onrr.gov that's based off of the mission statement.  It's grade 10.

The Office of Natural Resources Revenue (ONRR) collects, accounts for, and verifies energy and mineral revenues. We then distribute the funds to States, American Indians, and the U.S. Treasury.

**Comment by mcharg** [comment]
Since @Maroyafaied and I are getting widely different results in Hemingway, I got grades 11 and 16 for her suggestions, here's another tool that checks across a bunch of readability indices. https://www.webfx.com/tools/read-able/check.php

This one is giving a grade 14 for the NRRD text and grade 19 for the onrr.gov one.

**Comment by mcharg** [comment]
Also found instructions to turn on readability check in Word. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/31f44ce3-6257-4d27-9fd9-0d74d5bbdc9f)

**Comment by mcharg** [comment]
NRRD:

What we do

Companies pay to produce energy and minerals from federal and Native American property. The payments these companies make include bonuses, rents, and royalties.

The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to federal and local governments and Native Americans.

Revenue
The amount of money collected from energy and minerals on property owned by the federal government and Native Americans.
Grade 7 from Grade 15

Disbursements
The amount of money paid to federal and local governments, and Native Americans.
Grade 9 from Grade 16.

Production
The volume of energy produced on federal and Native American property.
Grade 9 from Grade 12

ONRR.gov
The Office of Natural Resources Revenue (ONRR) collects, accounts for, and verifies energy and mineral revenues. We then distribute the funds to States, American Indians, and the U.S. Treasury.

**Comment by mcharg** [comment]
@jlouis-onrr Will implement the NRRD changes with the trends PR.  We should keep the glossaries for bonuses, rent, and royalties.  Will need to decide whether to keep a glossary on distributes that we currently have on disbursements.

**Comment by mcharg** [comment]
NRRD changes are in Jerome's PR (https://nrrd-preview.app.cloud.gov/sites/1147-NewHomepageTrends/) and onrr.gov changes are in the prototype.
