### ISSUE TITLE
Review developer vacancy 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1237]
I'd like recommendations on title of the position and reviewing the position description.

**Comment by mcharg** [comment]
18F developer job description, for reference. https://join.tts.gsa.gov/join/consulting-software-engineer/

**Comment by Maroyafaied** [comment]
Here is my draft of the PD, please make edits as you see fit. 

https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/PD%20Developer.docx?web=1

**Comment by jennmalcolm** [comment]
I have done my review and added a few suggested changes.
