### ISSUE TITLE
Recruit participants for NRRD usability study

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1242]

**Comment by lpgoldstein** [comment]
@Maroyafaied  @jennmalcolm Here is the spreadsheet with the people to contact for NRRD. I added a column that we can mark with our names when we email. I will add each person to the market map as I email them. I'll start tomorrow and see how far I get. 

https://teams.microsoft.com/l/file/E2C1D40B-103D-47F3-897B-0F17FF0C56A3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2Fexternal_interviewees%20(1).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a
