### ISSUE TITLE
Thorough audit and update of AML page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1245]
Notes from content audit: Grade level up; need to update data from 2017 or just revise to remove those data points; many linked documents seem very out of date

Manually curated data: Yes: per-ton fees; fund distribution; state and tribal spending; percentage for acid mine drainage; static chart; grants to states and tribes; the fund today; allocation of balance

**Comment by lpgoldstein** [comment]
@jennmalcolm Will you please review https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/EfhoOOaWwKRPuuUBLQhuGpQBdnsz-Q64vH4JHBx_FUwROQ?e=CKUy7x?

**Comment by jennmalcolm** [comment]
Looks good. I added my comments.

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review: https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/EfhoOOaWwKRPuuUBLQhuGpQBdnsz-Q64vH4JHBx_FUwROQ?e=CKUy7x

**Comment by Maroyafaied** [comment]
@lpgoldstein this looks good. Did we check if the reading grade level went down after the changes?

**Comment by lpgoldstein** [comment]
@Maroyafaied I ran the checker in Word - but it's written in mdx format so I don't think it's accurate. Still high - grade 12. Once I get the PR out I'll run an online checker that should be more accurate.

**Comment by Maroyafaied** [comment]
@lpgoldstein ok sounds good.
