### ISSUE TITLE
Audit and update Native American ownership page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1247]
Content audit notes: Spacing problems; grade level up to 15; need to review content for updates
 
Manually curated data: Yes: acres of trust land

**Comment by mcharg** [comment]
We need to make sure we don't lose our Google juice to this page when it's rewritten.  It's by far the most landed on page in the site.

Stats for December:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/12aeaf47-48b2-4bf1-bef9-c840be26c657)

**Comment by jennmalcolm** [comment]
I'm not trying to take out content--just simplify where possible and update.
