### ISSUE TITLE
OGOR B MVP on site

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#125]

**Comment by lpgoldstein** [comment]
Related to issue #4935 - we will update the downloads page once we have the data. https://doimspp-my.sharepoint.com/:w:/g/personal/faiedm_mms_gov/EY1U6FC6RflCmWC5bozX63sBgQklYhD-qZbdGLYanJGN5Q?e=LhoAqF&CID=8b1e0694-53a6-bea5-1778-e271f4d66530
