### ISSUE TITLE
Look into ways to increase SEO now that we don't have state pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1251]
Explore Data is has dropped in numbers as a landing page and we're not seeing any of the traffic we used to get coming to the site landing on state pages.  Could we add keywords to the Explore Data page?

When I google "Texas oil revenue on federal land", our only page that comes up is revenue by company.  Maybe we could create a How Revenue Works page with all the state names describing how the process works for state to get people to the site?

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/873d8704-ba18-40a0-a80e-839850ac5e4b)

**Comment by mcharg** [comment]
@jlouis-onrr I just realized that neither Explore Data nor Query Data have an H1 title, which may affect SEO.
https://www.reliablesoft.net/h1-tag/#:~:text=The%20HTML%20tag%20is,header%20visible%20on%20a%20page.&text=In%20this%20post%2C%20you%20will,both%20SEO%20and%20user%2Dfriendly.

**Comment by mcharg** [comment]
Not having an H1 is also not good for accessibility.

**Comment by mcharg** [comment]
@jlouis-onrr I was once able to get this report of Google search terms out of the analytics, which gives some insight into terms people were using to get to the state pages.
https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/NRRD%20Metrics/Analytics/Google%20Searches.xlsx?d=w70f85b91fd3045c29896e74f5a9e2ac2&csf=1&web=1&e=AUFiaz

**Comment by jlouis-onrr** [comment]
@mcharg, where do you want to place the h1 headers for explore data and the query tool pages?
