### ISSUE TITLE
Add query tool downloads to analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1252]
Most of our other download numbers are down and I'm not seeing downloads from the query tool in the analytics.  It would be good to see if people are getting files from there instead of the download page.

**Comment by jlouis-onrr** [comment]
@mcharg, looks like I've created the Query data - download link click tag within GTM that tracks click events for the download links.  It appears the events are firing.  I'm also seeing the event beacons get fired to google and I'm seeing the events in GA under Events, the event category is 'Query data download link'.

**Comment by mcharg** [comment]
@jlouis-onrr I'm seeing it, as well.  Is it possible to add an attribute that will let us know whether it's revenue, production, or disbursements?

**Comment by jlouis-onrr** [comment]
@mcharg, I'll look at adding the dataType attribute to the links
