### ISSUE TITLE
Provide quarter report to program manager

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1254]
One page list of accomplishments for the first quarter of FY 21.

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg here is a start of a draft of the Q1 report, please add or make changes as you see fit. Thanks https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/Data%20Display%20Accomplishments%20%20-%20FY%2021%20Q1.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied I added analytics for the quarter and made some edits.

**Comment by Maroyafaied** [comment]
Send this to program manager.
