### ISSUE TITLE
Prototype monthly snap shot 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1255]
This will be for internal audience , not for external users. 

- [ ] Generate a snap shot automatically every month ( 1 page)
- [ ] Only include visuals already on the website
- [ ] Include text box for Chris to add bullet points

**Comment by Maroyafaied** [comment]
@mcharg can you please put the latest prototypes links here in the issue, I just want to make sure I'm reviewing the right ones before our meeting tomorrow. Thanks

**Comment by mcharg** [comment]
Option 1: https://ydxejr.axshare.com/#id=fbrbnb&p=v3
Accompanying pdf: [https://app.zenhub.com/files/215585796/9a89108b-901f-40db-8e01-e5cf443cafb1/download](https://app.zenhub.com/files/215585796/9a89108b-901f-40db-8e01-e5cf443cafb1/download)

Option 2: https://ydxejr.axshare.com/#id=3uopfd&p=v4&g=1
Accompanying pdf: [https://app.zenhub.com/files/215585796/559dce96-9c0b-4ac7-a54a-e0973ab72110/download](https://app.zenhub.com/files/215585796/559dce96-9c0b-4ac7-a54a-e0973ab72110/download)

**Comment by mcharg** [comment]
Revised option: [https://app.zenhub.com/files/215585796/0ece4c97-c288-4740-b975-40c55a6fe986/download](https://app.zenhub.com/files/215585796/0ece4c97-c288-4740-b975-40c55a6fe986/download)

**Comment by mcharg** [comment]
[Final prototype](https://app.zenhub.com/files/215585796/bafb8c6a-ce20-4f35-b6b1-cf9f898ad2d7/download)
