### ISSUE TITLE
Update land ownership data (on detailed cards)

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1257]
Newer CRS paper here. https://crsreports.congress.gov/product/pdf/RL/RL34273/23

**Comment by Maroyafaied** [comment]
Put % in spreadsheets and let @mojobnichols know the updates to change it in the database table.

**Comment by jennmalcolm** [comment]
@Baymatt this look like the correct report:
https://crsreports.congress.gov/product/pdf/R/R42346
The data starts on page 7.

**Comment by Baymatt** [comment]
Put the new land statistics in this spreadsheet, [land_stats.xlsx](https://github.com/ONRR/nrrd/files/5933828/land_stats.xlsx), as well as created a branch called update_land_stats where I made the changes to the land_stats.sql file found in nrrd/database/ddl/land_stats.sql 

@mojobnichols to take the new stats and update it in the database table

**Comment by jennmalcolm** [comment]
Thanks @Baymatt!
