### ISSUE TITLE
Thorough audit and update of disbursements page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1261]
Notes from content audit:

Grade level up; spacing issues; same glossary question as 2020; check on sequestration to see if 49% is still accurate; should we add anything to this page about NPPLLRF?

Manually curated data: percentages

**Comment by Maroyafaied** [comment]
@Baymatt here is the page this issue is referring to. https://revenuedata.doi.gov/how-revenue-works/disbursements

**Comment by mcharg** [comment]
@Baymatt We had 4 participants in this last round of user interviews who didn't understand why we only have disbursements data at the county level for a few states.  Can you look into adding content about this when you're working on this issue?
