### ISSUE TITLE
Review federal reforms page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1264]
Is this page within our vision and something we should continue to maintain?

If so, we need to research other reforms or updates that we should add to the page.

Currently we're at grade 14, which we should work on.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This issue is referring to this page on the site https://revenuedata.doi.gov/how-revenue-works/federal-reforms/.

Please evaluate if this page is something we should still provide on the site and if we decide to maintain it then what updates are needed?

**Comment by daniel-coleman-1** [comment]
I'd like to speak about the content if possible. I put some revisions in the attached document, main points:
- I'd like to change it to be more of an overview of the federal reforms process, and show how that affects DOI
- List Deepwater as an example of how rulemaking works
- Moved 1504 description to the bottom, I'd like to chat about this

[Federal Reforms Process.docx](https://github.com/ONRR/nrrd/files/6497031/Federal.Reforms.Process.docx)

**Comment by Maroyafaied** [comment]
@mcharg can you review Daniel's recommendations, I will look at it as well but busy with data checks today.

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B11FD9569-0C48-4473-B4D4-423B2AFCFAD1%7D&file=Federal%20Reforms%20Process.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@daniel-coleman-1 The edits you had were at Grade 13.  I put it into Hemingway and got it down to Grade 11, mostly by splitting up complex sentences.  My version is after yours in the doc, to show you what I changed.
