### ISSUE TITLE
Update federal laws page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1265]
This is a post-graduate reading level, which may be difficult to reduce, but we should try.

We also need to review for law changes that we need to update or add.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This issue is referring to this page. https://revenuedata.doi.gov/how-revenue-works/federal-laws/

**Comment by daniel-coleman-1** [comment]
This is an interesting, page, I'd like to speak about the content if possible.  I put some revisions in the attached document, main points:

- I'd like to change it to be more of an overview of the federal reforms process, and show how that affects DOI
- List Deepwater as an example of how rulemaking works
- Moved 1504 description to the bottom, I'd like to chat about this

[Federal Reforms Process.docx](https://github.com/ONRR/nrrd/files/6496805/Federal.Reforms.Process.docx)

**Comment by Maroyafaied** [comment]
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B2D2B4D41-0F5D-43A8-B640-E2367289D55C%7D&file=Language%20Revisions%20-%20Laws%20%26%20Fees.docx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I reviewed and left comments, I revised a few that were still a high grade level and brought it down a bit. There's still a couple that have a pretty high reading level , please try to bring down the reading level if you can. Thanks

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B2D2B4D41-0F5D-43A8-B640-E2367289D55C%7D&file=Language%20Revisions%20-%20Laws%20%26%20Fees.docx&action=default&mobileredirect=true
