### ISSUE TITLE
Update coal excise tax page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1266]
Audit notes: Spacing issues; need to update revenue by year, budget justification

**Comment by Baymatt** [comment]
Updated coal-excise-tax.mdx in a new branch labeled coal-excise tax. Will create pull request before the next intern meeting.
- Updated revenue table to include data for 2018 and 2019.
- Updated link for the Black Lung Disability Trust Fund (BLDTF) to reflect FY 21.
- Added line breaks - On my local build of the website, adding the line breaks that we mentioned during last week's meeting was able to work. It seems to be pretty particular about the format, but the line breaks are visible and the links aren't broken. Will need to verify it looks alright and the links work on other builds of the website.
