### ISSUE TITLE
Load Disbursement using nrrd-data

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#1288]
Load disbursement data using the new script

**Comment by Maroyafaied** [comment]
@mojobnichols , @lpgoldstein does some formatting with the raw data set when she receives it before uploading it so she will share those instructions with you.

**Comment by lpgoldstein** [comment]
@mojobnichols Here are the three changes I always make: 

1. Delete Treasury Fund column - good for our knowledge and more detail if anyone asks but not needed. 
2. Change Hidalgo Caounty to Hidalgo County under county column
3. Change "BLM - Permit Processing and Improvement" to "Lease Processing and Improvement" (BLM) under fund type column
