### ISSUE TITLE
State/offshore region doesn't need to be a column for monthly production

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1294]
We don't have that data for monthly, so they all show up as location not published.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ee345fdf-46a8-4f56-b85b-d17798c11550)

**Comment by master12** [comment]
@mcharg There is no code change for this so there will be no PR. but you can review it in dev.

https://dev-nrrd.app.cloud.gov/query-data/

**Comment by mcharg** [comment]
@master12 Looks good.
