### ISSUE TITLE
figure out not tied to lease/location labels

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1303]

**Comment by mcharg** [comment]
We decided to use "not tied to a lease" in place of "not tied to a location" and "not tied to a lease".  "Not tied to a commodity" is different and will stay.

**Comment by mcharg** [comment]
@jennmalcolm @mojobnichols Was updating the database supposed to be part of this issue, or should we create a new issue for that?

**Comment by jennmalcolm** [comment]
I created #1320 for updating the DB, so I'll close this.
