### ISSUE TITLE
Shorten guide for NRRD study

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1305]
The sessions are taking too long in the mock interviews.

**Comment by mcharg** [comment]
@jnwang01 On the query tool part, all we really want to know is whether people want to compare the same month in different years or consecutive months, so we don't need to spend much time on that.  We could maybe even just ask the question without showing the query tool to save time.

**Comment by jnwang01** [comment]
@mcharg okay great, I'll add that after the OGORB and before the sticky header

**Comment by mcharg** [comment]
@jnwang01 Let's remove the OGOR B from this and do it as a separate study. We can keep in the query tool stuff.

**Comment by jnwang01** [comment]
@mcharg okay I'll put the OGORB stuff on a separate document

**Comment by mcharg** [comment]
@jnwang01 Thank you.

**Comment by jnwang01** [comment]
[OGOR B user interview study guide.docx](https://github.com/ONRR/nrrd/files/5914351/OGOR.B.user.interview.study.guide.docx)
[Study Plan and Interview Guide - Trends MonthlyQueryTool.docx](https://github.com/ONRR/nrrd/files/5914352/Study.Plan.and.Interview.Guide.-.Trends.MonthlyQueryTool.docx)
 
Here is the OGOR B study guide and the Trends and Monthly Query Tool study guide. I separated the OGOR B from the Trends study guide and I shorted and removed parts of the Month;y Query Tool tasks

**Comment by mcharg** [comment]
Uploaded files to Teams for commenting.

Trends/monthly data query tool:https://teams.microsoft.com/l/file/15202F05-2458-418D-A3A8-D9EA02A27491?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F35_Trends_MonthlyQueryTool%2FStudy.Plan.and.Interview.Guide.-.Trends.MonthlyQueryTool.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

OGOR B: https://teams.microsoft.com/l/file/C59CCB32-B937-4A06-A635-4F96FD712FB1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F37_OGORB%2FOGOR.B.user.interview.study.guide.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@jnwang01 Looks good.  I added comments and made some edits in the versions of the docs I uploaded to Teams.

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein These are ready for you to review.

**Comment by Maroyafaied** [comment]
@mcharg looks great.
