### ISSUE TITLE
Due Feb 26: Proposal for DotGov Design conference

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1313]
https://dc.aiga.org/dotgov-design-conference-2021-call-for-speakers/
- I'm thinking of proposing a lightning talk on card sorting using GitHub for this one.

Session Formats
Our final schedule will feature a mix of the session formats listed below. If you think your session could fit multiple formats, you can choose more than one option in your final submission. If you want to propose a different format, feel free to pitch us in your application.

Creative Lunch:
A 45 minute interactive lunchtime session presented by one or two speakers. We recommend planning for 30 minutes of content, 10 minutes of Q&A, and 5 minutes for set-up and wrap-up.

Talk:
A 60 minute lecture or interactive session presented by one or two speakers. We recommend planning for 45 minutes of content, 10 minutes of Q&A, and 5 minutes for set-up and wrap-up.

Lightning Talk:
A 10-15 minute brief presentation with a single presenter. This session type will likely be grouped back-to-back with other talks and include a potential Q&A at the end of a full session of lightning talks.

Panel:
A 45 minute small group of people brought together to discuss, investigate, or decide on a particular topic, moderated by a single individual. We recommend 25 minutes of moderator-prepared questions, 10 minutes of audience-driven questions, and 10 minutes for set-up and wrap-up.

Unconference Session:
30 minute, informal sessions to discuss relevant topics with a small group of attendees.

Workshop:
A highly interactive 90 minute session featuring small group exercises led by one or two individuals. We recommend 60 minutes of activities, 15 minutes of reflection, and 15 minutes for set-up and wrap-up.

**Comment by mcharg** [comment]
Conference is May 13 - same day as Code for America.

**Comment by mcharg** [comment]
Or it may be May 18 - depending on where you look.

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied Do either of you want to review?
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={6c22f5b2-252b-4715-87ca-2fd57d9c7093}&action=edit

**Comment by Maroyafaied** [comment]
@mcharg looks great, I don't have changes.
