### ISSUE TITLE
Implement change from "oil & gas" to "oil or gas (pre-production)"

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1314]
Needs to be updated in Explore Data, the Query Tool, and downloads page.

**Comment by Maroyafaied** [comment]
@mcharg We never implemented this change, I think we decided to wait till the change is made in the database and the download files are coming from the database.  Once that happens, we also need to change it in our download pages.

**Comment by mcharg** [comment]
@Maroyafaied At least we now have an issue, so we don't forget to implement.

**Comment by Maroyafaied** [comment]
@lpgoldstein can you please make this change in revenue by company download page, disbursements by month download page and in your PR#1297.
