### ISSUE TITLE
Due Feb 19th: Survey call for presenters DOI Economics workshop 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1315]
@mcharg @jlouis-onrr or @mojobnichols let me know if one of you would be interested to present in the DOI Economics workshop April 27-29, you have till fill out this survey by Feb 19th.  Some of the suggested topics include data visualization and database management.  I put the detailed info and link to the survey below (question 7 is for presenters)

https://forms.office.com/Pages/ResponsePage.aspx?id=urWTBhhLe02TQfMvQApUlDYtRc-cjUFPjwcQSxBY4r9UMDA5OFkyRUFSNERUVTg5SlZPRzkzQlUxRS4u

The DOI Economics CoP is organizing the 2021 DOI Economics Workshop, to be held online April 27-29, 2021. This is an opportunity for the Interior economics community to come together for networking, training, and discussions on current issues of interest. Please feel free to share this announcement with your colleagues who may be interested in participating. We look forward to seeing everyone online in April for 3 days of presentations and discussions on topics of interest and importance to the Interior economics community.

Planning Survey and Call for Presenters
Please respond to our brief survey to help us consider what we should include on the 2021 agenda to make this a workshop that you'll enjoy. You may remain anonymous if you wish.

We also invite you to submit abstracts for research that you would like to share with the DOI economics community. We welcome presentations on in-progress work as well as completed projects. Please use the survey to send us a brief description of your research, and your preferred session type: lightning round, special topic session, or online "poster" (story-map, data-viz, etc.) by Friday, February 19. 

Presentation topics survey link (MS Forms Survey).

 
We also invite your ideas for panel discussions and small-group working sessions. Please use the survey link above to share your ideas for sessions, and tell us if there are topics you would be interested in serving on a panel for or helping to organize. We will use the responses we receive from this call for presenters to develop our agenda.

We look forward to working with all of you and enjoying our community’s gathering in April.

Please send along any questions or comments that come up.

**Comment by mcharg** [comment]
Looking at the topics, I think the database would be the most compatible with their list, if @mojobnichols wants to present on that.

**Comment by Maroyafaied** [comment]
I submitted the survey.
