### ISSUE TITLE
Consider defining "equivalent tons" separately

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/nrrd#132]
We define "equivalent tons" as "tons" in the glossary, but it's clearly a separate unit with a presumably different definition. We should add a glossary term and define what equivalent tons means.

![charts for purge liquor and soda ash, with equivalent tons for the first and tons for the second](https://user-images.githubusercontent.com/32855580/63951672-08b91180-ca33-11e9-850d-19a818ff832d.png)

**Comment by Maroyafaied** [comment]
Ask DORC about this

**Comment by cthomasONRR** [comment]
I just sent Nadia Miller an email, asking for help in defining "tons - equivalent" :

"Hi Nadia,

I’m hoping you can help the Data Display Team clarify a definition term on the NRRD website.

For solid minerals production, we have the volume in tons. The “tons” definition in the Glossary webpage as “In the U.S., one ton is 2,000 pounds. In some countries this is referred to as a short ton.”

For Purge liquor, we have the volume as “tons – equivalent”, which is not currently defined. This is clearly a separate unit, and we presume it should have a unique definition from the current “tons” definition. 

Could you help us develop a definition for “tons – equivalent”? We are unfamiliar with Purge liquor production, and would appreciate your expertise on how this term should be properly defined.

Please let us know if you will be able to help!

Thanks so much for your time and patience,

Christine Thomas"

**Comment by CM805** [comment]
You may also be able to check in with Mike Anspach, Michael Rausch, or Christina Lynch.  They do solids reference data, but they may be familiar with some reporting terms as well.

**Comment by cthomasONRR** [comment]
@CM805 Thanks for the advice! I will give Nadia some time to respond, then reach out to the other people you listed.

**Comment by cthomasONRR** [comment]
Email response from Nadia Miller. I am working on developing a simple definition.

"Christine,

Here is what I found out from a mining engineer familiar with solution mining of carbonate minerals and reading about the trona solution mining processes in Wyoming - The purge liquor is recovered from solution mining of trona and the volume is initially measured in liquid units.  There is chemistry involved in determining the ratios of which royalty bearing minerals (most likely soda ash and sodium bi-, and sesqui-carbonate, good guesses, based on what is recovered from solution trona mining) will precipitate out of the liquid.  Depending on the concentration of the mineral fractions contained in the solution, the extracted tonnages of the precipitated mineral(s) can then be calculated and these measurements are probably taken at the processing plant after the liquid flows through the royalty measurement point.  Most likely, the mineral fractions are very consistent, however the concentration probably varies and is still in liquid form at the royalty measurement point.

I hope this helps.  Let me know if you have questions.

Nadia"

**Comment by cthomasONRR** [comment]
Proposed "tons - equivalent" definition, since it is only used for Purge liquor.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/12f9fd79-e814-4eaa-87fa-15204b3759a0)

"Purge liquor is recovered from solution mining of Trona ore and the volume is initially measured in liquid units. The liquid units are converted to an equivalent tonnage during the process of recovering royalty-bearing minerals from solution Trona mining."

**Comment by cthomasONRR** [comment]
Nadia approved my proposed definition above.

@Maroyafaied and @mcharg - Can I get your approvals before adding this to the NRRD glossary?

Thanks!

**Comment by mcharg** [comment]
We use a tool called Hemingway to evaluate reading level.  The goal for the site is grade 10 and I'm getting a grade 14.  Can you see if you can get it down to a grade 10?
https://hemingwayapp.com/
![image](https://user-images.githubusercontent.com/38465926/127507191-5de5213e-a57c-4814-ad95-b2fbe912ada2.png)

**Comment by mcharg** [comment]
Here's one option that gets it to grade 10. 
![image](https://user-images.githubusercontent.com/38465926/127507747-04531475-f669-49cb-a9c2-a102b142d343.png)

**Comment by cthomasONRR** [comment]
@mcharg thanks for looking into the reading level!

I'm ok with your Grade 10 version:
"Purge liquor is recovered from solution mining of Trona ore. The volume is first measured in liquid units. It is then converted to an equivalent tonnage when recovering royalty-bearing minerals from solution Trona mining."

**Comment by Maroyafaied** [comment]
@cthomasONRR This looks good, I'll move this issue to this sprint so you can create a PR to add this to the glossary. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied , could this be added to the "adding glossaries" PR instead of making a new one?

**Comment by Maroyafaied** [comment]
@cthomasONRR Ya, that works!

**Comment by cthomasONRR** [comment]
Added this update to the "Adding glossaries" PR:
https://github.com/ONRR/nrrd/pull/1658
