### ISSUE TITLE
Query Tool Duplicate of "Not Ties to A Commodity" 

### ISSUE THREAD

**Issue by jnwang01** [ONRR/nrrd#1322]
In the query tool, under revenue, the commodities tab shows "not tied to a commodity" twice in the drop-down menu. 
![Screenshot (1322)](https://user-images.githubusercontent.com/69867817/106662634-7be38300-6557-11eb-907e-736d4718c5e9.png)
![Screenshot (1323)](https://user-images.githubusercontent.com/69867817/106662636-7c7c1980-6557-11eb-99de-28e078881921.png)

**Comment by Maroyafaied** [comment]
@master12 @mcharg looks like this issue might of been taken care of in one of Jeff's PR fixes because I'm not seeing it on the dev site. Is it ok to close it?

**Comment by mcharg** [comment]
I'm not seeing it in dev either.

**Comment by mcharg** [comment]
This is fixed
