### ISSUE TITLE
Update OGOR B prototype with final disposition categories

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1344]
So we can get user feedback.

**Comment by mcharg** [comment]
I think the prototype is ready.  There are pages for oil and gas. @Maroyafaied Do you want to review and make sure I didn't miss anything?
https://dwb2kg.axshare.com/#id=kgdh1w&p=usertesting

**Comment by Maroyafaied** [comment]
@mcharg this other circle doesn't underline and click when you hover over it like the others. 
![image](https://user-images.githubusercontent.com/40175688/110153457-4de49f00-7da0-11eb-84fb-e8a03b868bf0.png)

**Comment by mcharg** [comment]
@Maroyafaied Fixed

**Comment by Maroyafaied** [comment]
@mcharg from Wendy's notes, I understood it as under other, there would be "Native to lease/agreement" category and under it there would be both "injected on lease/agreement" and "used on lease/agreement". So load oil wouldn't be on it's own. That's the way you also have it for gas (last pic). Let me know if I'm not making any sense. 

![image](https://user-images.githubusercontent.com/40175688/110153843-cba8aa80-7da0-11eb-93f7-f59b0eb41f03.png)
![image](https://user-images.githubusercontent.com/40175688/110154060-090d3800-7da1-11eb-9221-4c95967e45bd.png)
![image](https://user-images.githubusercontent.com/40175688/110154605-ad8f7a00-7da1-11eb-91ed-8ff18bd55fa3.png)

**Comment by mcharg** [comment]
@Maroyafaied Got it.  There wasn't any injected oil for 2018, but will pull load oil into that category.
