### ISSUE TITLE
Nationwide top locations revenue chart data issue

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1348]
Chart on live site and in dev has huge "not tied to lease" numbers. Data elsewhere (like horizontal bar chart) doesn't appear wrong, but I haven't checked it all. This one is just glaring. 
![image](https://user-images.githubusercontent.com/30806839/107697339-1b53f480-6c81-11eb-9edd-6371a9c20c33.png)

**Comment by Maroyafaied** [comment]
@mojobnichols I checked the CY 19 top nationwide locations data and all the numbers were correct. @jennmalcolm can you do a quick check for a different year? Thanks

**Comment by jennmalcolm** [comment]
Yes I looked at FY20, and it looks good.
