### ISSUE TITLE
Add pattern library notes to MDX files

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1353]

**Comment by lpgoldstein** [comment]
@master12 would you please take a look at this issue?

**Comment by arcasarana** [comment]
I'm not sure if it helps, but I did make a copy of the files I changed before the PR.

**Comment by mcharg** [comment]
@master12 got the preview fixed.
https://nrrd-preview.app.cloud.gov/sites/1222-components-notes/patterns/

The only issue I noticed is the links aren't displaying as links.  They might need to be changed to html instead of markdown.

**Comment by Maroyafaied** [comment]
@master12 please look into this

**Comment by mcharg** [comment]
@master12 Should we close this issue and open a new one to fix whatever bugs are preventing the branch from building?

**Comment by mcharg** [comment]
Created #1442 for @master12 to fix the bugs that are preventing this build.
