### ISSUE TITLE
Due Feb 23: Code for America Summit Proposals

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1357]
I'm thinking of just submitting the card sorting using GitHub, since I'll be writing that up for the other conferences.  Any other ideas?

https://summit.codeforamerica.org/call-for-proposals/?utm_campaign=Summit%202021&utm_medium=email&_hsmi=111679854&_hsenc=p2ANqtz-9QnWLC-FvQa__g0lifyPeUD5_GNWuskD0xzZmEPLS696MFnR3Z1JDDtpKRyxrtjRcvTJ8zmq9ZKlCGbDb6dMqdwy5jog&utm_content=111679854&utm_source=hs_email

**Comment by mcharg** [comment]
Conference is May 12 & 13

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied Do either of you want to review?
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={7a8e7e73-bb75-4995-aef0-6aa57e4da929}&action=edit

**Comment by Maroyafaied** [comment]
@mcharg It looks like on the form they ask for the description to only be 130 works, this one has 231 so we probably have to make it shorter. 
![image](https://user-images.githubusercontent.com/40175688/108553362-ca12b900-72af-11eb-8807-8e27c52f7b07.png)

**Comment by mcharg** [comment]
@Maroyafaied Got it down to 129 words.  Also replaced with some of the simpler language in the other proposals.
