### ISSUE TITLE
Update README for gatsby-site

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/nrrd#136]
Our [readme documentation](https://github.com/ONRR/doi-extractives-data/tree/dev/gatsby-site) for the gatsby portion of the site is the boilerplate for the `gatsby-starter-default`. 

We should customize this readme to communicate how we are using gatsby and the transition status.

**Comment by mcharg** [comment]
Is this a duplicate of #18?

**Comment by jennmalcolm** [comment]
Look like duplicate of #18 so closing
