### ISSUE TITLE
Create a state page for SEO

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1360]
To help explain how money goes to the states and to increase SEO.

**Comment by mcharg** [comment]
@jlouis-onrr Here's copy for the state pages.

This page provides information about energy and minerals produced on federal land in [State name].  Federal land represents [XX]% of all land in [State name].  

The Office of Natural Resources Revenue (ONRR) collects rent, royalty, and bonus payments from companies that lease federal land. Some of the money collected is then disbursed to the state. States then distribute the funds as part of their budgets, but we don't have data about how the states spend the funds.

Explore production data in [state name]          Query production data in [state name] 
Explore revenue data in [state name]                Query revenue data in [state name] 
Explore disbursements data in [state name]     Query disbursements data in [state name]

**Comment by mcharg** [comment]
@jlouis-onrr Offsore region page:

This page provides information about energy and minerals produced in federal waters in the [Offshore region name].
The federal government manages the waters and submerged lands of the Outer Continental Shelf. This means that all offshore drilling and renewable energy generation takes place in federal waters.

The Office of Natural Resources Revenue (ONRR) collects rent, royalty, and bonus payments from companies that lease the federal waters. Revenue from offshore production is disbursed to the states and counties that surround the offshore area.

Explore production data in [region name]          Query production data in [region name]
Explore revenue data in [region name]                Query revenue data in [region name]
                                                                             Query disbursements data from all offshore regions

**Comment by mcharg** [comment]
@jlouis-onrr Updated offshore content.

This page provides information about energy and minerals produced in federal waters in the [Offshore region name].

The federal government manages the waters and submerged lands of the Outer Continental Shelf. The first three nautical miles offshore (generally) are in the states' jurisdiction. This means that most offshore drilling and renewable energy generation takes place in federal waters.  

The Office of Natural Resources Revenue (ONRR) collects rent, royalty, and bonus payments from companies that lease the federal waters. Revenue from offshore production is disbursed to the states and counties that surround the offshore area.

Explore production data in [region name]          Query production data in [region name]
Explore revenue data in [region name]                Query revenue data in [region name]
Query disbursements data from all offshore regions

**Comment by jlouis-onrr** [comment]
@mcharg, what is query filter for the following link?

**Comment by mcharg** [comment]
@jlouis-onrr Land type = federal offshore

**Comment by Maroyafaied** [comment]
Can I close this issue?

**Comment by jlouis-onrr** [comment]
@Maroyafaied, doesn't look like its been merged yet:
https://github.com/ONRR/nrrd/pull/1375
