### ISSUE TITLE
Due March 19: Create poster of card sorting presentation for IA Conference

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1364]
The proposal was accepted.  I think they'll send instructions for creating the poster later.

**Comment by arcasarana** [comment]
@mcharg Could I do this one?  It's okay if another intern has already taken it.

**Comment by mcharg** [comment]
@arcasarana Yes!  I'll forward you an email with details.

**Comment by mcharg** [comment]
KEY DATES

Poster review: send draft posters March 19

Feedback provided to presenters March 26

Poster tech rehearsal April 25

Poster night April 28

**Comment by arcasarana** [comment]
Draft Poster V3

[poster_v3.pdf](https://github.com/ONRR/nrrd/files/6161298/poster_v3.pdf)

**Comment by mcharg** [comment]
@arcasarana Looks good.  Draft sent to the organizer.
