### ISSUE TITLE
Query and automatically render data file date range

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/nrrd#137]
We manually curate the start and end years and months for our data files on the download pages. For instance, here is the paragraph for disbursements data:

> Revenue collected from extraction of natural resources on federal and Native American lands is distributed to various legislated funds, local governments, and federal agencies. This process is called disbursement. **We have disbursements data by month from October 2018 through the most recently available month.**

It would be nice to query the data and automatically plug in the date range variables for each data file based on the data itself.

**Comment by mcharg** [comment]
Irrelevant now that we're getting downloads from the database.

**Comment by mcharg** [comment]
Irrelevant now that we're getting downloads from the database.
