### ISSUE TITLE
Consolidate NRRD user interview findings

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1374]

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein This is ready to review.
https://teams.microsoft.com/l/file/9CC854BB-210E-4A33-9F1F-A5048DE9148A?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F35_Trends_MonthlyQueryTool%2FConsolidated%20Findings.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg looks good, I added a couple of comments.
