### ISSUE TITLE
Include the word "offshore" in the 8(g) option in the query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1376]
To match what we're doing in Explore Data.
Query tool:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/69452506-8d81-4563-bf48-90d2e71dcf35)

Explore data:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f5a95297-2884-4f46-9aad-9e6f9eb5b5f9)

**Comment by Maroyafaied** [comment]
Change is done in database.
