### ISSUE TITLE
Changes to fact sheet

### ISSUE THREAD

**Issue by master12** [ONRR/nrrd#1392]
@master12 this looks good, just two small suggestions. Can you make  revenuedata.doi.gov clickable and would it be possible to add a print icon for users to know this can be printed as 1 page. 
![image](https://user-images.githubusercontent.com/40175688/109704902-62345c00-7b54-11eb-91c7-1a3dfd49ed48.png)

_Originally posted by @Maroyafaied in https://github.com/ONRR/nrrd/issues/1366#issuecomment-789163100_

**Comment by Maroyafaied** [comment]
@master12 Howard would like us to put a space between commodity and unit of measure for the production charts headings. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/2391bf23-243f-4ca0-abe4-99d3a89445ff)

**Comment by master12** [comment]
Remove the date on the header

**Comment by master12** [comment]
Space for the production Label and units
