### ISSUE TITLE
Revise homepage copy to include mention of "federal lands".

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1398]
The new homepage copy doesn't make the scope of the site clear.  Some thought it was just Native American and were looking for "federal lands".

**Comment by mcharg** [comment]
Here's an idea that would also address an issue one participant had not knowing what offshore was.  Changing the heading may also clarify that it's the scope of the site.  It's grade 10.

About our data

Companies pay to produce energy and minerals from onshore and offshore land owned by the federal government and Native Americans. The payments these companies make include bonuses, rents, and royalties. The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to federal and local governments and Native Americans.

@Maroyafaied @lpgoldstein @arcasarana Thoughts?

**Comment by mcharg** [comment]
Since the header is the H1 on the page, we might get an SEO boost by making it more descriptive.  This is grade 11.

About natural resources revenue data

Companies pay to produce energy and minerals from onshore and offshore land owned by the federal government and Native Americans. The payments these companies make include bonuses, rents, and royalties. The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to federal and local governments and Native Americans.

**Comment by arcasarana** [comment]
I like the new header and makes sense for SEO.

Here are my first takes:

V1.  Companies pay to produce energy and minerals from onshore and offshore lands.  These lands include both federal lands and Native American lands.

V2. Companies pay to produce energy and minerals from onshore and offshore federal lands and onshore and offshore Native American lands.

V3. Companies pay to produce energy and minerals from onshore and offshore federal lands and Native American lands.

@Maroyafaied @lpgoldstein @mcharg What do you think?

**Comment by mcharg** [comment]
I like V3. 

V1 and V3 are grade 11 and V2 are grade 12. @Maroyafaied

**Comment by Maroyafaied** [comment]
I agree with V3. V2 is not correct to say "offshore Native American lands". Here a suggestion that's a grade 9. 

Companies pay to produce energy and minerals on federal lands, Native American lands, and the Outer Continental Shelf.

**Comment by mcharg** [comment]
@Maroyafaied That works.  I'm getting a grade 11 when I include it with the whole paragraph.

About natural resources revenue data

Companies pay to produce energy and minerals on federal lands, Native American lands, and the Outer Continental Shelf.  The payments these companies make include bonuses, rents, and royalties. The Office of Natural Resources Revenue (ONRR) collects these payments and distributes them. The payments go to federal and local governments and Native Americans.

I'll see if I can figure out how to make this update myself.

**Comment by Maroyafaied** [comment]
@mcharg I got grade 10, maybe because I didn't include the title heading. 
![image](https://user-images.githubusercontent.com/40175688/110346681-06068780-7fed-11eb-8fdb-3054f57453cb.png)

**Comment by mcharg** [comment]
@Maroyafaied I get 12 without the heading.  It looks like you might have an empty line above the text.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e2b6c8dc-2618-4bd6-8090-09e4b80f2553)
