### ISSUE TITLE
Make the bar charts look more clickable

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1399]
Now that the bars are all colored, it wasn't immediately obvious to all participants that they could interact with the charts.

**Comment by arcasarana** [comment]
![Clickable Bar Charts Compiled@2x](https://user-images.githubusercontent.com/36823491/115453249-63e1de00-a1ed-11eb-8160-30963ddfa8b5.jpg)

Here are some options.  Feedback? Questions?

@jlouis-onrr @Maroyafaied @mcharg @jnwang01 @branic18 @Baymatt

**Comment by mcharg** [comment]
I think A looks most clickable.  C is very close to the highlighting when selected that is on some browsers.

@jlouis-onrr Do you have input on which of these might work across all the browsers anomalies we've seen with these charts?

**Comment by mcharg** [comment]
Updated design.  @jlouis-onrr Does the second one here look doable?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fd64c2d9-bf3c-45e1-8701-c90415735451)

**Comment by jlouis-onrr** [comment]
that looks doable.

**Comment by mcharg** [comment]
I created #1528 to implement this change.
