### ISSUE TITLE
Review and update OGOR B study guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1411]
We made one a few sprints ago, but need to make sure it doesn't need updating.

**Comment by mcharg** [comment]
@Maroyafaied The guide is ready for you to review.
https://teams.microsoft.com/l/file/C59CCB32-B937-4A06-A635-4F96FD712FB1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F37_OGORB%2FOGOR.B.user.interview.study.guide.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg this looks good, I would also have this hand or link it to the guide incase any users have a specific question about a disposition code definition. https://www.onrr.gov/reportpay/pdfdocs/dispAdj.pdf
