### ISSUE TITLE
Add message indicating you can add only 4 cards if you try to add a 5th

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1413]

**Comment by arcasarana** [comment]
![4+ Cards - Frame 1](https://user-images.githubusercontent.com/36823491/114434978-9f4b2f80-9b91-11eb-9702-df46e83acf35.jpg)

Here's the XD developer link so Jerome can see the hex codes for the notifications.  The hex codes are from the pattern library.

https://xd.adobe.com/view/f4604731-f1b8-4a1b-930a-eab3faf1f328-a133/
