### ISSUE TITLE
Clarify that federal ownership is the percent of the state's land not the percent of federal land attributed to the state

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1414]
A couple of user interview participants weren't sure which it is.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f756ec0b-bd70-4239-837d-f163c4cc04ee)

**Comment by arcasarana** [comment]
Here's what I have so far.  I was also thinking of changing the width of the cards to make room for a line that would be longer but convey the information more accurately. <-- I can mock this up if you want to see it.

![% Federally Owned - state_federally_owned](https://user-images.githubusercontent.com/36823491/114444756-3964a500-9b9d-11eb-9264-15a25f3895de.jpg)

Thoughts? Feedback?

**Comment by mcharg** [comment]
@arcasarana What if you used the 2 letter state abbreviation to save space?  It might also clear up any confusion over "state land" being owned by the state.

"45.5% of CA land is federally owned"

**Comment by arcasarana** [comment]
Good idea!

![image](https://user-images.githubusercontent.com/36823491/114448285-5c915380-9ba1-11eb-805a-e9c0b8aac62a.png)

![image](https://user-images.githubusercontent.com/36823491/114448471-98c4b400-9ba1-11eb-83bb-2f57384f28fd.png)

Here are two implementations of it.  One bolded and one not.  The bolded one looks like it would have to be unaligned with the text at top to make it fit.  Maybe a smaller font size would do the trick?  The unbolded seems to fit.

**Comment by mcharg** [comment]
@arcasarana I think the unbolded works.

**Comment by Maroyafaied** [comment]
@arcasarana I like the unbolded one as well. Looks good

**Comment by arcasarana** [comment]
Ok, here's the unbolded one then we've settled on:

![image](https://user-images.githubusercontent.com/36823491/114720848-5d8fc580-9d06-11eb-9f0a-202d204b6e0f.png)

**Comment by mcharg** [comment]
I created #1485 to build this.
