### ISSUE TITLE
Add glossaries for OGOR B categories

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1438]
And possibly add disposition codes.

**Comment by Maroyafaied** [comment]
Make a list of categories that need definitions. with DC.

**Comment by mcharg** [comment]
This handbook chapter has descriptions of the codes.
https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-I.pdf

**Comment by mcharg** [comment]
From our meeting notes to include in glossaries:
* Some transfer to facility 11 or 12 is being reported as direct sales 01. Sales might be over-stated.  Facility does represent downstream sales.  Caveat that it's based on OGOR reporting. From 2013 told to report as 11 instead of 01 and companies didn't do it.
* Vented & flared - some companies were using 08 for royalty bearing until July 2019 - some still using 08 instead of 33 & 63.  They can go back and change them.

**Comment by Maroyafaied** [comment]
@Baymatt Can you please send me the link the to the worksheet you've been working on so I can review. Thanks

**Comment by Baymatt** [comment]
@Maroyafaied I've formatted it as a csv but I haven't created the actual file yet, would you like me to make it into an Excel worksheet and send it to you?

**Comment by Maroyafaied** [comment]
Sure that works.

**Comment by Baymatt** [comment]
[OGOR B Disposition Categories Glossary.xlsx](https://github.com/ONRR/nrrd/files/6382851/OGOR.B.Disposition.Categories.Glossary.xlsx)

**Comment by Baymatt** [comment]
Updated version with descriptions and tabs separating Oil and Gas codes

[OGOR.B.Disposition.Categories.Glossary-2.xlsx](https://github.com/ONRR/nrrd/files/6401153/OGOR.B.Disposition.Categories.Glossary-2.xlsx)
