### ISSUE TITLE
Create sample card sort for the IA Conference

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1469]
Waiting on the organizers to identify a topic relevant to the conference theme.

**Comment by mcharg** [comment]
Presentation is April 28.

**Comment by mcharg** [comment]
I also have a couple other things I need to do for this, so moving into this sprint.  Should get it done Friday.

**Comment by mcharg** [comment]
Done. @Maroyafaied @arcasarana Do you want to review?
https://github.com/theiaconf/CardSort/wiki

**Comment by Maroyafaied** [comment]
@mcharg I see the poster and it looks good, is there supposed to be an example of categories and subcategories?

**Comment by mcharg** [comment]
@Maroyafaied I added in a sample category and subcategory to the participant 1 project.
