### ISSUE TITLE
Change where US TreasuryAI lines from disbursements data are included in trends

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#147]
The US TreasuryAI lines in the monthly disbursments data actually reflect money that is going to Native Americans. AI represents American Indian. These numbers should be included in the Native American number, not the US Treasury number in the disbursements trends section.

We also should work with our disbursements data source to see if we can update that label to something that won't cause confusion, but I created ONRR/doi-extractives-data#4613 for that.

**Comment by mcharg** [comment]
Done
