### ISSUE TITLE
Fix bug in query tool

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1491]
A few users emailed that when they use the query tool and select production then click on Land Type filter , they get an error message.

**Comment by Maroyafaied** [comment]
Another error occurs when you are on revenue and try to filter for state/offshore region. 
![image](https://user-images.githubusercontent.com/40175688/114910682-6c947780-9ddb-11eb-82a4-b5fcf67bff5f.png)

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/30cb0479-cf1a-4e6c-a3af-36e6fcf702ae)

**Comment by mojobnichols** [comment]
The above two bugs seem fixed.   

a third bug (or newly introduced bug) seems to occur:

Production -> State/Offshore Region.
