### ISSUE TITLE
Change column name from commodity to product in monthly production download file

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#150]
This is continuation of ONRR/doi-extractives-data#4120. We are waiting on feedback from DORC before proceeding.

**Comment by mcharg** [comment]
@lpgoldstein Will check to see if this is still relevant.

**Comment by lpgoldstein** [comment]
Closing this because the data contained in the two different production files have different information for commodity and product. We also have both commodity and product in the revenue files.
