### ISSUE TITLE
Get homepage graphics into a prototype to test with users

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1510]

**Comment by arcasarana** [comment]
### **Here's the lo-fi mock for context:**

![image](https://user-images.githubusercontent.com/36823491/116105192-1519c580-a67f-11eb-88fa-350480884449.png)

### **Here's the content for revision.**

### Card 1
**Heading**
Companies lease property
**Front**
Companies pay to produce energy and minerals on federal lands, Native American lands, and the Outer Continental Shelf.
**Back**
Private individuals, corporations and state and local governments can also buy and own land. Whomever owns the land also owns the oil, gas, coal, and other minerals found below the surface.  [Go to interactive data about production.](https://revenuedata.doi.gov/?tab=tab-production)


### Card 2 
**Heading**
Companies produce energy & minerals
**Front** 
The payments these companies make include bonuses, rents, and royalties.
**Back**
Once a piece of land is leased, the leased land starts to produce commodities like oil.  Generally, these are sold by the producer.  The selling of these commodities results in revenue to the government. [Go to interactive data on revenue.](https://revenuedata.doi.gov/?tab=tab-revenue)


### Card 3
**Heading**
Companies pay ONRR
**Front**
The Office of Natural Resources Revenue (ONRR) collects these payments from companies.
**Back**
Payments can be in the form of royalties, bonuses, rent, inspection fees, civil penalties, or other types of revenue.  [Go to interactive data on revenue.](https://revenuedata.doi.gov/?tab=tab-revenue)


### Card 4
**Heading**
ONRR distributes funds
**Front**
ONRR distributes these payments to federal and local governments and Native Americans.
**Back**
Some types of disbursement include the Land and Water Conservation Fund, the Historic Preservation Fund, the U.S. Treasury, state governments, and the Reclamation Fund. [Go to interactive data on disbursements.](https://revenuedata.doi.gov/?tab=tab-disbursements)

**Comment by arcasarana** [comment]
@mcharg Any copy on the back of the cards I should revise?  Maroya mentioned something about linking to appropriate data so I tried to incorporate that as well as relevant info from Jamie's diagram.

Also, this was a note on the creative brief that we made but I don't quite understand it and where it fits in the cards: 
 "Federal & Native Americans have revenue production and disbursements. Private and statement-owned do not."

**Comment by mcharg** [comment]
@arcasarana 

### Card 1
**Heading**
Companies lease property
**Front**
Companies pay to produce energy and minerals on federal lands, Native American lands, and the Outer Continental Shelf.
**Back**
Private individuals, corporations and state and local governments can also buy and own land. Whomever owns the land also owns the oil, gas, coal, and other minerals found below the surface.  [Go to interactive data about production.](https://revenuedata.doi.gov/?tab=tab-production)
SM: Need to decide whether we want the data links to go to homepage tab, explore, or query. @Maroyafaied thoughts?  I was thinking query, but maybe this audience would be better geared towards explore.
SM: @arcasarana The note in the creative brief is referring to this.  We should say that this site only covers land owned by the federal government and Native Americans.


### Card 2 
**Heading**
Companies produce energy & minerals
**Front** 
The payments these companies make include bonuses, rents, and royalties.
SM: This would make more sense on Card 3.  Maybe move the first two sentences from the back to the front?
**Back**
Once a piece of land is leased, the leased land starts to produce commodities like oil.  Generally, these are sold by the producer.  The selling of these commodities results in revenue to the government. [Go to interactive data on revenue.](https://revenuedata.doi.gov/?tab=tab-revenue)


### Card 3
**Heading**
Companies pay ONRR
**Front**
The Office of Natural Resources Revenue (ONRR) collects these payments from companies.
SM: Add sentence from card 2.
**Back**
Payments can be in the form of royalties, bonuses, rent, inspection fees, civil penalties, or other types of revenue.  [Go to interactive data on revenue.](https://revenuedata.doi.gov/?tab=tab-revenue)


### Card 4
**Heading**
ONRR distributes funds
**Front**
ONRR distributes these payments to federal and local governments and Native Americans.
**Back**
Some types of disbursement include the Land and Water Conservation Fund, the Historic Preservation Fund, the U.S. Treasury, state governments, and the Reclamation Fund. [Go to interactive data on disbursements.](https://revenuedata.doi.gov/?tab=tab-disbursements)

**Comment by Maroyafaied** [comment]
@mcharg I think card 1 should link to how revenue works page and say say something like "Learn more". Card 2 should link to production data not revenue. I think all the data links should go to explore data rather than the query tool since it's more interactive.

**Comment by mcharg** [comment]
@arcasarana For the links going to Explore Data, we should label them "Explore [data type]" to be consistent with the other links to that page.

**Comment by arcasarana** [comment]
Ok,  I'll make an interactive prototype with those changes for testing and share the link.  I'm thinking it'll get done tomorrow. @Maroyafaied @mcharg

**Comment by mcharg** [comment]
@arcasarana Great.  Can you and @branic18 coordinate to make sure you have the same state of the homepage in the prototypes, so the only difference is the graphics?

**Comment by arcasarana** [comment]
Here's what I've got.  I put it in Slack, too.

https://xd.adobe.com/view/2b3a2522-1130-4dec-b577-4f07022a7af4-7e69/?fullscreen&hints=off
