### ISSUE TITLE
Plan user interviews for homepage graphic

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1511]

**Comment by branic18** [comment]
[Usability Study_ Homepage Graphic.pdf](https://github.com/ONRR/nrrd/files/6436630/Usability.Study_.Homepage.Graphic.pdf)
@Maroyafaied

**Comment by arcasarana** [comment]
@branic18 @Maroyafaied 

1. I think this is the issue I'm helping with correct?  Just making sure.
2. When's the deadline for the interviews to be done and when can we get started recruiting users?

**Comment by Maroyafaied** [comment]
@branic18 @mcharg the study looks good, please copy it to our team's folder so everyone can access it. @arcasarana we can start recruiting this sprint. We can do a practice round with our new employee if you'd like.

**Comment by mcharg** [comment]
@Maroyafaied I created a folder for the study and uploaded the plan.
https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=38_HomepageGraphic&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FNRRD%252FUser%2520Research%252FStudies%252F38_HomepageGraphic
