### ISSUE TITLE
Load disbursements monthly data 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1524]

**Comment by Maroyafaied** [comment]
Let @mojobnichols know what formatting is done manually.

**Comment by Maroyafaied** [comment]
@mojobnichols here are the Manuel[https://app.zenhub.com/files/215585796/fecc536d-d4f4-46c5-b05f-358384513af5/download](https://app.zenhub.com/files/215585796/fecc536d-d4f4-46c5-b05f-358384513af5/download) formatting we do to this file, I've also included the raw file for this month without the formatting. Let me know if you can incorporate these formatting in the database or if I should do it manually this month. Thanks

1. Delete Treasury Fund column - good for our knowledge and more detail if anyone asks but not needed. 

2. Change Hidalgo Caounty to Hidalgo County under county column 

3. Change "BLM - Permit Processing and Improvement" to "Lease Processing and Improvement" (BLM) under fund type column 

[https://app.zenhub.com/files/215585796/80f0e48e-a2be-4f34-8c9e-2d0d790b2a66/download](https://app.zenhub.com/files/215585796/80f0e48e-a2be-4f34-8c9e-2d0d790b2a66/download)

**Comment by mojobnichols** [comment]
@Maroyafaied  All of these could be incorporated into the load process.   And I think I would recommend it done that way so all changes are happening in load process. 

1.  Delete Treasury fund is not needed it's just a matter of not including it in the view that generates the downloads.   So this one isn't necessarily required in process anymore.

**Comment by Maroyafaied** [comment]
@mojobnichols ok should I do a PR with the raw file then and you can incorporate the other two in the load process?
