### ISSUE TITLE
Recruit participants for homepage study

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1525]

**Comment by CM805** [comment]
I've recruited Emily Clauss for the homepage study.  She has a degree in Communication from DU and is the Communications Director at WaterStone Community Church.  What contact info would you like for her?

**Comment by mcharg** [comment]
@arcasarana @branic18 Do one of you want to contact people, so you can make sure the times work with your schedule or would you like me to do it?

@CM805 You can send the 3 of us her email address via chat.
