### ISSUE TITLE
Give new employees training on Git and GitHub

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1544]
This presentation is helpful.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BC91DBBAC-6225-4886-9545-23FDA27CDF9E%7D&file=git%20%2B%20GitHub%20for%20onrr.gov%20workshop.pptx&wdOrigin=OFFICECOM-WEB.START.MRU&ct=1620664511110&action=edit&mobileredirect=true

**Comment by mcharg** [comment]
Scheduled for Tue, May 24.
