### ISSUE TITLE
Train new employees on user center design and usability testing 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1545]

**Comment by mcharg** [comment]
@Maroyafaied This is the deck I plan on presenting on Monday.  Let me know if you have any feedback.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/What%20We%20Do/UserResearch_Design.pptx?d=w36770fa925c046519de374f4777ce618&csf=1&web=1&e=eRmc0O
