### ISSUE TITLE
Reveiw Homepage MUI components

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/nrrd#155]

**Comment by jlouis-onrr** [comment]
MUI Components Homepage Review

- [ ] Update Bar Chart hover to be blues like production
- [ ] Reduce Bar Chart bar widths
- [ ] Change chart indicators to be square
- [ ] Lets try to get all colors locked in to 6 colors each
- [ ] Update trend dots to be grey
- [ ] Make bar chart dotted line a bit more pronounced, less like title
- [ ] Add xLabels with grey border
- [ ] Remove right padding/margin from, Filter links
- [ ] Create left margin break for all links
- [ ] Update Revenue by location line to not be underlined, change icon to blue
- [ ] Update Typography character width and count
- [ ] Mobile menu open issue
- [ ] Mobile tabs, increase width, stylize

**Comment by mcharg** [comment]
@jlouis-onrr I checked off the items that look good in your stylize branch.

- On the revenue by location icon, can you make it the link blue?
- I'll create a new issue (#176) for next sprint to figure out the colors.

The ones I didn't check, I either didn't know what they were or didn't see the change.

**Comment by jennmalcolm** [comment]
Creating separate issues for two remaining items.
