### ISSUE TITLE
Write alt text for homepage graphics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1552]

**Comment by daniel-coleman-1** [comment]
Can we link to the graphics here?

**Comment by mcharg** [comment]
https://xd.adobe.com/view/6b7d6581-992f-46a5-8d72-035d26beb875-3e2e/

**Comment by Maroyafaied** [comment]
@daniel-coleman-1  this issue is not assigned to the sprint we're in, this can wait till it's assigned.

**Comment by daniel-coleman-1** [comment]
[Alt Text](https://github.com/ONRR/nrrd/files/6941471/Alt.Text.8.5.docx)


Text:
The Production image shows a simple line drawing of an oil rig, a mechanical tower built above the sea. The oil rig has a line descending below into a dollar sign ($).  The dollar sign below the oil rig represents the natural resources that are extracted and sold.
Grade 5

The Revenue image shows a revenue document, a simple line drawing of a paper with a dollar sign ($).  As the dollar sign on the document denotes finance, this document could be for production reporting, royalty reporting, solid minerals reporting, or other documents companies submit to ONRR.
Grade 10

The Disbursement image shows simple line drawing of a node set. The central node contains a dollar sign ($) and is connected to six distal nodes.  The central node represents ONRR, and the distal nodes represent tribes, the Federal government, states, and local governments.  
Grade 7

**Comment by daniel-coleman-1** [comment]
@mcharg @arcasarana  what do you think?  Too repetitive in the beginning of the first sentences?

**Comment by mcharg** [comment]
@daniel-coleman-1 I think it's fine.
