### ISSUE TITLE
Recruit internal users for homepage study

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1561]
Recruiting email templates: https://teams.microsoft.com/l/file/BE542636-D0E1-40CE-9EF4-7CFA4326CBAD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FTemplates%2FRecruiting%20Email%20Templates.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by meshanw** [comment]
How many people do you need? And when should these be sent out? I have at least 2 people in mind who might be interested.

**Comment by mcharg** [comment]
@meshanw I'd say maybe 4 ish people would be good.  You can send them out now.
