### ISSUE TITLE
Add user interview plans and findings to GitHub

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1562]
We're behind in posting these.

**Comment by mcharg** [comment]
I added 38_HomepageGraphic for NRRD, so we could link to it from the blog post.

**Comment by cthomasONRR** [comment]
I added to NRRD:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/10b252ba-ebf4-4dbe-b950-5de2fad77615)
(36 was intentionally left off)

And I added to ONRR.GOV:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/6560a590-173e-49ad-a410-98d042e8307d)

Task is complete- closing now.
