### ISSUE TITLE
Better label or define federal offshore with no region

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1567]
![image](https://user-images.githubusercontent.com/40175688/119557903-0138b080-bd5e-11eb-8bcf-f5e4d5f5fe01.png)

**Comment by mojobnichols** [comment]
I have bandwidth to do this, but I need a label.  

My vote is:

Offshore  -  indicating it came from all( or any offshore region).   It stil has Land type indicating it is Federal offshore so that info is not lost. 

@Maroyafaied,  @mcharg,  @daniel-coleman-1

**Comment by mcharg** [comment]
What about "Other offshore" to make it clear it doesn't include the other ones.

**Comment by Maroyafaied** [comment]
@mcharg @mojobnichols I'm good with "Other offshore" if there's no region specified and still having land type as "Federal Offshore"

**Comment by Maroyafaied** [comment]
Not tied to a region. Make issue explaining glossary term.
