### ISSUE TITLE
Wiki link not working: Little rules for designing with data

### ISSUE THREAD

**Issue by CM805** [ONRR/nrrd#1573]
https://github.com/ONRR/nrrd/wiki/Little-rules-for-designing-with-data

![image](https://user-images.githubusercontent.com/83783622/119738724-5f3cc500-be3e-11eb-89c5-b494171bbc80.png)

![image](https://user-images.githubusercontent.com/83783622/119738750-695ec380-be3e-11eb-9b00-f8b2414e4071.png)

**Comment by mcharg** [comment]
We can link to the version of the state page in the archive.
https://archive.revenuedata.doi.gov/explore/UT/

**Comment by CM805** [comment]
Replaced link and verified it's working properly.
