### ISSUE TITLE
Broken link: Source file for revenue in the query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1580]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7d9662d9-729f-4eb7-a659-8f4434245395)

It's going here: https://revenuedata.doi.gov/downloads/federal-revenue-by-location/
We should update the link to: https://revenuedata.doi.gov/downloads/revenue/

And add a redirect for the old one.

**Comment by mcharg** [comment]
@Maroyafaied Did you put in the redirect or just fix the link in the query tool?

**Comment by Maroyafaied** [comment]
@mcharg I only fixed the link, I don't know how to do the redirect but I checked everywhere on the site and all of them link to the correct revenue download page.
