### ISSUE TITLE
Put together presentation for Government UX Summit

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1582]
Presentation is June 23.

**Comment by mcharg** [comment]
Slides due June 16.

**Comment by mcharg** [comment]
@Maroyafaied This is ready to review or you can wait until practice on Monday.  It's accessible in PPT.  They want it in PDF format, so I'll make sure it's accessible there after making any changes after practicing.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/Gov%20UX%20Summit/OpenSourceInformationArchitecture.pptx?d=wc36595837ab44aebaa3657f4fa98daed&csf=1&web=1&e=b7MMvE

**Comment by Maroyafaied** [comment]
@mcharg I looked at it quickly since we're going over it later today, but there's 2 title slides after each other (slide 10 & 11).. not sure if that was done on purpose but it was a bit confusing and maybe adding an outline slide in the beginning would help to know what to expect will be covered in the presentation.

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review again.  I took off the "I'm a NRRD" part of the logo and left the bison in brackets, since it's not about the NRRD site and I don't want to have to explain it.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fbc1f29d-0647-4d7b-9ae6-cde3bda9cc19)

**Comment by mcharg** [comment]
Accessible pdf version of the presentation.[OpenSourceInformationArtitecture.pdf](https://app.zenhub.com/files/215585796/b6d438ee-8824-49bb-aa2f-3341407b79f2/download)

**Comment by mcharg** [comment]
Presentation turned in.

**Comment by Maroyafaied** [comment]
@mcharg it looks good, I added 2 small comments.
