### ISSUE TITLE
Two different spellings of sulfur

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1583]
Only in Explore Data, revenue
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9df31b5a-c57c-4d1b-bafa-a2db652048c8)

**Comment by mojobnichols** [comment]
Closing because it seems to have been corrected in the data.   If it was manually corrected by us I think we should programmatically correct so we don't have to remember to do it manually in future.
