### ISSUE TITLE
Add something to what you might have missed updates

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1587]
This gests published on onrresource once a month. 

https://doimspp.sharepoint.com/:w:/s/ONRRWebContentTeam/EZQ_AoNinDVEoUSyErsmYBMB4V0BGsyGL3KBXq1ufuHDNw?e=CsN6Nz

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg I think for this edition I will just give a status update on the 508 project, let me know if you think we should include anything else and feel free to edit what I've written below. Thanks

Onrr.gov 508 Compliance Project Status

- Phase 1 (top 100 downloaded documents): 97% completed
- Phase 2 (next top 100 downloaded documents): 56% completed
- Phase 3 (remaining 3,184 documents) : 71% completed

**Comment by mcharg** [comment]
@Maroyafaied I think that works.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied  Ok sounds good, it also gives me a better idea of exactly what you're looking for in status updates moving forward.
