### ISSUE TITLE
Decide on Team's name

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1591]
Submit ideas and create a Polly for voting.

**Comment by mcharg** [comment]
Poll results: https://teams.microsoft.com/l/file/49E3384D-547B-421A-94F5-4F46B908FA39?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FAdmin%2FTeamName.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by CM805** [comment]
Maroya is giving the top name choices to Nathan
