### ISSUE TITLE
Consult SME how to calculate total production from OGOR B disposition codes 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1595]
Data Display work with Nadia Miller on identifying which OGOR B disposition codes should be used to calculate total production for Yearly file.

**Comment by Maroyafaied** [comment]
Send Nadia Miller an email.

**Comment by CM805** [comment]
@Maroyafaied how would you like me to help with this issue?

**Comment by Maroyafaied** [comment]
@CM805 not much to do right now till we see what Nadia says. Thanks

**Comment by Maroyafaied** [comment]
Replied to Nadia. She will let us know response from Stacey on a list of disposition codes to calculate total production.
