### ISSUE TITLE
Due Jul 1: Proposal for Interagency Accessibility Forum (IAAF) 

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1602]
[Proposal Info](https://app.zenhub.com/files/215585796/e4e85d48-26d3-4795-9796-4aa4c9c58393/download)

**Comment by mcharg** [comment]
@Maroyafaied Here's a draft of the proposal. https://doimspp-my.sharepoint.com/:b:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/IAAF_Proposal.pdf?csf=1&web=1&e=iSJ2aI

**Comment by Maroyafaied** [comment]
@mcharg This looks good, I only have one edit but it's not letting me do it in the document. Here it is 
![image](https://user-images.githubusercontent.com/40175688/123642389-79244b80-d7e0-11eb-9a57-be2966bc3e8a.png)

**Comment by mcharg** [comment]
@Maroyafaied I fixed the typo and submitted the proposal.
