### ISSUE TITLE
Add guidance around gender pronouns to the NRRD content guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1604]
Per this executive order, federal websites shouldn't use gendered pronouns.
https://www.whitehouse.gov/briefing-room/presidential-actions/2021/01/20/executive-order-preventing-and-combating-discrimination-on-basis-of-gender-identity-or-sexual-orientation/

**Comment by Maroyafaied** [comment]
Also add to the onrr.gov content guide.

**Comment by daniel-coleman-1** [comment]
I'm not seeing anything about government websites or gender pronouns in the executive order, the closest I see is:
"It is the policy of my Administration to prevent and combat discrimination on the basis of gender identity or sexual orientation, and to fully enforce Title VII and other laws that prohibit discrimination on the basis of gender identity or sexual orientation."

Gender neutral vocabulary options:
one
they
reporter/the reporter
mineral owner/the mineral owner
individual/the individual

Will follow up on this in Sync Up

**Comment by daniel-coleman-1** [comment]
https://www.whitehouse.gov/briefing-room/presidential-actions/2021/06/25/executive-order-on-diversity-equity-inclusion-and-accessibility-in-the-federal-workforce/

I think this one also applies here

**Comment by mcharg** [comment]
@daniel-coleman-1 In the DOI Web Council meeting, they interpreted the first one to include websites and documents. They did say that agencies don't have to go back and correct everything, but if something new comes out it shouldn't use gendered pronouns.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1  Since DOI web council interpreted it to apply to websites, let's add the guidance to the content guide so we are cautious of it. Thanks

**Comment by Maroyafaied** [comment]
update in both NRRD and Onrr.gov content guide.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 add this to the NRRD content guide

**Comment by daniel-coleman-1** [comment]
@Maroyafaied @mcharg this is ready for your review:
https://github.com/ONRR/nrrd/wiki/Content-style-guide

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks good.
