### ISSUE TITLE
Add FOGRMA Amendments to Federal Laws page

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1611]
We link to here on onrr.gov: https://www.onrr.gov/Laws_R_D/PubLaws/PL97451.htm

**Comment by Maroyafaied** [comment]
Review emails if this was supposed to be removed.

**Comment by mcharg** [comment]
@Maroyafaied Have you had a chance to take a look at your emails about this?

**Comment by Maroyafaied** [comment]
@mcharg I forwaded you the email for your reference, they basically asked for us to correct the link to FOGRMA in this page https://onrr.gov/compliance/index.htm.  It should be ok to add the same link to the federal law page as well.

**Comment by mcharg** [comment]
@Maroyafaied I'll add the amendments link we're using on onrr.gov.
