### ISSUE TITLE
Power Point for All hands meeting

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1612]
5 slides or less

**Comment by Maroyafaied** [comment]
@mcharg @daniel-coleman-1 Let me know if you have any feedback on this presentation, it's supposed to be for only 10 min and to introduce what the team does and how we work. https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B3555f5b1-05a5-4275-861b-0edeefd12129%7D&action=edit&wdPreviousSession=24c3f22c-6cc2-7891-91ca-970aed973c08

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 If you'd like me to add a pic for you , please send it to me.

**Comment by mcharg** [comment]
@Maroyafaied Looks good.
