### ISSUE TITLE
Finalize team name 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1617]
Nathan would like us to chose 3-5 names and have all of IDM vote on the best name with the option for them to suggest a name.  He doesn't wants us to use NRRD as an acronym and not use Digital Services in the name.  He does like using open data and/or user experience in the team name. 

Here are some ideas

- Open Data & User Experience ( Data & User Experience was our top vote so this is just adding "Open" to it)
-  Open Data Design and Development

**Comment by CM805** [comment]
@Maroyafaied do you think we should first send something out giving people the option to suggest a name (or you can send out an email asking them to email suggestions to be by a certain date)?  Then we can send a follow up to have people vote on a name.  My concern is that we will have people vote on a name and have more suggestions come in and then have to send a second survey anyways.

**Comment by Maroyafaied** [comment]
@CM805 That's a good suggestion, I'll run it by Nathan today during our check in and let you know his thoughts.

**Comment by Maroyafaied** [comment]
I send Nathan email to choose.
