### ISSUE TITLE
Define glossaries for default cards in explore data

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1622]
- Define Nationwide federal
- Define Native American

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 draft and add definition in glossary file.  Look into other places on the site to add the definitions to.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'd like to include the definitions with the next release , can you draft a definition for Native American clarifying that location is withheld from that data and draft a definition for "Nationwide Federal" clarifying that data is only federal onshore and offshore and doesn't include Native American. data

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg please review the drafted definitions. 

Nationwide Federal: This data includes natural resources extracted from United States federal lands and waters.  It does not include Native American lands, privately owned lands or sate-owned lands. Federal data is available by location.

Native American: This data includes natural resources from Native American lands only. Location data is withheld from Native American data.

**Comment by mcharg** [comment]
@Maroyafaied I would change "extracted from" to "produced on".  Otherwise, looks good.

**Comment by Maroyafaied** [comment]
@mcharg Thanks, I made the change.  @jlouis-onrr can you these as definitions in explore data cards? Thanks

Nationwide Federal: This data includes natural resources produced on United States federal lands and waters. It does not include Native American lands, privately owned lands or state-owned lands. Federal data is available by location.

Native American: This data includes natural resources produced on Native American lands only. Location data is withheld from Native American data.
