### ISSUE TITLE
Decide on an approach to content guides

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1625]
Decide if we should have a content guide for each website or consolidate into one content guide.

**Comment by daniel-coleman-1** [comment]
Approach to style guides:

- [ ]  Evaluate topics from other agencies to determine value to our sites
- [ ]  Create topics list for NRRD
- [ ] Create topics list for ONRR.gov
- [ ] Finalize content guidance inside NRRD topic list
- [ ] Finalize content guidance inside of ONRR.gov topic list
- [ ] Submit for review

If we find it useful to combine the two, or portions of them, we'll do so during the review process
