### ISSUE TITLE
Complete content guides 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1626]

**Comment by daniel-coleman-1** [comment]
https://digital.gov/resources/style-guides-by-government-agencies/

Includes a list of several agencies' content style guides

**Comment by daniel-coleman-1** [comment]
Approach to style guides:

- [ ] Evaluate topics from other agencies to determine value to our sites
- [ ]  Create topics list for NRRD
- [ ]  Create topics list for ONRR.gov
- [ ]  Finalize content guidance inside NRRD topic list
- [ ]  Finalize content guidance inside of ONRR.gov topic list
- [ ]  Submit for review

If we find it useful to combine the two, or portions of them, we'll do so during the review process
