### ISSUE TITLE
Decide on icons for revenue and disbursements

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1632]
I put a bunch of options in chat for the team to provide feedback on.

**Comment by mcharg** [comment]
I think we should use the ones in this prototype.  @Maroyafaied Are you good with that?
https://xd.adobe.com/view/6b7d6581-992f-46a5-8d72-035d26beb875-3e2e/

**Comment by Maroyafaied** [comment]
@mcharg Yes, I'm good with it.
