### ISSUE TITLE
Update how to upload data on wiki and review data checklist 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1635]

**Comment by cthomasONRR** [comment]
This is a duplicate issue, and can be closed. Issues this one duplicated are:
#1168 https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/1668
#1675 https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/1675
