### ISSUE TITLE
Join community of practice - Digital.gov

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1638]
Look into groups and become a member to anything relevant to our area of knowledge. 

https://digital.gov/communities/

**Comment by daniel-coleman-1** [comment]
(instructions from one of my listservs this morning)
Joining multiple communities can add a significant number of unread emails to your inbox, which can feel overwhelming. 
A rule that automatically moves the messages to a folder will still allow you to receive the emails, but lessen the anxiety of having multiple unread emails within your inbox.  You can use the following steps to quickly setup a rule:

1.	Select a message from the XYZ@LISTSERV.GSA.GOV address
2.	Select the “Home” tab within Outlook, select “Rules” and select “Always Move Messages from: XYZ”
![1 123](https://user-images.githubusercontent.com/83892362/126665708-534d8eda-aee1-4c4b-ab4c-938fc38e9c74.png)

3.	In the “Rules and Alerts” dialog box, select the folder that you want the emails to automatically be moved into and select “OK.”
![2 123](https://user-images.githubusercontent.com/83892362/126665804-ef81500e-a23d-4142-b650-7a7f1feea441.png)

**Comment by Maroyafaied** [comment]
one point for each person.

**Comment by cthomasONRR** [comment]
I just joined:

- IT accessibility and Section 508
- Open Data Community
- Open Gov

**Comment by mcharg** [comment]
I joined a bunch a few weeks ago.

**Comment by lpgoldstein** [comment]
I also joined a bunch
