### ISSUE TITLE
Write Business Justification for Using Slack

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1639]
https://marketplace.fedramp.gov/#!/agency/department-of-the-interior?sort=name

The Federal Risk And Management Program Dashboard (fedramp.gov)

**Comment by Maroyafaied** [comment]
[Slack Data Sheet.pdf](https://github.com/ONRR/nrrd/files/6786920/Slack.Data.Sheet.pdf)

**Comment by shannonmcharg** [comment]
@Maroyafaied Slack is FedRAMP Authorized?!?!

**Comment by Maroyafaied** [comment]
@shannonmcharg Yep! I learned that on Thursday. Also GitHub is authorized.  I was told that there's an agency in DOI that uses Slack so our approval shouldn't take long. They would like a few paragraphs explaining how we started using Slack and how we are using it and to mention integration with GitHub.

**Comment by Maroyafaied** [comment]
@mcharg Here's my first draft, can you review and add/delete what you see fit. https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/Slack%20Business%20Justification.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied I reviewed and added some stuff.
