### ISSUE TITLE
Bug: Query tool displays no data when you click "clear all"

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1642]
@CM805 found this issue when reviewing data, if you choose filters then click clear all, you get this 
![image](https://user-images.githubusercontent.com/40175688/125628181-c646e2ed-775a-4e24-bb7f-ad2032af7340.png)

**Comment by CM805** [comment]
@Maroyafaied and @mojobnichols let me know what you need me to do and when for this.  I'm assuming I'll just check functionality once the bug is fixed.
