### ISSUE TITLE
Q2 & Q3  accomplishment report 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1643]
@mcharg please add metrics numbers and review. Thanks

Q2 - https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/Data%20Display%20Accomplishments%20-%20FY21%20Q2.docx?web=1

Q3 - https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/Data%20Display%20Accomplishments%20-%20FY%2021%20Q3.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied I added metrics and reviewed.

**Comment by Maroyafaied** [comment]
Send to Nathan.
