### ISSUE TITLE
Finalize content for homepage graphic

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1645]
https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD~2FShared%20Documents~2FGeneral~2Fonrr_homepage_graphic_content.docx?threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&messageId=-1&baseUrl=https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD&fileId=4f667b4c-babd-421a-9de1-449d07ee3166&ctx=chiclet&viewerAction=view

**Comment by daniel-coleman-1** [comment]
Added some updates and some notes

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I haven't had a chance to look at this yet, but I would like for Nathan to review it and approve it once it's finalized since it'll be on the homepage.

**Comment by mcharg** [comment]
@daniel-coleman-1 I went through and added another round of comments.

**Comment by mcharg** [comment]
@daniel-coleman-1 I responded to your last round of comments.

**Comment by daniel-coleman-1** [comment]
@mcharg I made some edits and responded to your comments

**Comment by mcharg** [comment]
@daniel-coleman-1 I think this is ready for @Maroyafaied to review when she gets back.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please see my comments in the doc.

**Comment by daniel-coleman-1** [comment]
@maroya edited following our chat, please see my comments in the doc.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I reviewed, looks good but we still need content for the back of the production card.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This looks good, I'll have Nathan review it once we add the revised content to the card design.
