### ISSUE TITLE
Daniel Axshare Access

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1651]
Dan needs access to Axshare

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please put in a non core software request, you have to be on vpn to submit this.  Here's the link and the info I used to fill mine out for your reference. 

https://bsee.servicenowservices.com/sp?id=non_core&sys_id=d0f75bf76faa21001481202fae3ee411

Who is this ticket requested for?: Maroya Faied (faiedm)
Non-Core Software: Axure RP 9
Software Title: Axure RP 9
Software Version: 9.0.0.3662
User Company: ONRR
If a different version is required check this box.: true
Enter the specific version of the software you are requesting.: RP 10
Business Justification: To create prototypes for onrr.gov and NRRD. I'd like this license transferred to me. 
Key: lCyNr0xPqNhL8BykygQHlcy5E7imbZJ/xyF4sN8T2ohc0YjVz7E0TAx9VwKqu9l+
Date the Software is needed: 2021-04-08
Supervisor / COR: Patricia Damon (damonp)
Office: ONRR-Core
Created In SP: true
Cloud?: No
EULA Acceptable?: Yes
Unauthorized ports?: No
Third Party Programs?: No
Pre-Requisite Programs?: No
Security Outcome: no vulns

**Comment by daniel-coleman-1** [comment]
Submitted

**Comment by daniel-coleman-1** [comment]
Installed and good to go!
