### ISSUE TITLE
Add using plain language and active voice to content guide

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1655]
This should be added to both content guides.

**Comment by daniel-coleman-1** [comment]
Added to both the ONRR and NRRD wikis

![Active_voiceJuly20](https://user-images.githubusercontent.com/83892362/126347028-096913bf-d703-4096-995f-84ac99ab5586.jpg)


![Plain_languageJuly20](https://user-images.githubusercontent.com/83892362/126347054-5a2a6233-b86d-4131-a813-1de6f9960fbe.jpg)
