### ISSUE TITLE
Standardize how "United States" should be abbreviated 

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#1659]
I'm working on the NRRD Glossary and noticing that we are sometimes abbreviating "United States" as "US" and other times with periods as "U.S." See image below as an example:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/d6f1ca70-5779-4b51-8138-d9d9ec203d90)

@daniel-coleman-1 , could you please make a decision and update the content guide?

Thanks!

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-07-26 092928](https://user-images.githubusercontent.com/83892362/127016341-d79ad7ed-0a5d-4241-86ef-266698676a69.png)

It's in there, I am thinking this should be a part of the content audit.

**Comment by cthomasONRR** [comment]
OK, I will close this issue and we can address it as part of the content audit.
