### ISSUE TITLE
Upload June disbursements data

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1664]

**Comment by Maroyafaied** [comment]
check data against data check list

**Comment by Maroyafaied** [comment]
[Original data ](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/FY21/Q3%20Total%20Web%20Data%20(Jun).xlsx?web=1)

**Comment by cthomasONRR** [comment]
Data has been uploaded.
This is now part of Pull Request #1671
https://github.com/ONRR/nrrd/pull/1671

**Comment by cthomasONRR** [comment]
The data was uploaded and reviewed. This issue can be closed.
