### ISSUE TITLE
Defining State/Offshore Region Query Data terms in NRRD

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#1665]
There are 4 undefined terms within the State/Offshore Region Query Data:
Location not published
Not tied to a lease
Not tied to a location
Not tied to a region

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/b5de1b19-8853-4457-acc7-8e2a4939eeed)

These 4 terms and the data associated with them need to be analyzed, to determine if they need to be defined, combined with another term, or removed.

**Comment by Maroyafaied** [comment]
Not tied to a lease - label only used in revenue data, should be for revenue types like civil penalties that don't have  either onshore or offshore as land category or don't have a commodity listed. 

Location not published - label used in revenue and production data, should be used for Native American data.

Not tied to a region - label used in revenue data, for data labeled as offshore but don't have a region listed. 

Not tied to a location - @mojobnichols can you remind me how we're using this label and how it's different from not tied to a lease label?

**Comment by Maroyafaied** [comment]
@mojobnichols I believe everything labeled "not tied to a location" should be labeled as "not tied to a lease" according to this closed issue. https://github.com/ONRR/nrrd/issues/1320

**Comment by Maroyafaied** [comment]
@cthomasONRR Great job, that's a good start! You should be able to replicate not tied to a region by filtering for offshore for land category and filtering for "blanks" in offshore region. Let me know if it works for you, I attached a pic.  Also, it seems like from your findings, we can't combine not tied to location data with not tied to a lease since that data has onshore as land category?
![image](https://user-images.githubusercontent.com/40175688/128035214-dc570c6c-37a4-492a-8cb2-9eb8edc12e15.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied - 

Thanks - I was able to replicate "Not Tied to a Region" by filtering the offshore region to 'blank'!

Right now, I'm not sure if we can combine any of these 4 region types. 
For "Not Tied to a Lease", it is associated to the specific "Not Tied to a Lease" land category. This is a category independent of onshore and offshore. "Not Tied to a Location" is onshore only, and "Not Tied to a Region" is offshore only. So to me, it doesn't look like any of these can be combined.

**Comment by Maroyafaied** [comment]
@cthomasONRR I agree that we can't combine the labels. Can you draft glossary terms for all 4 labels based on your findings and I'll review. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied, let me know what you think!

- Location Not Published: We conceal all location data for Native American production, revenue, and disbursements.

- Not Tied to a Location: This term indicates Federal onshore revenue data that did not include a location.

- Not Tied to a Lease: This term indicates Federal revenue data that either did not include a location, or did not include a commodity.

- Not Tied to a Region: This term indicates Federal offshore revenue data that did not include a regional location.

**Comment by Maroyafaied** [comment]
@cthomasONRR  I made changes to the "Location not published" label, the other labels definitions look good. @mcharg @daniel-coleman-1 can you review?

- Location Not Published: Location data is not published for Native American data, it is only available at the national level to protect private and personally identifiable information. 

- Not Tied to a Location: This term indicates Federal onshore revenue data that did not include a location.

- Not Tied to a Lease: This term indicates Federal revenue data that either did not include a location, or did not include a commodity.

- Not Tied to a Region: This term indicates Federal offshore revenue data that did not include a regional location.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks!!!

**Comment by mcharg** [comment]
Revised to reduce reading level.

- Location Not Published: Location data isn't published for Native American data. It's only available at the national level. This protects private data and personally identifiable information (PII). (Post-Graduate to Grade 10)
- Not Tied to a Location: This term indicates Federal onshore revenue data that did not include a location. (Grade 10, no edits)
- Not Tied to a Lease: This term indicates Federal revenue data that  did not include either a location or a commodity. (Grade 11 to Grade 10)
- Not Tied to a Region: This term indicates Federal offshore revenue data that did not include a region. (Grade 11 to Grade 9)

**Comment by Maroyafaied** [comment]
@cthomasONRR I've already merged the adding glossaries PR you had earlier so you'll have to create a new PR for these terms. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied I think I still need some hand-holding for the process of making a PR. I'll set up a meeting for us to do it together.

**Comment by Maroyafaied** [comment]
@cthomasONRR sounds good, I'd be happy to help.

**Comment by cthomasONRR** [comment]
@Maroyafaied 

"Not Tied to a Lease" already had a definition: "Some revenues - such as civil penalties - are not tied to either onshore or offshore"

Are we ok replacing this definition with the new one? Just want to make sure!
