### ISSUE TITLE
Review interns applications

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1667]
@Maroyafaied I will check if applications came through, then I will have you guys do resume views and/or interviews.

**Comment by Maroyafaied** [comment]
I'm still not seeing any applicants which is weird because I know at least of one applicant that applied to the data one.  I will reach out and see when we should be seeing applicants.

**Comment by Maroyafaied** [comment]
Below is the response I received, I'll wait till we receive an email to review application material.

"Dear Maroya,

We are almost there!  USAJobs had some technical issues, so we extended the application period to Aug. 2.  As soon as we receive the data transfer form USAJobs,  we will send an email letting mentors know they can log in to review application materials.

By the way, one of our interns introduced us to picktime.com, which is more helpful for scheduling applicant interviews than emailing back and forth about availability."

**Comment by mcharg** [comment]
Spreadsheet is in this folder.  I also copied the interview question docs from last year that we can use as a starting point.
https://doimspp-my.sharepoint.com/:f:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Interns/2021?csf=1&web=1&e=pQrhJT

**Comment by cthomasONRR** [comment]
I'm reading through application and putting additional comments in the notes section of the spreadsheet.

**Comment by Maroyafaied** [comment]
Please see my comment in the excel sheet regarding the applicant Rawa. Thanks
