### ISSUE TITLE
Write steps of how to upload data in wiki

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1668]

**Comment by Maroyafaied** [comment]
1. Save original file in Teams folder (General>NRRD>Data)

**Comment by cthomasONRR** [comment]
I created a section for "How to upload monthly datasets" here:
https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great, I made minor edits and I also include this page on the navigation menu under "Data". We can close this issue for now and you can use these steps the next time we have data to upload and make changes if needed. Thanks!

![image](https://user-images.githubusercontent.com/40175688/128068747-c1939a98-f240-4efc-afe0-f4a1872d9288.png)
