### ISSUE TITLE
Create Data Procedure form 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1669]
There's 3 procedure forms and they are outdated since we've been using the database. We need to create one procedure form for all 3 data sets and archive the outdated ones in a folder.

https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Disbursements/Monthly%20Disbursements%20Procedure.docx?web=1

**Comment by lpgoldstein** [comment]
@cthomasONRR I used the wiki as a basis and added some screens shots. The only thing I think might be confusing is that all of the data sets go into the same PR, but I'm not yet sure how to make it more clear until I work through it. Please take a look and edit as you please - no hurry either. Thanks!

**Comment by cthomasONRR** [comment]
@lpgoldstein - I reviewed and added in comments last week. Is this ready for @Maroyafaied to review?

**Comment by lpgoldstein** [comment]
@cthomasONRR Yes @Maroyafaied This is ready for your review. You'll see a comment in the document that addresses next steps as well.

**Comment by Maroyafaied** [comment]
@lpgoldstein I reviewed and added a couple of comments. Thanks

**Comment by lpgoldstein** [comment]
@Maroyafaied I incorporated your comments. Is this okay to close?

**Comment by Maroyafaied** [comment]
@lpgoldstein yes, looks good. Thanks
