### ISSUE TITLE
Review and update wiki content in nrrd repo

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#167]
Make sure things are still relevant and none of the links are to the old repo.
https://github.com/ONRR/nrrd/wiki

**Comment by jennmalcolm** [comment]
First step is to audit (create spreadsheet with results) the wiki and determine which items need updates as a result of our more to cloud.gov

**Comment by mentastc** [comment]
Updated a lot of the pages that just needed updated links the following is a list of pages that need a more extensive update.


Link | Comment
-- | --
https://github.com/ONRR/nrrd/wiki/Analytics-Segments-and-Reports | Not sure if our not having google has changed this page
https://github.com/ONRR/nrrd/wiki/Content-and-data-maintenance-notes | Very out of date
https://github.com/ONRR/nrrd/wiki/Continuous-integration-tools | Will be out of date when we switch repos
https://github.com/ONRR/nrrd/wiki/Data-Catalog | Out of date
https://github.com/ONRR/nrrd/wiki/Onboarding-checklist | Out of date, goggle drive and slack stuff
https://github.com/ONRR/nrrd/wiki/Preview-urls | Will need updating when we move repos
https://github.com/ONRR/nrrd/wiki/Problem-statement | Out of date
  |
