### ISSUE TITLE
visualize 508 compliance progress and analytics

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1673]
Nathan asked for us to provide visuals for analytics and 508 compliance to include in an end of year report for Howard.

**Comment by mcharg** [comment]
I started a deck with some ideas.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/What%20We%20Do/FY21Analytics.pptx?d=w1d54152e90614166a953ca2a1207e340&csf=1&web=1&e=hq9zpq

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR I updated the deck based on on conversation.  Let me know if you have additional feedback.  I can play with colors tomorrow.

**Comment by cthomasONRR** [comment]
@mcharg I added in some comments on the slides. Thanks!!

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR Updated colors and addressed Christine's comments.

**Comment by cthomasONRR** [comment]
@mcharg The changes look great!

**Comment by Maroyafaied** [comment]
@mcharg Thank you for work on this , I added a couple of comments. Looks great overall!

**Comment by Maroyafaied** [comment]
@mcharg Here are the dates of emails send and deadline given for each phase

Phase 1; Email send on 11/9/2020 with deadline of 12/31/2020 except for Lee Ann Martin (April Lockler) was given a deadline of 3/31/2021

Phase 2 : Email send on 2/3/2021 with deadline of 3/31/2021. Email send for April Lockler on 4/1/2021 with deadline of 6/31/2021.

Phase 3: Email send 6/28 with deadline for decisions to correct or remove by 7/31/2021 , hope to be done with this phase beginning of Nov 2021 (one year from initiation of phase !)

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR Added a timeline to slide 13.  Still playing with visuals for the documents.

**Comment by Maroyafaied** [comment]
@mcharg I like the timeline a lot. I'll show the updates to Nathan tomorrow during our check in for feedback.

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR I added a slide at the end showing that users are likely finding the correct handbook file more easily as a result of the handbook design.  That's all I'll add before Maroya meets with Nathan, unless @lpgoldstein has discovered anything else looking at metrics.

**Comment by cthomasONRR** [comment]
Looks great! Thanks for al your work on this!

**Comment by Maroyafaied** [comment]
@mcharg Thanks, it looks good. I'll show it to Nathan during our next check in but we're good to close this issue for now and refer to it as needed.
