### ISSUE TITLE
Create presentation for Interagency Accessibility Forum (IAAF) 

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1680]
[Proposal](https://doimspp-my.sharepoint.com/:b:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/IAAF_Proposal.pdf?csf=1&web=1&e=CBtm8A)

Presentation is October 13

**Comment by mcharg** [comment]
@Maroyafaied I'm going to start working on this based on the blog post, so we can take Sid up on his offer to give feedback.

**Comment by Maroyafaied** [comment]
@mcharg sounds good, let me know how I can help.

**Comment by mcharg** [comment]
@Maroyafaied I started with some of the slides from the analytics deck.  Will fill in with more from the blog post tomorrow.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/IAAF/IAAF_Presentation_ONRR.pptx?d=wde350753b5be4a89b9337211a6e88396&csf=1&web=1&e=UX0cPP

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein I sent the presentation and all the other stuff to the IAAF team.
