### ISSUE TITLE
Connect with Bicameral D.C. Stakeholders

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1698]
1. Determine States for outreach
2. Make a list of both Senators and all Representatives from each state
3. Add contact information for each office
4. Call each office and request the name and contact for the intern coordinator
5. Connect with each office's intern coordinator and brief on user research, request participation from their interns
6. List all intern coordinators in a file on the share drive (expect high annual turnover)

**Comment by daniel-coleman-1** [comment]
In determining states for outreach I assessed the states who take in the most money from natural resources using this incredibly handy [Natural Resource Revenue](revenuedata.doi.gov) website.  Based on that, I identified the following states: CO, LA, NM, UT, WY, and MD.  These states have a combined 19 House seats and 12 Senate seats.

However, many of the Representatives and Senators in these states have policy priorities that are not connected to natural resources.  They're busy and they have bigger fish to fry, so going with all of these sets of staffers may not be the highest and best use of our or their time.

Following that I assessed House subcommittees of the House Natural Resources Committee.  The Subcommittee on Energy and Natural Resources has 8 listed Members and the Subcommittee for Indigenous Peoples of the United States has 8 listed Members, two Members are on each subcommittee bringing the total to 14.

The Senate Subcommittee on Public Lands, Forests, and Mining has 14 listed members, and two leaders, a Democratic committee office and a Republican committee office, bringing the total to 18 (14+2+2).

I propose we do outreach to those offices, as I perceive them to be our main stakeholders on the Hill.

**Comment by daniel-coleman-1** [comment]
Senate Side:
Senate Committee on Energy and Natural Resources Subcommittee on Public Lands, Forests and Mining (all members)
Senate Finance Committee Subcommittee on Energy, Natural Resources and Infrastructure (all members)

House side:
House Committee on Natural Resources Subcommittee for Indigenous Peoples of the United States (all members)
House Committee on Natural Resources Subcommittee on Energy and Natural Resources (all members)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm closing this issue  since at stand up you asked for it to be moved to next sprint so you can finish your other work.  Since we are in maintenance mode for NRRD, outreach is not a priority right now and I'd like you to focus on completing the updates for the sitemap. We can revisit this when we are in need to do outreach.
