### ISSUE TITLE
July disbursements data 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#1699]

**Comment by cthomasONRR** [comment]
@lpgoldstein do you need any help with this upload? I can likely get it done today if you're busy. Thanks!

**Comment by cthomasONRR** [comment]
Data is successfully uploaded to an existing PR: https://github.com/ONRR/nrrd/pull/1689

**Comment by lpgoldstein** [comment]
first issue found with downloaded data - this should just be calcasieu
![image](https://user-images.githubusercontent.com/39419003/131369857-bc27864d-15ed-47aa-94c6-e4672bb120be.png)

**Comment by cthomasONRR** [comment]
I think it's "Calcasieu Parish" because it's in Louisiana, and they have parishes instead of counties.

**Comment by lpgoldstein** [comment]
It is but we don't list county or parish in the name, right?

**Comment by cthomasONRR** [comment]
Yeah.... it looks like an error that only 2 have "Paris" ...  I think we need @mojobnichols's help to remove the "Paris" on these 2 line items.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/a7b3213a-948c-44a0-8e47-cdb5ff751e9b)

**Comment by cthomasONRR** [comment]
I'm noticing something odd when comparing the raw data to the downloaded data: the July 2021 sums are the same, but the total line item count is not. The raw data has 363 line items and the downloaded data only has 352. They both have a disbursement sum of $924,409,786.8. Does this have something to do with deleting the Treasury Fund column?

**Comment by lpgoldstein** [comment]
It shouldn't. We delete that every month. I'll look too.

**Comment by lpgoldstein** [comment]
@cthomasONRR This is probably one of the roll ups 
![image](https://user-images.githubusercontent.com/39419003/131376621-e3030852-560b-49a3-81a6-47e6ceccbe92.png)

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR I believe any lines that have the same Fund type, commodity and revenue type will be rolled up.  @mojobnichols Is that correct?

**Comment by lpgoldstein** [comment]
@Maroyafaied that's what I think is happening too. I just want to make sure that the numbers look okay when they are rolled up. They likely do since the totals all match.

**Comment by cthomasONRR** [comment]
For the public-facing dataset, should some of these Fund Types be combined? Like 'U.S. Treasury' and 'U.S. Treasury AI'? I thought that this was one of the 'roll ups'?
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/28fd35ba-c6f0-40a7-a5c9-3236a998845b)

**Comment by lpgoldstein** [comment]
@cthomasONRR I believe that U.S. Treasury AI is directed towards American Indians. If anything it would be rolled up with Native American Tribes & Allottees but when we had this discussion maybe a year and a half ago with FM they strongly believed that we shouldn't roll up that item.

**Comment by cthomasONRR** [comment]
@lpgoldstein OK, thanks for the explanation!

**Comment by cthomasONRR** [comment]
I was able to go through the disbursements data checklist, and everything looks good. It's just those 'roll ups' and 'Parish' issues that were throwing me. @lpgoldstein let me know if you're ok with me closing this issue. Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR Looks good to me!
