### ISSUE TITLE
Future Metrics

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1708]
Decide on metrics for the upcoming fiscal year and look into features in Zenhub.

**Comment by lpgoldstein** [comment]
[onrr.gov metrics](https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/EWoa1xIlZSxIip45nuC_uhgBJ3D1D3omd62y2GqeO3lawg?e=BRCmzw)

[nrrd metrics](https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/EYhMmpAIa1lLsWhB5Wuyhd0BlE-aPKP7Z0OLrMukM1aItw?e=4KFpqt)
