### ISSUE TITLE
Complete Mentoring Objectives Worksheet

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#1710]
Hi Kiara,

This task is for you to read through and complete the [Mentoring Engagement Objectives](https://app.zenhub.com/files/215585796/aa304481-15c1-484b-bc07-f2145e6ee34f/download) worksheet.

You can comment in this issue if you have any questions about the worksheet.
Also please comment when you're ready to discuss and we can set up a meeting to do so.

Thanks!
Christine

**Comment by kjgdata** [comment]
@cthomasONRR Uploading Mentoring worksheet as we discussed #
[Mentoring Worksheet_GomezKiara.docx](https://github.com/ONRR/nrrd/files/7219830/Mentoring.Worksheet_GomezKiara.docx)
