### ISSUE TITLE
Menu is missing on mobile

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1713]
This is occurring both in dev and on the live site on both my iPhone SE (Safari) and Android (Chrome).

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/083c90fa-07f9-466e-845e-5ae4e3126f15)

**Comment by jlouis-onrr** [comment]
@mcharg, just put a update out for this here:
https://nrrd-preview.app.cloud.gov/sites/1713-MobileMenuMissing/

Once reviewed and good I'll merge this into dev.

**Comment by mcharg** [comment]
@jlouis-onrr It's working on both my phones.

**Comment by jlouis-onrr** [comment]
@mcharg, cool I'm going to merge it into dev
