### ISSUE TITLE
Negative number bar design on the Explore Data Page, Nationwide revenue summary

### ISSUE THREAD

**Issue by cvojslavek** [ONRR/nrrd#1716]
This is to come up with negative number bar design ideas when a bar doesn't show up because either the total number is negative or one of the items (e.g., Federal onshore) is negative. See the example below from the Other Revenues section of the [Explore Data Page](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2020), Nationwide revenue summary tab:
![image](https://user-images.githubusercontent.com/89403899/132399481-44dac83f-1dd3-4932-bcc0-c53261e1b777.png)

**Comment by jkwonatx** [comment]
@kmhtran have you checked this out yet? Would you be interested in giving it a thought together?

**Comment by mcharg** [comment]
For reference, #1299 shows what we're doing on the vertical bar charts.

**Comment by mcharg** [comment]
And #476 has some designs for other types of charts that haven't been implemented yet.

**Comment by kmhtran** [comment]
@jkwonatx Sure, we can definitely work through this one together. We can gather some ideas and meet to discuss what we've come up with.

**Comment by jkwonatx** [comment]
> @jkwonatx Sure, we can definitely work through this one together. We can gather some ideas and meet to discuss what we've come up with.

Sounds good. I'll ping you in a few hours. We can meet on Tuesday if you're available.  @mcharg do we have a specific timeline for this issue?

**Comment by mcharg** [comment]
@jkwonatx I would say by the end of next sprint, unless you don't have time with user interviews, then it can wait until the sprint after.

**Comment by mcharg** [comment]
There's also an explanation about negative numbers on the fact sheet under revenue that might be useful to consider. https://revenuedata.doi.gov/fact-sheet

**Comment by mcharg** [comment]
#1409 is also relevant because we want to have all the graphs under Revenue by Company use the same color for the same thing, but they don't currently.

**Comment by mcharg** [comment]
Negative numbers will occur most often in Other Revenue because that includes Civil Penalties.

**Comment by jkwonatx** [comment]
I came up with two ideas to solve this issue. Before coming up with the idea, I understood the bar to be a visualization of the dollar value of the revenues. The bars help viewers quickly grasp the magnitude of the revenues in relation to one another. There are two levels of comparison. At one level, the revenues are compared by Revenue Source. At another, they are compared by Revenue Type. All six bars reference the largest figure, which is currently at $6.3 billion. 

The challenge of the problem became more clear during a meeting between me and @kmhtran She will post her idea(s) as well. 

Now, onto the ideas. I came up with two ideas. I took into consideration the scrolling nature of the UI and that at any given time they will not see all six Revenue Types in a single glance, which makes the Type comparison functionality of the bars less effective. The exception to this is when the user zooms out on a desktop screen.  

Having said, my first idea is to move the bars and group them together above the charts with dollar figures. 

![IMG_0008](https://user-images.githubusercontent.com/85380376/133446707-fa26a33a-dc81-4311-a37f-ef85872ec7c5.png)

My second idea is to keep the bars where they are but only make them compare the values by Source. 

![IMG_0009](https://user-images.githubusercontent.com/85380376/133446747-22c1b5b2-e388-4c6c-8fb8-d0c0349475f6.png)

**Comment by mcharg** [comment]
@jkwonatx The first option is effective at making it clear that there are negative numbers and also makes it easier to compare the amounts across revenue types.  The second option takes away the ability to easily compare across revenue types, which is a fairly common user task.

**Comment by mcharg** [comment]
@jkwonatx Another way to get a similar effect to the first one would be to collapse the numbers under a "show details" link like we do on the Revenue by Company graphic.
![image](https://user-images.githubusercontent.com/38465926/133452052-dd157e8b-f5f7-418f-ac05-c5b61b1bea39.png)

**Comment by kmhtran** [comment]
@mcharg I came up with several designs to solve this issue and have two to share that may be effective.

For the first, I thought along a similar thought process as Jae and used the idea of making the bars similar to that of a number line. This seemed the most straightforward to me, but I realized that it may be confusing considering the fact that the bars might be difficult to compare due to all the values and information sandwiching each bar. Additionally, if multiple rows can't be seen at once, it might be confusing to the user that the bars do not all start at the same place.
However, this suggestion mentioned earlier is a good idea that I believe fixes the flaws I was thinking about in my diagram:
> Another way to get a similar effect to the first one would be to collapse the numbers under a "show details" link like we do on the Revenue by Company graphic.

![Version 1](https://user-images.githubusercontent.com/89661018/133476224-bb36c9a6-96a0-473e-aa07-9fb0298dd49e.jpg)

After our meeting, I really liked Jae's idea about merging all the bars together. Since the bars are scaled according to the large values in Royalties, I felt stacking the bars together this might aid in the scaling of the bars since it would create more space for the smaller bars to expand. To add, I thought about creating a master chart of values below the bar chart as well:
![Version 2](https://user-images.githubusercontent.com/89661018/133476200-2516d87a-e619-4ea8-bdc9-5f87938a1c57.jpg)

**Comment by mcharg** [comment]
@kmhtran I like the option with the table below.  The one thing we lose with that is the definitions of the revenue types, but we could put those in glossaries.

@jlouis-onrr Do you have feedback on any of the options?

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR @lpgoldstein Do any of you have feedback?

**Comment by cthomasONRR** [comment]
@mcharg I like Jae's first option (and similarly, Kaitlyn's second option) the best. I agree that having a collapsing the 'show details' link will make the data more table-like and less scrolling will be needed.

**Comment by mcharg** [comment]
We'll review and pick a direction in the intern meeting next Tuesday.

**Comment by jkwonatx** [comment]
A quick recap: we got a vote on my first idea and @kmhtran's second idea. @kjgdata  suggested we try using the stacked waterfall chart. @kmhtran and I will play with the design. @cthomasONRR  did raise the issue of accessibility when it comes to more sophisticated charts. We'll take that into consideration. We'll play with Excel and the chart simulation site @mcharg. @Baymatt, thanks for the link to the data. Thank you everyone for chiming in!

**Comment by Maroyafaied** [comment]
This is a visual from our archived site, wonder if something like this would work with revenue types on the left and the different sources listed as columns instead of the phases.. just a thought. 
![image](https://user-images.githubusercontent.com/40175688/134256292-554bbfcd-d117-4d98-9b05-e44aa270e60e.png)

**Comment by mcharg** [comment]
Users had a really difficult time understanding that chart. They didn't get why so many were practically empty and they never understood that they all added up to the total on the bottom.  They have a much easier time understanding the current diagram.

**Comment by Maroyafaied** [comment]
@mcharg Good to know.. let's stay away from it then!

**Comment by kmhtran** [comment]
The design from today's intern meeting: https://t6cz16.axshare.com/#id=wjilqz&p=accordion_bars_original&c=1
@jkwonatx and I will take time to explore the feedback we got regarding adding a zero axis, an additional bar for total revenues, and scaling among total revenues.

**Comment by jkwonatx** [comment]
@kmhtran I've made following edits to your sketch above: added negative bars; the size of all bars now reference the net total; added a hover effect to each bar to show corresponding dollar amount. Here's the link: https://dm7gya.axshare.com

**Comment by mcharg** [comment]
@jkwonatx Looking at your design, it wasn't clear to me that the shading on the left was indicating the negative axis.  That might need more labeling.

**Comment by mcharg** [comment]
Can we use a show details link like we have on the revenue by company chart, so we're consistent?
![image](https://user-images.githubusercontent.com/38465926/135461481-df322add-514f-4120-9f19-9eba026799c8.png)

**Comment by Maroyafaied** [comment]
@jkwonatx @mcharg I like the grey showing the total, I agree with Shannon about the design not being clear about where the negative area is or where the zero starts. I liked the previous design with the red line showing the zero line.

**Comment by Maroyafaied** [comment]
@kmhtran This is looking great, thank you for your work. The only feedback I have is if we can make the red line longer or skinner so it doesn't look like it's one of the revenue sources and more clear that it's a "Zero axis".

**Comment by kmhtran** [comment]
@Maroyafaied @mcharg https://t6cz16.axshare.com/#id=sjl6kn
I played with making the line skinnier but it was getting close to disappearing completely amongst the other bars so I made the red line longer to stick out both over and under the bar and added a 0 above the first bar's axis.

**Comment by mcharg** [comment]
Created #1782 to build.
