### ISSUE TITLE
Update company revenue download page

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#1719]
@jlouis-onrr @mojobnichols I added the link to the company revenue download page to an email and the snap shot that is inserted with the link shows that we only have data through 2018. The download page itself shows 2019. Probably two separate issues but is the download page text still updated manually? I can fix that if it is. 
![image](https://user-images.githubusercontent.com/39419003/132540108-ac496d8a-eda4-4552-825a-7770ec693715.png)
![image](https://user-images.githubusercontent.com/39419003/132540209-dfa70ef0-05d6-481f-a7ae-effcd6c0447d.png)

**Comment by jlouis-onrr** [comment]
@lpgoldstein, for the first item that is coming from the markdown frontmatter and for the latter item its coming from the markdown content.  I was hoping that the ALL_YEARS constant might be available at the markdown level (which would allow for setting the years dynamically in the content), but its not so the easy thing to do is was to update the markdown file.  

https://nrrd-preview.app.cloud.gov/sites/1719-RevenueDownloads/downloads/federal-revenue-by-company/
