### ISSUE TITLE
Change "oil or gas" to "oil & gas" in monthly disbursement download page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1723]
The terminology decided on was "Oil & Gas (pre-production)".

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/5ba19b24-58e6-483a-89db-9f04ca8f28cf)

**Comment by cthomasONRR** [comment]
@Maroyafaied I can take this issue and work on it when I get back on Tuesday (9/14).
