### ISSUE TITLE
Video library logo contest entry - Due Sep 21

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1724]
Office of Natural Resources “Video Library” Logo Contest

 

Contest Objective:   
To create a Video Library Logo that will be present on the ONRResource Homepage.

 

Timeline:   
Logos due September 21, 2021  

 
Lead by:   
Business Development Services

 

Who is eligible to participate? 

Contest is open to all ONRR employees. You do not have to be an artist to submit a design.

 
Contest Rules: 

·     No more than two entries per employee. 

·     Submit a jpg, png, or eps file to onrrinternalcommunications@onrr.gov. Must be received by 3 p.m. MST on September 21, 2021. Anything received after this deadline will not be eligible for consideration.

·     The ONRR Comms team will help finalize the winning design into a suitable graphic that is 508-compliant.

Judging: 

·     Business Development Services will review all entries.    

·     By October 1, 2021, all entries will be published to ONRResource, and shortly thereafter, a survey will go out to all ONRR employees to vote on the logo. The voting period will be two weeks.   

·     The top three employee selections will then go to ONRR Senior Management for final vote.   

 

*ONRR Senior Management reserves the right to re-consider entries for final selection. Final selection may be submitted to a graphic artist to ensure professional finish.   

The winner will be notified by e-mail and acknowledged through the ONRResource Home Page. The winning logo will be used on all ONRR Video Library materials, including but not limited to presentations, websites, etc.

**Comment by daniel-coleman-1** [comment]
Deadline has passed, good luck everyone!
