### ISSUE TITLE
Update PowerPoint template to include the new team name

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1737]
Includes revisiting the NRRD logo.

**Comment by mcharg** [comment]
PPT template: https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/ODDD%20Branding/ODDD_Template.potx

PPT theme:
https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/ODDD%20Branding/ODDD.thmx

@Maroyafaied @cthomasONRR @lpgoldstein Do you want to review?

**Comment by Maroyafaied** [comment]
@mcharg I'm not seeing a difference between the two links? What's the difference between the template and the theme?

**Comment by mcharg** [comment]
@Maroyafaied I think the theme makes the styles available to apply to any presentation.

**Comment by cthomasONRR** [comment]
It looks good to me! Thanks for all your work on this!

**Comment by Maroyafaied** [comment]
@mcharg Ok, thanks. It looks good for me as well.

**Comment by lpgoldstein** [comment]
@mcharg Thanks! I love it!
