### ISSUE TITLE
Look into getting National Park passes for interns

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1740]
Info about the program.
Patricia Seiser from NPS mentioned in a Virtual Student Federal Service meeting that they are able to provide their unpaid interns with the pass. ONRR isn't on the list for the pass, but it mentions any work done on lands managed by the agencies listed and our websites present revenue data for lands managed by BLM. 
https://store.usgs.gov/faq#Volunteer-Pass

These are the people at BLM we can try contacting to see if our interns might qualify, since our websites present data about lands managed by BLM.
https://www.blm.gov/get-involved/volunteers/state-volunteer-contacts

**Comment by mcharg** [comment]
@lpgoldstein Is this something you might want to see if you can track down?  I already tried asking the Web Council folks and got crickets.  Patricia said we might try emailing the people on the BLM volunteer contacts page.

**Comment by jkwonatx** [comment]
@mcharg @lpgoldstein 
I appreciate you both looking into this!

**Comment by lpgoldstein** [comment]
@mcharg I'll look into it

**Comment by mcharg** [comment]
@lpgoldstein Thank you!
