### ISSUE TITLE
VSFS website feedback

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1753]
So I don't forget to do it.

**Comment by mcharg** [comment]
Document with feedback: https://teams.microsoft.com/l/file/96D9B660-3EEC-4AB0-B072-49733BC1FFFD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FAdmin%2FMentoring%2FVSFS_website_feedback.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by jkwonatx** [comment]
Added feedback on student view below Shannon's.
