### ISSUE TITLE
September analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1754]

**Comment by daniel-coleman-1** [comment]
September analytics are up and QC'd.  I think they are good to go, but I'm seeing a lot of variance in the Downloads sections.

**Comment by daniel-coleman-1** [comment]
For ONRR.gov users, I'm seeing a (not set) table - I ignored it and posted the one below it.  Should we revisit?
![Screenshot 2021-10-04 130741](https://user-images.githubusercontent.com/83892362/135921650-1ef9a016-30e2-4f8c-9eaf-4b47b5d04849.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm getting a 404 error when I click on the NRRD monthly dashboard report for September. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c70ce890-2a5c-4fd1-a322-b3c35b8cab85)

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm seeing 42 site searches, but you have 37. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1abf8bed-9e1c-4c3c-9304-3695c59c04cc)

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm seeing different percentages than you have.![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3bb01ec9-f69d-4457-aeff-192cad705f7e)

**Comment by mcharg** [comment]
Safari (in-app) mobile is above 1% and should be added to browsers.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/89eedd96-ade9-40c2-bfb0-9f76a5de9034)

**Comment by mcharg** [comment]
@daniel-coleman-1 Disbursements downloads, I'm seeing one each for Excel and CSV.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b2705a64-00f7-4aac-8dd4-e6511d1900e3)

**Comment by daniel-coleman-1** [comment]
@mcharg I think we're good to go here

**Comment by mcharg** [comment]
Looks like everything is fixed.
