### ISSUE TITLE
Metrics statement for upper management

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1768]
Nichelle would like us to write a similar statement to this for FY21 by Wednesday, the statement can include stats for onrr.gov as well. 

"The site now includes 17 years of annual production, revenue, and state and county disbursement data, as well as expanded monthly datasets. The number of monthly users during FY20 increased by 8 percent over FY19, confirming the growing importance of this data portal to congressional, industry, civil society, and other users."

**Comment by lpgoldstein** [comment]
@Maroyafaied if we compare NRRD to FY 2018 we are up by 95% for users

**Comment by Maroyafaied** [comment]
@lpgoldstein That's crazy! What is it if we compare it to FY 20.

**Comment by mcharg** [comment]
@Maroyafaied Should we also update that PPT we started?

**Comment by Maroyafaied** [comment]
Submitted to Nichelle.
