### ISSUE TITLE
Preform Content Audit & Identify issues 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1776]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you post the right link to the content audit so I can review? The one above is not the same as you showed yesterday. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the edited link says I don't have access, can you put this is our shared drive and post the link. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied here's the link:
https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EfAoWgc43uRAn0jNWMk0x8gBtJ9ier2tZh7lxeAFKOS8NQ?e=wEOPmA

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 The audit is missing a few pages on the website, explore data hasn't been done and it looks like previous audits went through all the States and offshore regions. The glossary, fact sheet, and a few download pages were also missing from the audit. Also, some of the notes and descriptions are from the last audit and no longer relevant. 

https://revenuedata.doi.gov/explore?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2020
https://revenuedata.doi.gov/glossary
https://revenuedata.doi.gov/fact-sheet
https://revenuedata.doi.gov/downloads#Data-Collection-and-Validation
https://revenuedata.doi.gov/downloads/production-by-month/
https://revenuedata.doi.gov/downloads/production/
https://revenuedata.doi.gov/downloads/disbursements-by-month/

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this is ready for your review

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Can you delete the tabs for explore, archive and docs since they are not relevant to this year's audit.  For the glossary page, there are terms there that need to be removed since they are no longer relevant to the current website, so can you note that in the audit and create an issue. For the explore page, did you audit the production, revenue, and disbursement data types like I showed you this morning? Just looking at the explore data revenue, this statement comes back as grade level 13 which is not noted in the audit. 
![image](https://user-images.githubusercontent.com/40175688/140825850-a29cebd4-15b9-4f72-87d5-9d405ea8b6d2.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I removed Archive but kept Explore because it reflects commodities extracted in FY 2020.  I'll remove docs but it makes sense to me to keep the sheet for the explore cards.

That page comes back at 7 for overall reading level, it has a few sentences that come back as hard to read (like the example you provided) but overall the page comes back at below the target reading level. Generally I'm going page by page and not focusing on specific sections or sentences unless the overall page reading level comes back as above the target level.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the explore tab is from a previous audit and the description is for commodities in CY 2018. Also the archive tab is still there and hasn't been removed.  Also, explore data page doesn't have much content except the nationwide summary statement so wondering how that page came back as reading level 7 since it's full of charts? This is the content audit I'm looking at that still have the archive tab and explore tab. https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EfAoWgc43uRAn0jNWMk0x8gBtJ9ier2tZh7lxeAFKOS8NQ?e=wEOPmA

**Comment by daniel-coleman-1** [comment]
@Maroyafaied here's the correct link:
https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BDB134184-4C07-48DD-AACE-FA19CA3C1A84%7D&file=content_audit_FY22.xlsx&action=default&mobileredirect=true

**Comment by daniel-coleman-1** [comment]
@Maroyafaied the other text on the Explore Data page is mainly either nouns or simple descriptive sentences, pretty simple. I don't think the software engages with the charts at all.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 For the explore tab, can you delete the columns that aren't relevant to this audit (columns F-Q).  I don't see this page in the audit that I mentioned in the above comments. https://revenuedata.doi.gov/downloads#Data-Collection-and-Validation

**Comment by daniel-coleman-1** [comment]
@Maroyafaied deleted irrelevant columns; I left out the Data Collection page because that text lives in the Downloads page:
https://revenuedata.doi.gov/downloads
