### ISSUE TITLE
Look into Touchpoints survey tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1783]
https://touchpoints.digital.gov/

Survey tool managed by GSA that might allow us to collect feedback on our sites without triggering PRA review as long as we don't collect PII.

**Comment by cthomasONRR** [comment]
Here is some useful information I found while researching Touchpoints:

- PRA-friendly: Touchpoints provides a common feedback survey template that leverages an existing PRA clearance.
- BUT- I cannot find on their website which PRA they are referencing. It would be good to have that information so we can reference the exact PRA when sending it out.
- You have to make an account with Login.gov to access, but it's easy to do with your PIV card.
- I made an account and tried to access Touchpoints...
- onrr.gov has yet to be configured for Touchpoints. If we want to play around and learn it, we need to contact the Feedback Analytics Team for assistance:
![image](https://user-images.githubusercontent.com/72526208/142882571-45320b97-a9fe-4e49-8968-4473c15f9929.png)
- I tried contacting Touchpoints for help:
![image](https://user-images.githubusercontent.com/72526208/142883355-399b51a4-3044-4c42-a3b7-7b5c30a89560.png)
- I will update if/when I hear back. I cannot access or do anything with Touchpoints except read their main webpage without onrr.gov being set up in their system.

**Comment by cthomasONRR** [comment]
After reading closely to the wiki page, they are a bit sneaky in saying 'PRA-friendly'... this does not mean a PRA is not needed. It just means that our questionnaires will be under GSA's existing PRA (https://www.federalregister.gov/documents/2019/07/03/2019-14217/information-collection-improving-customer-experience-implementation-of-section-280-of-omb-circular). We will still have to submit PRA-like data/paperwork through Touchpoints:

> A-11 Reporting from Touchpoints
Once a Touchpoint Form is live and accepting Submissions, the Submissions are stored in a database table. This is very standard.

> Submissions can be viewed at any time in Touchpoints, and the data can be exported to .CSV for review and analysis.

> At the end of the quarterly reporting period, the Touchpoints Team will be in touch immediately after (and within the 2 week reporting window).

> In Touchpoints, there are 2 buttons that allow for the exporting of the 2 files required for A-11 reporting:

>1.  Service Metadata Report (details about the Service)

>
Service Submission Details Report (a quantitative summary of the 7 questions>
 Contingent upon an Agency's review, the Touchpoints Team can submit those files to OMB Max, or the Agency can elect to do it on their own.

We should have a discussion if we want to go through with Touchpoints. I'm afraid that we will have to incorporate the Regs Team in this decision. It might be too much hassle. I'll schedule a meeting for after Thanksgiving to discuss.

**Comment by ryanwoldatwork** [comment]
hi @cthomasONRR, ONRR has been setup in Touchpoints. You will now be able to login successfully.

https://touchpoints.digital.gov/

**Comment by cthomasONRR** [comment]
@ryanwoldatwork Thanks! We have a meeting scheduled for after Thanksgiving to discuss if Touchpoints is the right fir for our group. I'll link up with you after that with some additional questions. Thanks for your swift response!

**Comment by cthomasONRR** [comment]
@ryanwoldatwork After discussing with the group, we are going to hold off utilizing Touchpoints for now. I will get back in touch with you if we decide to go this route in the future. Thanks!
