### ISSUE TITLE
Update homepage graphic XD file

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1786]
With the new copy.

**Comment by mcharg** [comment]
@codyeckstein Are you good with Maroya's update?

**Comment by Maroyafaied** [comment]
I spoke to @codyeckstein about this during our check in , the edits above comes back as grade 11 in hemingway but it works for now so closing this issue.

**Comment by mcharg** [comment]
I updated the XD file and put screenshots and copy/pasteable copy in #1428 for implementation.
