### ISSUE TITLE
Convert to using sprints

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1787]
ZenHub will be removing Milestones by the end of the year.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/92b335ee-043e-4cc1-81d0-38bf9dd911f7)

**Comment by Maroyafaied** [comment]
They do an extension to give us Zenhub features within Github but then take milestones away.. how annoying lol but it shouldn't be a big deal since the Sprints feature now shows up on GitHub.
