### ISSUE TITLE
Explore data: Build national revenue summary

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#179]
Design: 
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f8dfd08a-c2c9-4755-ba49-9866a27e43ab)

Prototype: https://935313.axshare.com/#g=1&p=national_revenue_summary

Page context: https://935313.axshare.com/#g=1&p=revenue_default

**Comment by mcharg** [comment]
Updated design with the breakouts for onshore/offshore and other revenue above.

@lpgoldstein Can you come up with descriptions for inspection fees and civil penalties?

**Comment by lpgoldstein** [comment]
@mcharg This is what we have on the download pages for the definitions.

 **Inspection Fees** The Department of the Interior inspects offshore oil and gas drilling rigs at least once a year. Inspection fees help recover some of the costs associated with these inspections.
**Civil Penalties** ONRR issues civil penalties when companies fail to comply with, or knowingly or willfully violate, regulations or laws
