### ISSUE TITLE
October Analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1797]

**Comment by daniel-coleman-1** [comment]
@mcharg these are the most downloaded items from NRRD from October 01-31.  I'm thinking we list the top 5, what are your thoughts?

![Screenshot 2021-11-08 104411](https://user-images.githubusercontent.com/83892362/140791814-62fa3afe-6304-410d-a9d8-945ba7e71599.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 I think that would be a waste of time because the bulk of downloads are happening from the query tool.  What we agreed on when we met was a count of the total downloads from the download page and a count of the total downloads from the query tool.

**Comment by daniel-coleman-1** [comment]
@mcharg this is ready for review

wiki update:
![Screenshot 2021-11-17 114242](https://user-images.githubusercontent.com/83892362/142262542-f9072ac4-b103-4bd8-b045-9923de6b4faf.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Safari mobile should be 12.73%.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8b44807f-6240-4f4a-966a-192c2ea086ef)

**Comment by mcharg** [comment]
Otherwise, looks good.

**Comment by daniel-coleman-1** [comment]
Resolved issues, thanks for taking a look @mcharg
