### ISSUE TITLE
Update Glossary page

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1800]
Convert glossary items to title case and correct sentence/fragment punctuation agreement

https://nrrd-preview.app.cloud.gov/sites/production-cy/glossary/

**Comment by Maroyafaied** [comment]
Add tags to anything changed. Also, audit terms that are no longer on the website.

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EcTng99NUkpFmjzlaThQfcwB_tconReiLPWDBJFd1Ofa4w?e=E2nlW2

@cthomasONRR could you review?  There are some terms I have identified for removal, and some that are only found on the glossary page and nowhere else that I don't believe should be removed from the site.  For terms that should not be removed, I think we should look to intentionally create content that contains those terms.  I estimate that it would require adding 8-10 pages of content to the site.  What do you think?

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 
I did a first pass, but let me look at it again with fresh eyes on Monday.

**Comment by daniel-coleman-1** [comment]
Thanks @cthomasONRR!  Those notes are very helpful.

**Comment by daniel-coleman-1** [comment]
Where do we host definitions?  I'm looking at the glossary mdx file and only see the glossary terms, without definitions:

![Screenshot 2021-12-03 135914](https://user-images.githubusercontent.com/83892362/144676997-54f56d0a-2a03-4e50-9907-142551dc6202.png)

I'll bring this up at sync up

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the glossary terms are under scrc>components>glossary.mdx Please let me know which terms you recommend removing before doing so. Thanks

![image](https://user-images.githubusercontent.com/40175688/144858488-95fe515c-c221-40de-a9cb-f382e3297c99.png)

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 OK I reviewed with fresh eyes and added an explanation for all terms in question for removal. Let me know if you have any questions!

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @cthomasONRR I reviewed and added my comments, I disagreed with several terms being removed since they are currently mentioned on the website.  There are no terms in the glossary that need us to create content or pages on the website, the are all relevant to the current content.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR @Maroyafaied Based on your feedback I recommend we remove the following terms:

- Civil Society
- Gross Domestic Product (GDP)
- kWh

We need to come to consensus on the following term:
- Variance floor

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein can you please give your input if we should keep or remove the term "Variance Floor". Thanks

**Comment by mcharg** [comment]
Where do we have it on the site?

**Comment by mcharg** [comment]
It's not coming up in search results.

**Comment by Maroyafaied** [comment]
@mcharg it's not anywhere on the website and I didn't think it was relevant so my recommendation is to remove it.

**Comment by mcharg** [comment]
If it's not on the website, we don't need it.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you can go ahead and remove variance floor. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied @cthomasONRR @mcharg the following terms will be removed in the PR:

- Civil Society
- Gross Domestic Product (GDP)
- kWh
- Variance floor

**Comment by daniel-coleman-1** [comment]
@cthomasONRR the current definition for Geothermal - Sulfur is as follows:
"Geothermal byproducts that is commercially recovered from produced geothermal fluids"
I'd like to change the "is" to "are," is that correct? So it would be:
"Geothermal byproducts that are commercially recovered from produced geothermal fluids"

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 Yes, I'm good with that change. Looks like a grammar error.
