### ISSUE TITLE
Reduce Reading Level: how-revenue-works/ownership/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1801]
Currently coming in at grade level 12, Split Ownership paragraph comes in at 11 and Natural Resource Ownership comes in at 15.

https://revenuedata.doi.gov/how-revenue-works/ownership/

**Comment by mcharg** [comment]
@lpgoldstein Did Jennifer do this one last year?

**Comment by lpgoldstein** [comment]
@mcharg Yes I think so - especially after reading it.
