### ISSUE TITLE
Reduce Reading Level: /how-revenue-works/minerals/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1802]
Overall the page comes to 12.

Nonenergy Minerals section comes back as 16.  Plan - 16.  Claim - 13. Explore - 12.  Develop - 14.  Decommission and Reclaim - 11.

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={8afb839b-090c-4f90-afef-0df8a528cf76}&action=edit

**Comment by Maroyafaied** [comment]
@lpgoldstein please review

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 I think these are good to go with the few comments and edits I made. Nice work! You can add me to review the PR as well.
