### ISSUE TITLE
Reduce Reading Level: how-revenue-works/hpf/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1803]
Historic Preservation Fund - 9.  Funding Priorities - 12.  Authorization and funding - 12.  Distribution of funds - 13.

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B0CE15431-E61A-49B2-9A7E-DFA4695B9959%7D&file=HPF.docx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@lpgoldstein please review

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 I think these are good to go with the few comments and edits I made. Nice work! You can add me to review the PR as well.
