### ISSUE TITLE
Reduce Reading Level: /how-revenue-works/offshore-oil-gas/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1805]
https://revenuedata.doi.gov/how-revenue-works/offshore-oil-gas/

Offshore Oil & Gas - 15. Plan - 12.  Lease - 13.  Explore - 14.   Develop - 14.  Decommission and reclaim - 14.

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/Ee3RloCHWkNLuC5v1owkYakBjPr08R_lxPtQcCHYFQ2Bxg?e=8MlaZl

These edits bring:
Offshore Oil and Gas to 8 from 15
Plan to 11 from 12
Lease to 9 from 13
Explore to 11 from 14
Develop to 12 from 14
Decommission and reclaim to 11 from 14.

**Comment by daniel-coleman-1** [comment]
@lpgoldstein could you review?

**Comment by daniel-coleman-1** [comment]
@lpgoldstein this is ready for your review:

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B8096D1ED-5A87-4B43-B82E-6FD68C2461A9%7D&file=Offshore%20Oil%20%26%20Gas.docx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@cthomasONRR can you please review this since @lpgoldstein is out.

**Comment by lpgoldstein** [comment]
@cthomasONRR if you haven't started on this yet - I'm back and can do it.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I just finished reviewing- looks good to me! I attempted to try and lower the Grade 11 sections, but no luck.
