### ISSUE TITLE
Reduce Reading Level for /how-revenue-works/federal-reforms/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1806]
https://revenuedata.doi.gov/how-revenue-works/federal-reforms/

Fed Reforms to DH - 11.  Deepwater Horizon - 13.   Dodd Frank - 11.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 fix misspelling ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/53a38997-7e02-4265-b51a-533b038d13df)

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={5a278407-eb5f-4d2d-b496-a088dd5a3312}&action=edit
@lpgoldstein could you review?

**Comment by lpgoldstein** [comment]
Looks good!
