### ISSUE TITLE
Reduce Reading Level for /how-revenue-works/native-american-ownership-governance/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1807]
As this is one of our most viewed pages, this should be a higher priority.

https://revenuedata.doi.gov/how-revenue-works/native-american-ownership-governance/

beginning to laws and regulations - 11.  History of federal obligations - 13.  General allotment act - 13.   Indian reorganization act of 1934 & Indian Mineral Leasing Act of 1938 - 9.  Indian Mineral Development Act of 1982 - 12.  Indian Tribal Energy Development and Self-Determination Act of 2005 - 13.  Indian Tribal Energy Development and Self-Determination Act Amendments of 2017 - 11.  Title 1 and 2 Amendments - 14.

**Comment by Maroyafaied** [comment]
This was worked on last year.
