### ISSUE TITLE
Reduce Reading Level for /how-revenue-works/onshore-oil-gas/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1811]
Onshore Oil & Gas - 13.  Plan - 13.  Lease - 11.  Explore - 14.  Develop - 13.  Decommission and reclaim - 15.

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={81e91666-0f14-41aa-978b-40c591d2fef4}&action=edit

@lpgoldstein could you review?

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Looks good - just one edit
