### ISSUE TITLE
Reduce Reading Level for /how-revenue-works/audits-and-assurances/

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1812]
Audits and Assurances - 13.  Tracking and Verifying Payments - 16.  Company Standards and Oversight - Post-graduate.  Federal standards and audits - 14.  Federal revenue reporting - 12.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I don't believe this was worked on last year. @mcharg the page that was removed was the Native American Economic Impact Page. https://github.com/ONRR/nrrd/pull/1378

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={f45f634e-99e9-4f50-942f-720e9c4d0733}&action=edit
@lpgoldstein could you review?

**Comment by lpgoldstein** [comment]
Looks good.
