### ISSUE TITLE
Add content to WYMHM Nov edition - due Nov 15th

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1814]
https://doimspp.sharepoint.com/:w:/s/ONRRWebContentTeam/EaOnraOKV2JJoedjDvm49J8B28MLxhIsAJRH-qXUKdUuRA?email=Maroya.Faied%40onrr.gov&e=4%3ADOdS97&CID=7057d788-f92a-dc4e-d11c-253af8ffb188

**Comment by daniel-coleman-1** [comment]
requested access

**Comment by daniel-coleman-1** [comment]
Added [Christa's blog post](https://blog-nrrd.doi.gov/agile-methodology/)

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/181680cd-0b81-439c-9549-6a2e68f9abcb)

**Comment by Maroyafaied** [comment]
Since this is due next Monday, I went ahead and made the updates. @mcharg can you review? Here is what I added incase you don't have access to the document. 

**Open Data, Design, & Development (ODDD):** 

- The ODDD team interviewed 30 ONRR employees to better understand challenges and resources needed around section 508 Compliance to help employees support this law.  

- The section 508 Compliance project on onrr.gov is at 96% completion with 120 documents remaining to be correct or removed.  

- New blog post written by our cross trainer, Christa McCurdy:  [ I came for the data and stayed for the agility: reflections on my rotation with the Open Data, Design, & Development team ](https://blog-nrrd.doi.gov/agile-methodology/)

**Comment by mcharg** [comment]
@Maroyafaied I just changed "correct" to "corrected" in the second bullet.

**Comment by mcharg** [comment]
@Maroyafaied I made my edits to your comment, since I don't have access to the document.

**Comment by Maroyafaied** [comment]
@mcharg thanks
