### ISSUE TITLE
Answer FOIA's questions 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1817]
I’m hoping you or someone on your staff can help with answers to some questions for “Chief Officer Report” to DOJ; the questions are regarding proactive disclosures of non-public information.  I think that the Revenue Data site is a way that ONRR proactively discloses typically non-public information.  Note:  I also asked Shannon a question regarding website earlier – I will forward that message.

We are happy to work with you or your team to answer these as quickly as possible, we have a hard due date next week.  Please see the questions below: 

 

Please describe what steps your bureau/office takes to identify, track, and post (a)(2) proactive disclosures.

Does your bureau/office disseminate common types of material outside of FOIA, including in online databases where the public may access them? If yes, please provide examples and, if applicable, statutory authority.

Beyond posting new material, is your bureau/office taking steps to make the posted information more useful to the public, especially to the community of individuals who regularly access your bureau/office’s website?
I
f yes, please provide examples of such improvements. In particular, please describe steps your bureau/office is taking to post information in open, machine-readable, and machine-actionable formats, to the extent feasible. If not posting in open formats, please explain why and note any challenges.

Optional --Please describe:
Best practices used to improve proactive disclosures
Any challenges your bureau/office faces in this area.

**Comment by Maroyafaied** [comment]
Send link to Tracey Fey to review. http://2017onrr/

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein I have drafted answers to this FOIA request (except #4). Please review and make any necessary changes or additions. This can wait till next week. Thanks https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Admin/FOIA%20-%20proactive%20disclosures.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied Looks good.

**Comment by Maroyafaied** [comment]
@mcharg Thanks, I incorporated your comment. Will send to the FOIA team.

**Comment by lpgoldstein** [comment]
@Maroyafaied Looks great! I made a few proofreading type edits.
