### ISSUE TITLE
Add missing redirects from the old site

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1821]
This will fix links in blog posts.

Old link: https://revenuedata.doi.gov/explore/revenue/
Redirect to: https://revenuedata.doi.gov/query-data

Old link: https://revenuedata.doi.gov/downloads/federal-revenue-by-location/
Redirect to: https://revenuedata.doi.gov/downloads/revenue/

Old link: https://revenuedata.doi.gov/downloads/federal-production/
Redirect to: https://revenuedata.doi.gov/downloads/production/

**Comment by Maroyafaied** [comment]
@jlouis-onrr can you show @daniel-coleman-1 how to do redirects.  By doing so , it'll fix most of the blog posts with broken links. Thanks
