### ISSUE TITLE
Write a stronger justification for using Slack 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1827]
https://teams.microsoft.com/l/file/A582E56B-4B2D-49A4-8F7D-330A0CC67DAD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FAdmin%2FSlack%20Business%20Justification.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review/discussion. We can go over in our check in tomorrow?

**Comment by Maroyafaied** [comment]
@lpgoldstein I've reviewed and added a section specific to Microsoft teams and moved somethings around. Can you take a final look and make any necessary changes and I'll send it off later this afternoon.

**Comment by lpgoldstein** [comment]
@Maroyafaied That makes more sense now. I like the bullet list at the end. I just went through it one more time. If you accept the changes we should be good to go.

**Comment by Maroyafaied** [comment]
@lpgoldstein Thanks, I send it.
