### ISSUE TITLE
Recruit internal ONRR employees for onrr.gov user study.

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#183]
Send email to all the contacts on onrr.gov and recruit people from production, royalty, and compliance teams.

**Comment by lpgoldstein** [comment]
@mcharg  and @Maroyafaied  I added all of the ONRR.gov contacts from several sources and documented in the market map. Let's discuss before we send out emails. I think we should narrow down focus first. 

[ONRR.gov Internal Contacts](https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BC55B52B5-A7E3-40D3-983D-FD8D95FA993B%7D&file=Market%20Map.xlsx&action=default&mobileredirect=true&cid=32889eb3-479e-4f0c-a877-36e885cf4563)
