### ISSUE TITLE
Add historical revenue file to NRRD

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1831]
Find a place to put historical revenue data 1982-2002 on the NRRD. This would be just the file and not incorporated in the database.

**Comment by cthomasONRR** [comment]
We could add a new section in Downloads (https://revenuedata.doi.gov/downloads). Here's a mock-up:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/458d6a84-5788-4118-9331-2a0013a9ff0d)

**Comment by cthomasONRR** [comment]
@mojobnichols @Maroyafaied Here is a mock-up. I will need Mojo's help setting it up though.

Add a new paragraph here: https://revenuedata.doi.gov/downloads/
Under 'Federal Revenue by Company':
![image](https://user-images.githubusercontent.com/72526208/144304243-f82b8120-04ce-4616-ac7c-e0bbcec257d6.png)

**Historical Revenue**

This dataset offers revenue by calendar year from 1982 through 2002. The data includes federal offshore and onshore revenue, along with revenue from Native American lands. The data is further broken down by location, lease type, revenue type (i.e., bonuses, rents, and royalties) and production/commodity information.
[Download Link](url)

**Comment by Maroyafaied** [comment]
@cthomasONRR I think it would be better to add it under revenue before revenue by company. Also, this is only federal data without Native American data, I'd take out the word "production".

**Comment by cthomasONRR** [comment]
Here is my draft in Atom: 
![image](https://user-images.githubusercontent.com/72526208/144305750-ecd88e9b-8ea7-4fa2-a650-43c664a0fef1.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR you can just create the PR since you already did the work and one of us can help adding the actual file.

**Comment by cthomasONRR** [comment]
Next step is to set up a folder titled "historical-revenue" here:
\GitHub\nrrd\database\static\csv
