### ISSUE TITLE
Add content to WYMHM: December Edition

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1859]

**Comment by daniel-coleman-1** [comment]
https://blog-nrrd.doi.gov/breaking-down-silos-by-cross-training/

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this is the Dec doc to add content to https://doimspp.sharepoint.com/:w:/r/sites/ONRRWebContentTeam/_layouts/15/doc.aspx?sourcedoc=%7Bd271e26d-43a0-44a0-99a2-c7bb2d83ffe5%7D&action=edit&CID=6a960e27-f97b-3c03-f337-fecd5e5cb26b
