### ISSUE TITLE
Create data check template in PowerBI - Revenue Homepage

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#1862]
This is a new issue for making a template for the Revenue Homepage data check.
(https://revenuedata.doi.gov/?tab=tab-revenue)

We would like this template to reflect the Monthly Revenue Homepage data checklist:
https://github.com/ONRR/nrrd/wiki/Checklists-for-Reviewing-Data

**Comment by mcharg** [comment]
Done
