### ISSUE TITLE
Renewable snapshot 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1873]
Nathan would like us to set up a meeting within the next 1-2 weeks  to discuss ideas for Kimbra's request.

**Comment by Maroyafaied** [comment]
One idea is research if EIA has any renewable data/visuals we can pull into an automated snapshot.

**Comment by mcharg** [comment]
@Maroyafaied Did you get clarification about whether Geothermal counts as renewable?

**Comment by mcharg** [comment]
We could pull together a quick design studio and go over the problem next week in the intern meeting and solutions the following week.

**Comment by Maroyafaied** [comment]
@mcharg Yes, geothermal would be considered a renewable. A design studio is a good idea, I'll try to set up a meeting with Nathan on Monday to get a better idea of what their vision is.

**Comment by mcharg** [comment]
Closing, since we have the design studio one.
