### ISSUE TITLE
Renewable Snapshot Design Studio (2/2) 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1879]
Design studio presentation saved [here](https://doimspp.sharepoint.com/:p:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B595E7C7B-7180-4C29-940A-F55539764F1C%7D&file=Renewables%20Design%20Studio.pptx&action=edit&mobileredirect=true)

**Comment by cthomasONRR** [comment]
I uploaded my ideas to the PowerPoint.

**Comment by Maroyafaied** [comment]
@mcharg here's my sketch. [https://app.zenhub.com/files/215585796/72f9bec6-4059-48d7-807e-0eb20ee96427/download](https://app.zenhub.com/files/215585796/72f9bec6-4059-48d7-807e-0eb20ee96427/download)

**Comment by mcharg** [comment]
@Maroyafaied All I'm seeing in the folder is a pdf of the existing fact sheet.

**Comment by mcharg** [comment]
Added my sketch to the PPT.

**Comment by mcharg** [comment]
@Maroyafaied I was able to recover your sketch from an email that said you'd uploaded it to the issue.  I'll add it to the PPT.

**Comment by jkwonatx** [comment]
Added my sketch and the design note to the PPT

**Comment by daniel-coleman-1** [comment]
Added my sketch to the PPT
