### ISSUE TITLE
Make user type triangle and agile slides accessible

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1880]
They have contrast, alt text, and reading order issues.

**Comment by jkwonatx** [comment]
Here's my plan for remediation: 1. Reorder the elements slide by slide, covering all slides, focusing on the easy fixes 2. identify problems that require some thinking and tackle them one by one.

**Comment by jkwonatx** [comment]
I'll tackle number 1 of the plan above

**Comment by mcharg** [comment]
@jkwonatx I need these for the impact expo presentations. Do you want to work on them or should I do it?

**Comment by lpgoldstein** [comment]
@mcharg Looks good. Updated fonts and colors so everything matches as well.
