### ISSUE TITLE
Consistency with geothermal units in download production page 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1881]
@lpgoldstein I changed this issue to be just for the download production page, and will have @daniel-coleman-1 fix the geothermal units and spellings in issue # 1883

In the yearly production download page , we missed listing Geothermal-direct use (millions of gallons) and we also need to change  "utilization" to "use" and write out the the units like we have them in the glossary.  For example,  the first one listed is "Geothermal- Direct Utilization, (gal hundreds) , this should be changed to " Geothermal - Direct Use, (hundreds of gallons). 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f6e00529-360c-4843-bfe0-a9eeb21f404d)

**Comment by mcharg** [comment]
@daniel-coleman-1 There are also a couple typos for sulfur on the glossary page.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d5dde334-a93d-4118-9b00-30e4ed11f5c5)

**Comment by mcharg** [comment]
More typos.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/acbe2fc2-91b0-41c5-9ab2-1549820df207)

**Comment by mcharg** [comment]
And more.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/45ff26f7-533b-4a09-a7b4-efdb1a24dae3)

**Comment by Maroyafaied** [comment]
@lpgoldstein please fix the geothermal units in the download production page and @daniel-coleman-1 please fix the geothermal and other glossary issues in the glossary page that I assigned for next sprint (issue #1883)

**Comment by lpgoldstein** [comment]
@Maroyafaied This is what it looks like now. I kept the units uncapitalized because that's how we have it for all downloads pages. 
![image](https://user-images.githubusercontent.com/39419003/146454984-df711d12-b9e8-4519-a5c7-b66d91adca76.png)
