### ISSUE TITLE
Fix Misspellings in Glossary & change Geothermal term "Utilization" to "Use"

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1883]
![image](https://user-images.githubusercontent.com/40175688/146283662-964d68c9-18a5-4851-8208-921ef9f8266f.png)
![image](https://user-images.githubusercontent.com/40175688/146283781-6fd1a5ba-92b1-4e63-a299-a2d5b6db0e96.png)
![image](https://user-images.githubusercontent.com/40175688/146283925-a75a1d6b-64b0-46ba-acee-690c312bd849.png)
![image](https://user-images.githubusercontent.com/40175688/146283990-5406bd07-789f-4c3c-b4ff-21a29712829c.png)
 
In the glossary, for some some terms we say "Direct Utilization' and for others we say "Direct Use" (in red) , please change al terms to say direct use and fix spellings ( in yellow). 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/c752b989-916d-41db-8920-e6619623c3da)

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5ff5a93f-d130-4737-bf90-f233083de462)
