### ISSUE TITLE
Axure training: The Basics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1895]

**Comment by cthomasONRR** [comment]
Working on the step-by-step training Axure has on its website: https://docs.axure.com/axure-rp/tutorials/

**Comment by cthomasONRR** [comment]
- [ ] Interactive Button
- [ ] Hiding and Showing Widgets
- [ ] Pass Text to Next Page
- [ ] Anchor Link
- [ ] Embedding Media
- [ ] Full Width Image or Banner
- [ ] Scrolling Region
- [ ] Rotating Carousel / Slideshow
- [ ] Navigation Menu
- [ ] Tooltips
- [ ] Tab Menu
- [ ] Accordion Menu
- [ ] Drag and Drop
