### ISSUE TITLE
Review OGOR B data from DORC

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1898]
See email from Donna.

**Comment by lpgoldstein** [comment]
[Raw data](https://teams.microsoft.com/l/file/E761407E-F62C-4388-BEE4-DE0D0062463E?tenantId=0693b5ba-4b18-4d7b-9341f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FOGOR%20B%2FProduction_Test_FileCY10_20%20as%20of%2012_20_21.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by Maroyafaied** [comment]
- Review if any disposition codes should be removed
- Review if database can show volumes as zero to match raw data
- Follow up with DORC regarding meeting with Nathan about zero values and rounding to two decimal places
- Follow up with DORC regarding meeting with BLM about proprietary federal solids data

**Comment by Maroyafaied** [comment]
Review material for our meeting tomorrow

[OGOR B Prototype ](https://dwb2kg.axshare.com/#id=kgdh1w&p=usertesting)

[OGOR B Disposition Categories ](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BABCBCB23-4E64-48A6-9029-AA3F864277FD%7D&file=OGOR.B.Disposition.Categories.Glossary-2.xlsx&action=default&mobileredirect=true)

**Comment by Maroyafaied** [comment]
I met with the DORC team today, the discussion was mainly around rounding to decimal places but I let them know that we would like for them to provide us a column with the actual disposition code along with the description.  I also emailed Nadia about calculation total production  for oil and gas from disposition codes.

**Comment by cthomasONRR** [comment]
Donna emailed us a new excel with Disposition Code numbers and descriptions.

I did a comparison using CY 2020 data. There are 5 commodities that did not match and will need a list of specific disposition codes that contribute to the production number. 

- Coal: The OGOR data was **less** than the NRRD Production Downloaded data.
- Gas 
- Geothermal - Electrical Generation, Kilowatt Hours: The OGOR data was **less** than the NRRD Production Downloaded data.
- Oil: The OGOR data was **less** than the NRRD Production Downloaded data.
- Sand/Gravel

I'm confused as to why the OGOR data is less that the NRRD Production downloaded data on 3 of these commodities... if additional disposition codes are included, shouldn't the OGOR values be greater?

In addition, there are 2 commodities listed in the OGOR data that are not listed in the NRRD Production downloaded data: "Borrow Sand & Grave (ton)" and "Other". 

I included my Pivot comparison excel in the Team folder [here](https://teams.microsoft.com/l/file/09B1677B-8452-4324-BE54-12974F48B34A?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FOGOR%20B%2FPROD_FTS%20CY10-20%20as%20of%201_6_22_Christine%20Pivot.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
When comparing data CY 2010-2020:

The following commodities do not match, and the OGOR values are LESS than the NRRD yearly production download values:
- Coal
- Oil
- Salt

The following commodities do not match, and the OGOR values are MORE than the NRRD yearly production download values:
- Gas
- Geothermal - Electrical Generation, Kilowatt Hours
- Leonardite
- Sand/Gravel
- Soda Ash

The following commodities do not match, but it looks like minor rounding errors:
- Copper concentrate
- Lead concentrate
- Zinc concentrate

The following commodities are present in the OGOR data, but NOT present in the NRRD production yearly download:
- Borrow Sand & Gravel
- Other
- Unprocessed Gas

**Comment by Maroyafaied** [comment]
@cthomasONRR  Thanks for analyzing the files. Usually production numbers change due to change of reporting based on when the dataset is pulled. For example , when DORC provides us CY 21 production data, they will provide the data back from 2003 and we update all the years with the new production data but it's usually not a significant change. 

Were the volumes significantly different for the commodities you identified as more or less? Also, we do have Borrow Sand & Gravel in the current CY production data but I will ask Donna about Unprocessed gas and other.  Did you get the chance to review if all the disposition codes we need are provided in the file? Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied 
Here's a screengrab of all the commodities that did not match between the 2 datasets for 2010-2020. My pivot excel is located [here](https://teams.microsoft.com/l/file/09B1677B-8452-4324-BE54-12974F48B34A?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FOGOR%20B%2FPROD_FTS%20CY10-20%20as%20of%201_6_22_Christine%20Pivot.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a).
![image](https://user-images.githubusercontent.com/72526208/149152236-0469d6df-1c3e-4e24-896b-9146654c74e6.png)

Aside from copper, lead, and zinc concentrates, there are significant differences between these datasets. 

Borrow Sand and Gravel is not in the NRRD CY Production excel. If it should be, we need to talk to Mojo about getting it added.

Here are Disposition Codes that are present in the most recent OGOR dataset provided, but are NOT present in our "OGOR-B Disposition Categories Glossary" Excel:
- 06 (Gas - Sales-Non-Hydrocarbon Gas)
- 12 (Gas - Transferred to Facility-Returned to L/A)
- 21 (Gas - Flared Oil-Well Gas)
- 22 (Gas - Flared Gas-Well Gas)
- 33 (Gas - Flared Gas-Royalty Due)
- 61 (Gas - Vented Oil-Well Gas)
- 62 (Gas - Vented Gas-Well Gas)
- 63 (Gas - Vented Gas-Royalty Due)

On the disposition code PDF (https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-I.pdf), all codes except for 06 and 12 are highlighted in yellow as being a new disposition code or updated description.

Here are Disposition Codes that are NOT present in the most recent OGOR dataset provided, but ARE present in our "OGOR-B Disposition Categories Glossary" Excel:
- 24 (Theft)
- 43 (Sales - Royalty Not Due - FMP not Assigned)

**Comment by cthomasONRR** [comment]
@Maroyafaied 
Update on disposition codes: All codes in the OGOR dataset are present in the Glossary excel, and vice-versa. My confusion was because I didn't realize there was a gas tab on the glossary excel. Everything matches up!

**Comment by Maroyafaied** [comment]
I updated the DORC team with our findings, we will analyze and compare production data against this data set once we receive and update CY production file in February.
