### ISSUE TITLE
Q1 Report to Nathan 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1900]

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein @mcharg please review, Nathan asked for super simple 1 page summary. Thanks

https://teams.microsoft.com/l/file/EFB37191-D6F9-4749-9858-72CB706F15F8?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FAdmin%2FGoals%20%26%20Accomplishments%2FFY%2022%2FQ1%20Accomplishments.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied Looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks good, I can't think of anything else to add.

**Comment by lpgoldstein** [comment]
@Maroyafaied I just capitalized powerpoint, but it looks good! We've accomplished so much already this year!
