### ISSUE TITLE
December Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1901]

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm seeing the archive is the third most landed on page, not AML.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b5deeade-32cf-4b3a-8a03-4d5a4e119b13)

**Comment by mcharg** [comment]
@daniel-coleman-1 Chrome desktop number is incorrect.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/20ea6721-06a0-42ec-872f-60033d0cd6ee)

**Comment by daniel-coleman-1** [comment]
Corrected, thanks @mcharg
