### ISSUE TITLE
Look into disbursement data for renewable

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1907]

**Comment by cthomasONRR** [comment]
The renewables disbursement excel is saved [here](https://teams.microsoft.com/l/file/5470509C-E945-460C-81E8-8416C8C7555C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FDisbursements_Renewables.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a). I used the NRRD query tool to make this excel and it worked really well! Comments about the graphs created are in Issue #
