### ISSUE TITLE
Correct Historical Revenue File Download Links

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1927]
Historical Revenue links are broken on this page:
https://revenuedata.doi.gov/downloads
![Screenshot 2022-01-14 170855](https://user-images.githubusercontent.com/83892362/149600256-f23fcf89-94b9-4280-b682-367f894dfdb9.png)

https://revenuedata.doi.gov/historical_revenuecsv_CY1982-2002.csv
https://revenuedata.doi.gov/historical_revenue_CY1982-2002.xlsx

**Comment by Maroyafaied** [comment]
@jlouis-onrr Can you look into this as well? Thanks
