### ISSUE TITLE
Upload FY 21 Production data

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1934]

**Comment by lpgoldstein** [comment]
@cthomasONRR here is the [raw data](https://teams.microsoft.com/l/file/3ED15C11-78EC-42D0-804E-B0005662337B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FProduction%2FFY%202021%2FFY03-21%20Production%20File.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
@mojobnichols @lpgoldstein 

The new FY21 Production dataset has more columns than the existing dataset on GitHub\nrrd\database\static\csv\production.

New FY 21 dataset:
![image](https://user-images.githubusercontent.com/72526208/155145531-39dbb86c-e8fe-414b-80cf-9d09f22a6cad.png)

Existing FY dataset:
![image](https://user-images.githubusercontent.com/72526208/155145622-62049d1c-e454-43df-afe8-2005eb07549a.png)

@mojobnichols, Is there anything special I need to do before uploading this new dataset? I crated a branch (FY21-Production), but haven't updated it with new data.

**Comment by cthomasONRR** [comment]
@mojobnichols I published the branch. It's "FY21-Production". The new data is in there for you to check out.
