### ISSUE TITLE
Due Feb 4: Government UX Summit proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1940]
To the Government UX Community—
 
Are you interested in presenting at the 2022 Government UX Summit?  The call for participation is now open! If you have a great topic you’d like to share with the government UX community, please consider submitting it. But first, please read through this entire email.  We know it’s long, but we’ve put together all the information you’ll need.  There is also information about the call on DigitalGov.
 
The 2022 Government UX Summit will be an entirely virtual event held June 7 and 8, 2022. The Summit will be open to all, and registration will be FREE for everyone. Registration is not open yet, but we will let you know when it is.  
 
Last year we had more than 1,000 attendees at the 2021 Summit, and we are looking forward to another successful event this year! 
 
To submit a proposal, complete this form. Proposals are due Friday, February 4, 2022.
 
Please note that we have new requirements from GSA this year. We are focusing on federal work, so all presentations must have a federal employee as the lead author.  Contractors and state and local employees would be eligible to speak only if they are working on federal projects and are co-presenting with a federal employee. We recognize that our state and local colleagues have valuable lessons to share; this year, however, we will have to focus on UX work at the federal level.
 
Before submitting, please note the following:
 
Topics must be relevant to Federal UX work (see topic suggestions below).
All submissions must have a Federal employee as the lead author. 
The presentation itself and any presentation materials must all be fully accessible, following the Revised Section 508 Standards. 
Presenters must submit their presentation materials at least a week before the Summit so we can make them available to attendees.
All presenters must attend a “tech check” a week or so before the Summit.
We will not be posting videos of the sessions this year. GSA has evaluated the analytics and found that very few people actually watch them. Instead, we will invite all presenters to give a 5-minute summary of their presentation, sharing the highlights on June 15, time TBD, with the goal of posting these shorter videos.
 
Submissions for the UX Summit can be presentations, panels, or other appropriate formats.  Presentations can be either 15 or 60 minutes long (including Q&A). Attendees have a range of experience with UX, so submissions can target those newer to UX, those with more experience, or a general audience. 
 
The UX Summit covers all topics related to UX work in the government, such as:
 Case studies of user experience projects or programs (consider sharing lessons learned, too!)
Conducting UX work in a fully remote environment
How to use design and/or evaluation methods
Starting, building, or managing a government UX program
UX research
Government-specific challenges and obstacles
UX and Agile
Using human-centered design approaches for innovation or problem solving
 
A committee of government employees representing a variety of agencies will review the submissions and select the presentations for the final program. We expect to complete the reviews by May. The committee will consider:
 
Relevance – Is the topic of interest to the Federal government UX Community?
Usefulness – Will the presentation provide information the government UX Community can use?
Qualifications of the presenters to discuss the topic
Quality of the submission
Whether the proposed content will fit in the selected session length
 
Please note that this is a government-sponsored event where we are looking to share experiences and best practices. We will not accept presentations that appear to serve as marketing for the presenter's products or services.  
 
If you have any questions, please contact us.

**Comment by lpgoldstein** [comment]
https://doimspp.sharepoint.com/:w:/s/NRRD/EVG_QthNehBMpE9IRhIr3A0BMY8NLYU135z8aLOcYusQoQ?e=aNhbfa
@jkwonatx Please take a look at this and see if you have any areas for improvement.

**Comment by jkwonatx** [comment]
@lpgoldstein same here, no access.
