### ISSUE TITLE
Reiterate on PowerBI instructions and design

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#1942]
@kjgdata 

I'm reviewing your instructions, and I'm having a lot of questions with Step 4. I am trying to update the data files to show our most recent monthly Revenue (December 2021). I was able to update the raw data pretty easily. But for the web downloaded data, I cannot adjust the date filter to show December 2021. The latest it will let me go is to September 30 2021:

![image](https://user-images.githubusercontent.com/72526208/149991289-9d064905-8105-40c2-8858-6cc2e0893d75.png)

For the image in 4.3, maybe we need to work at naming these starting files something very obvious, so that the user knows which file to update. For example, instead of having a file named "monthly_revenue(#)" we name it "NRRD downloaded monthly revenue csv" so there is no confusion.

Create a "troubleshooting" section in the Wiki to highlight issues like the eraser tool.

**Comment by cthomasONRR** [comment]
Also, add the renamed starting Excel files into Teams here:
![image](https://user-images.githubusercontent.com/72526208/150379879-cad72cff-801f-4cf2-ab09-785c6924052c.png)

**Comment by kjgdata** [comment]
I have updated the Wiki Page with the edits that your suggested. I will be closing this issue.
