### ISSUE TITLE
Create Visio template with ONRR colors

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1944]
Christa asked if we had one, so I'm going to work with her to create one.

**Comment by mcharg** [comment]
Had to put in a non-core software request to get the latest version of Visio to work with Christa's files.

**Comment by mcharg** [comment]
@Maroyafaied The Visio template and shapes are in this folder.  Do you want to review before I send to Christa?  Megan took a look and helped with colors.
https://doimspp-my.sharepoint.com/:f:/r/personal/mchargs_mms_gov/Documents/ONRR%20Logo%20and%20PPT%20Template/Visio?csf=1&web=1&e=xlnrPe

**Comment by Maroyafaied** [comment]
@mcharg sure but the link above doesn't show anything for me.

**Comment by mcharg** [comment]
@Maroyafaied Try this one. https://doimspp-my.sharepoint.com/:f:/g/personal/mchargs_mms_gov/EoXahL7Qf_tKtASTll2uhoMBjW4pzWlzSfoE9BXdnQ642w?e=F0COwK

**Comment by Maroyafaied** [comment]
@mcharg it looks good to me.

**Comment by mcharg** [comment]
Sent to Christa to review and then will upload final version to 508 docs team folder.
