### ISSUE TITLE
Test PowerBI Template 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1951]

**Comment by Maroyafaied** [comment]
@cthomasONRR I got PowerBI installed yesterday, feel free to schedule a meeting next week to go over the wiki and how we should be testing. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks! I'm waiting for Kiara to send me her most updated version. Once I have that I will schedule a meeting.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I set up a meeting for us on Tuesday 2/8 at 1pm.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein 
The most updated version of the Template is located [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=PowerBI%2520Templates&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FNRRD%252FData%252FPowerBI%2520Templates)
The wiki page is located [here](https://github.com/ONRR/nrrd/wiki/PowerBI-Templates), if you want to walk through it before the meeting tomorrow

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein I was able to follow the wiki instructions and play around with the revenue template, I was able to change the data source by uploading a different file and played around with filters. I also tried the buttons and selecting multiple attributes with the production file. Looks great.

**Comment by lpgoldstein** [comment]
@Maroyafaied @cthomasONRR me too! So nice to have this available.
