### ISSUE TITLE
Build reusable pivots for renewable data 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1953]
The leadership team went with [Option A](https://zw7izs.axshare.com/#id=cfp7si&p=option_a) and asked to include trend line for disbursements and add content comparing year over year. 

We need the following for FY18, FY 19, and FY 20

**Geothermal and Wind Revenue** 
- [x] screenshot of map on explore data page
- [x] Table showing top 5 states/regions with total for all regions, include trendlines in the table

**Geothermal and Wind Disbursements** 
- [x] Circle chart with % of disbursements for geothermal and wind
- [x] Table by commodity & disbursements, include trendline
- [ ] Statement for total disbursement in particular fiscal year and year over year comparison

**Geothermal Production**
- [x] Table showing production and trends for electrical generation, direct use, and sulfur byproduct.

**Comment by Maroyafaied** [comment]
@Baymatt I started an excel sheet for each data set with the latest data we have

[Geothermal & Wind revenue](https://teams.microsoft.com/l/file/E4DAFD8F-DF9D-424D-B102-369EDFE560AA?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20%26%20Wind%20Revenue.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
[Geothermal & Wind disbursements](https://teams.microsoft.com/l/file/2BB9F316-22F3-448F-A87C-F11DF7EC969B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20%26%20Wind%20Disbursements.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
[Geothermal Production ](https://teams.microsoft.com/l/file/F5F07E6A-47C1-4EAB-8F53-FDE8D40EFCEB?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20Production.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by Baymatt** [comment]
@Maroyafaied Here are the circle charts for FY18, FY19 and FY20. I've also made the pivot tables to obtain these values on the excel sheet.

@mcharg said she would be able to help out and make these images look better using Axure/Powerpoint.

I'll work on trying to create a table that looks like the one in the prototype as well as calculating the percentages.

*FY18*
![renewable_disbursements_fy18](https://user-images.githubusercontent.com/43329595/151883459-5647f7c7-3972-4a04-92e8-bcac2d01116e.png)

*FY19*
![renewable_disbursements_fy19](https://user-images.githubusercontent.com/43329595/151883462-a9dea786-c67f-40f1-bc6e-b9d406c67cfe.png)

*FY20*
![renewable_disbursements_fy20](https://user-images.githubusercontent.com/43329595/151883465-9929f687-3a07-4beb-a3af-98687c9d84d4.png)

**Comment by Maroyafaied** [comment]
@Baymatt Thank you sounds good, let's do it for FY 21 as well to have it ready.

**Comment by Baymatt** [comment]
@Maroyafaied @mcharg The excel sheet has the % breakdowns for geothermal and wind as well as sum of total disbursements and % of disbursements that were renewable.

I'll work on the FY21 sheet, here is the image.

*FY21*
![renewable_disbursements_fy21](https://user-images.githubusercontent.com/43329595/151886190-7187d2ff-37ad-4aee-9144-a51fd0ec7c79.png)

**Comment by Baymatt** [comment]
@Maroyafaied I finished the sheets for FY18-21. I didn't match the exact format of the prototype but it should be simple enough for someone to come into the sheet and find the values they're looking for. It also should be easy enough to do this for future years by duplicating, although some values/filters will need to be changed manually (dates, cell locations for the totals). I'll upload the images to their respective years.

**Comment by Maroyafaied** [comment]
@Baymatt Thank you, you're awesome!

**Comment by Maroyafaied** [comment]
I made a template with tabs for each FY and it contains all the data, there's also excel sheets for each data set that we can reuse for future FYs or use to review data.  @cthomasONRR can you review the data for each FY, production and revenue are easily checked using the query tool.  Here are the links to all the sheets. 

[Renewable snapshot template](https://teams.microsoft.com/l/file/E4DAFD8F-DF9D-424D-B102-369EDFE560AA?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FRenewable%20snapshot%20template.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
[Geothermal & Wind revenue](https://teams.microsoft.com/l/file/154558E4-DFD8-4F92-96BF-418663B482F6?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20%26%20Wind%20Revenue.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
[Geothermal production](https://teams.microsoft.com/l/file/F5F07E6A-47C1-4EAB-8F53-FDE8D40EFCEB?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20Production.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)
[Geothermal & Wind disbursements](https://teams.microsoft.com/l/file/2BB9F316-22F3-448F-A87C-F11DF7EC969B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRenewable%20snapshot%2FGeothermal%20%26%20Wind%20Disbursements.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
@Maroyafaied 

For 2019 Revenue, the total on the template is 436,822,958 but the total on your Pivot and Query data is 37,037,805.42... are you intentionally omitting something? All the other years match up.

All production data looks good!

All disbursements look good too- I added in % for how much went to the States vs U.S. Treasury

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks, I fixed the FY 19 revenue total. And thanks for adding % for funds.
