### ISSUE TITLE
Review FY 20 Renewable Snapshot data 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1958]
[powerpoint](https://teams.microsoft.com/l/file/712CF60D-D296-4002-8BC6-939650285B1B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FRenewables%20Snapshot%20FY20.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by Maroyafaied** [comment]
[powerpoint](https://teams.microsoft.com/l/file/712CF60D-D296-4002-8BC6-939650285B1B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FRenewables%20Snapshot%20FY20.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by Baymatt** [comment]
Looks good on my end
