### ISSUE TITLE
Review content of OGOR B download page with SMEs

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1964]

**Comment by lpgoldstein** [comment]
finally found the file @cthomasONRR https://teams.microsoft.com/l/file/F298DA70-69E7-4CDC-B055-508C6B9C92E1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FOGOR%20B%2FOGOR%20B%20page.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@lpgoldstein I updated the document you linked above. It's ready for your final review.

**Comment by lpgoldstein** [comment]
@cthomasONRR I just edited slightly but looks good.

**Comment by cthomasONRR** [comment]
@lpgoldstein Great! What are next steps? Email it to Stacey and Melissa, and set up a meeting if needed?

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR I will make time to review this today then I'll send an email to SME's to review.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied I made edits resolving your comments. Could you review again? Thanks!

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR  I reviewed and send to SME's for input. I will close this issue and we can create another to implement SME's suggestions.
