### ISSUE TITLE
Draft a tasklist/how-to guide to couple the MMR template (508 compliant)

### ISSUE THREAD

**Issue by jkwonatx** [ONRR/nrrd#1966]
To assist the MSA team in ensuring that the monthly report stays compliant.

**Comment by jkwonatx** [comment]
First draft. Sent to Cory and Lindsay for review. 

[https://app.zenhub.com/files/215585796/026ef049-59a6-45b7-aa00-87e74059f063/download](https://app.zenhub.com/files/215585796/026ef049-59a6-45b7-aa00-87e74059f063/download)

**Comment by lpgoldstein** [comment]
@jkwonatx Checklist looks great to me. Let's add something about running an Adobe accessibility check once the file is converted. I'm sure Cory will have some feedback once he works through the process as well.

**Comment by jkwonatx** [comment]
Received feedback from Cory at MSA. Will use that to prepare for the meeting tomorrow. The aim is to have the final how-to guide ready for a hand-off.

**Comment by jkwonatx** [comment]
here's the deliverable
[Monthly Market Analysis Report Checklist ver 2.docx](https://github.com/ONRR/nrrd/files/8119825/Monthly.Market.Analysis.Report.Checklist.ver.2.docx)
