### ISSUE TITLE
Register for National Association of Government Web Professionals conference

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1977]
Registration opens in April
https://nagw.org/

**Comment by daniel-coleman-1** [comment]
Presentation proposals are due February 25:
https://nagw.org/2022_Call_for_Speakers

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 closing this issue since we missed the proposal deadline.

**Comment by lpgoldstein** [comment]
presentations proposals are now due March 18

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I confirmed that speakers have to attend in person so I'm closing this issue.
