### ISSUE TITLE
Create FY 21 Renewable Fact sheet 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1979]
once we receive FY 21 production data set from DORC, we can create FY 21 snapshot and also recheck the production numbers for Geothermal on previous renewable factsheets (Fy18-FY20)

**Comment by lpgoldstein** [comment]
@cthomasONRR please [review: ](https://teams.microsoft.com/l/file/943615B4-414E-4F9F-9314-435635F96B17?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pdf&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FRenewables-Fact-Sheet-FY21.pdf&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
@lpgoldstein For this FY21 Fact Sheet, do we know that the FY21 Production data we were given is correct? Should we wait to finalize until we get the updated FY21 Production?

**Comment by cthomasONRR** [comment]
All the data look good, and the FY21 Production matches what we currently have. I suggest holding off until we get the new production next week, just in case it changes for FY 2018-2021.

**Comment by lpgoldstein** [comment]
@cthomasONRR moving to next sprint and we will recheck data once we get a new file

**Comment by lpgoldstein** [comment]
@cthomasONRR all fact sheets have been updated with new data. please review when you have time https://teams.microsoft.com/l/file/5CCC7654-C50D-4E0C-9523-30EEE4E444FE?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pdf&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FRenewables-Fact-Sheet-FY21.pdf&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@lpgoldstein 
I checked all fact sheets (2018-2021), and the new FY Production data matches with all fact sheets. All sheet still pass the accessibility check. I put the new Production data in the following location: NRRD\Data\Renewable snapshot.

**Comment by Maroyafaied** [comment]
@lpgoldstein please use this PR to add the fact sheets , it has a tab in the homepage called "Fact Sheets". Thanks 
https://github.com/ONRR/nrrd/pull/1960
