### ISSUE TITLE
February analtyics

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1986]

**Comment by daniel-coleman-1** [comment]
@mcharg this is ready for review

**Comment by mcharg** [comment]
@daniel-coleman-1 The chart only goes to Jan. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3d079bad-1e5a-4e31-8ebd-7c618c1ba118)

**Comment by mcharg** [comment]
@daniel-coleman-1 Everything else looks good.
