### ISSUE TITLE
Update analytics with new chart

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1987]

**Comment by mcharg** [comment]
Done.

@daniel-coleman-1 We decided to swap out the bar chart with a line chart and I moved the bar chart to an analytics page along with all the other stuff we're no longer tracking. Please review.

Current analytics: https://github.com/ONRR/nrrd/wiki/Analytics
New archive: https://github.com/ONRR/nrrd/wiki/analytics-archive
Updated instructions on wiki: https://github.com/ONRR/nrrd/wiki/Analytics-Reports

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you please review.
