### ISSUE TITLE
Update Content in Production by Year Download page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1989]
We need to change the content in the scope section since the data is now being pulled from OGOR B header rather than OGOR A. We also need to add any products to the list that weren't there before (for example: unprocessed gas and wavelite).

**Comment by Maroyafaied** [comment]
DORC recommended we change the scope to the following: The dataset currently includes data tracked and managed by the Department of the Interior’s Office of Natural Resources Revenue (ONRR). The production data for Oil and Gas is collected on Form ONRR-4054-B (Oil and Gas Operations Report, Part B). Solid mineral production is collected on Form ONRR-4430 (Solid Minerals Production and Royalty Report)." Geothermal sales volumes are obtained from the Form ONRR-2014 (Report of Sales and Royalty Remittance).

**Comment by cthomasONRR** [comment]
@Maroyafaied I will work on this once we know the FY21 Production PR is good to go.
