### ISSUE TITLE
Fill out spreadsheet with what web services we're using

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1996]
The Web Council wants all bureaus and offices to fill this out, so we know who's using what.

Spreadsheet: https://teams.microsoft.com/l/file/B19ADBE7-2CD2-402F-B0CC-94A62F3AEE72?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FWebCouncilandColleagues%2FShared%20Documents%2FGeneral%2FDOI%20Applications.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FWebCouncilandColleagues&serviceName=teams&threadId=19:39eec87497dc4490a5523a8f69f40645@thread.skype&groupId=9fea1abf-45a4-4e1f-bc33-50ee36b3b371

**Comment by Maroyafaied** [comment]
@mcharg I don't have access to the excel file but I requested it.

**Comment by mcharg** [comment]
@Maroyafaied I have access. I dropped in initial answers. Let me know if you want me to make edits.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9a43db7a-e46d-4af5-a0fe-7e7974a608d3)

**Comment by Maroyafaied** [comment]
@mcharg and I reviewed this during our check in. Closing issue.
