### ISSUE TITLE
Organize and consolidate all ODDD's folders & materials in one location 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1997]

**Comment by cthomasONRR** [comment]
@mcharg I don't have any ODDD files on my personal drives, but I will organize the ODDD Team folders once everything is migrated over

**Comment by mcharg** [comment]
@cthomasONRR Sounds good. I'm slowing getting things migrated over. I'm almost done with the NRRD folder.

**Comment by mcharg** [comment]
I'm also uploading stuff from my desktop, since I need to free up space for the Windows upgrade.

**Comment by cthomasONRR** [comment]
@mcharg I think this issue can be closed now. Thank you so much for all your help with this!
