### ISSUE TITLE
Create one page on ONRR's efforts for Transparency 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1999]
A request from Christ during the EITI group meeting.

**Comment by lpgoldstein** [comment]
[EITI 21-22 Strategic priorities](https://app.zenhub.com/files/215585796/bb8a87c6-42ae-4f44-87aa-60c413f2ac16/download)

"Open data and associated strategies for stakeholder engagement will increasingly become the norm for EITI implementation. Proactive disclosure founded on timely, usable and accessible data will gradually replace retrospective reporting to inform decision making, foster independent analysis, and promote public debate. This will be accompanied by an evolution of the role of multi-stakeholder groups from ensuring compliance through reports to placing greater emphasis on the use, analysis and dissemination of data."

**Comment by Maroyafaied** [comment]
@mcharg please review https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/ONRR%20Transparency%20.docx?web=1
