### ISSUE TITLE
Plan user research on new query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#200]
We can probably use a lot of what was in the plan from the last round.

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg is this issue supposed to be closed? or do we still need a plan?

**Comment by mcharg** [comment]
@lpgoldstein Wrote a plan, but we should probably review it.
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BCEE6D330-879A-4B66-865B-6917B05E823F%7D&file=Query%20Tool%20Study%20Plan%202.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@lpgoldstein I made edits and comments in the plan.

**Comment by mcharg** [comment]
Looks good.  I put in a few additional edits.
