### ISSUE TITLE
Upload & review Nov production monthly data 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2001]

**Comment by cthomasONRR** [comment]
The new monthly production dataset (January 2003 to November 2021) has less rows (1817) than our existing NRRD dataset (1833 rows, January 2003 - October 2021). So, some data has been rolled up in this new dataset. I can't tell what's been rolled up yet.

Also, our existing monthly NRRD production file has dates separated into 2 columns (A - Month, B- year) and are not always in chronological order. The new monthly file has dates in 1 column (A - MM/DD/YYY) and are in chronological order.
