### ISSUE TITLE
Review Content for production monthly download page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2003]

**Comment by cthomasONRR** [comment]
@Maroyafaied I updated the language in the document linked in my comment above. I made sure to match the language to the OGOR-B write-up that DORC reviewed. This is ready for your review. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR this looks good, I made minor comments/changes.

**Comment by cthomasONRR** [comment]
@Maroyafaied This updated text is now incorporated into PR #2005 . I checked it and it looks good. I will close this issue as any modifications will be in the PR.
