### ISSUE TITLE
Q2 Metrics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2011]

**Comment by Maroyafaied** [comment]
@lpgoldstein not sure if you need a seperate issue for onrr.gov?

**Comment by lpgoldstein** [comment]
@Maroyafaied Here you go! I reused the document from last Quarter. https://doimspp.sharepoint.com/:w:/s/NRRD/EZdnbx5NIJ5EhyUVyulIUDABZA4g8P9B0nLNQ4OcqO-ZsQ?email=Maroya.Faied%40onrr.gov&e=RPUv4f

**Comment by Maroyafaied** [comment]
@lpgoldstein Thanks, I added some things and saved it in the Teams folder. If it looks good to you then please close this issue. Thanks 
https://teams.microsoft.com/l/file/FB7C9249-7525-47F0-A216-3343746F4FC2?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FAdmin%2FGoals%20%26%20Accomplishments%2FFY%2022%2FFY%2022%20Q2%20Metrics.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a
