### ISSUE TITLE
Identify webpages for SME review & draft email 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2014]

**Comment by mcharg** [comment]
I think these sections are ready to review:
- Regulations (just missing colored text on FOGRMA page and an email icons)
- Compliance (just missing contacts tabs)
- Training Presentations (would be a good time for a discussion about the reading order warnings on the ppts)

**Comment by Maroyafaied** [comment]
@mcharg Do you rather we have SMEs review by sending them an email & link to dev or do you want me to schedule a meeting to review  with the SMEs.

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR ok it would be helpful to identify who the SMEs are for these pages, I remember I took notes when reviewing wireframes and listed the attendees.

**Comment by mcharg** [comment]
@Maroyafaied Found this draft email in the folder with the previous design review notes. https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Design%20Reviews%20-%20ONRR%20teams/DesignReviewInvitationEmail.docx?d=wc393eaff7b7447d08eb6ba90402ac0d1&csf=1&web=1&e=dlImvP

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg I updated the email Shannon linked to reflect this final review:

Hello,

As you know, our Open Data, Design, and Development (ODDD) team has been redesigning onrr.gov. We are continuing to make sure the new redesign is meeting the needs of all stakeholders including end users, the internal teams who post to the website, and ONRR leadership. We are now ready to share with you the final redesign!

As part of the final design review process, we want to include stakeholders that previously reviewed our prototypes. We would like to show you the changes that have been made, walk you though the new dev site, and get your final approval on the redesign.   

Please let us know some good times for a one hour meeting for a review of the final design. 

Thanks, 

The ODDD Team

**Comment by Maroyafaied** [comment]
@cthomasONRR @mcharg I set up meetings with all the groups identified above. I will create separate issues for each group for record of approval and to note if there's any requested changes within each groups issue.
