### ISSUE TITLE
Update User Centered Design wiki page with new diagram

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#2031]
We're linking to it from the Troubleshooting blog post, so we should update it to the latest and greatest.
https://github.com/ONRR/nrrd/wiki/User-Centered-Design-Process

**Comment by mcharg** [comment]
@Maroyafaied How's this look for onrr.gov. I removed all of the duplicate pages, added a note and link to the NRRD wiki on the homepage and at the bottom of the right nav.  I also reworked the home page to make it specific to onrr.gov.
https://github.com/ONRR/onrr.gov-site/wiki

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied The User-Centered Design Process page is ready to review.
https://github.com/ONRR/nrrd/wiki/User-Centered-Design-Process

**Comment by mcharg** [comment]
We should probably do some reorganizing of the NRRD right nav to separate NRRD stuff from process stuff.

**Comment by mcharg** [comment]
Reorganized the NRRD right nav.
https://github.com/ONRR/nrrd/wiki

**Comment by Maroyafaied** [comment]
@mcharg everything looks good, but I don't know if it's just my eyes but the user centered image is a bit blurry for me.

**Comment by mcharg** [comment]
@Maroyafaied It is blurry. I exported it from PPT to an image. I'll spend some time tomorrow seeing if I can get a cleaner version, unless @lpgoldstein wants to look into that.

**Comment by mcharg** [comment]
@Maroyafaied Does it look less blurry now?
https://github.com/ONRR/nrrd/wiki/User-Centered-Design-Process

**Comment by Maroyafaied** [comment]
@mcharg yes, it's better than before.
