### ISSUE TITLE
Impact Expo presentation: Agile

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#2035]

**Comment by mcharg** [comment]
@lpgoldstein This is ready for you to review.
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY22/Impact%20Expo/Agile.pptx?d=wac56bb1685bd42db830d228b0dc1ff0f&csf=1&web=1&e=uKlPzb

**Comment by lpgoldstein** [comment]
@mcharg just a few edits. Looks good!

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review.

**Comment by Maroyafaied** [comment]
@mcharg This is great, so much valuable information! Can you check for accessibility and it's up to you if you'd like to schedule a time to practice to see if 30 min will be enough time. Thanks

**Comment by mcharg** [comment]
Yeah, I still need to do alt text. Was waiting until we finalized the slides. I'll schedule a time to practice.

**Comment by mcharg** [comment]
@Maroyafaied I added a Resources slide at the end with links to trainings, if you want to take a look.

**Comment by Maroyafaied** [comment]
@mcharg looks good

**Comment by mcharg** [comment]
@lpgoldstein Alt text is ready to review.

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied I added a slide at the beginning about my agile experience, to show why I'm qualified to talk about this. https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY22/Impact%20Expo/Agile.pptx?d=wac56bb1685bd42db830d228b0dc1ff0f&csf=1&web=1&e=lwmG2Q

**Comment by lpgoldstein** [comment]
Looks good!

**Comment by mcharg** [comment]
@lpgoldstein Will you please look at formatting in this one? There are gray bullets, etc.

**Comment by mcharg** [comment]
I created a new issue for next sprint to practice more, so these issues can be closed once we finalize the presentations.
