### ISSUE TITLE
Impact Expo presentation: Customer Experience

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#2036]

**Comment by mcharg** [comment]
@lpgoldstein This is ready for you to review.
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY22/Impact%20Expo/CX.pptx?d=w7c96d74054044a1e89477884c982772a&csf=1&web=1&e=AlJUNG

**Comment by lpgoldstein** [comment]
@mcharg looks good! I can recheck once alt text is in.

**Comment by mcharg** [comment]
@Maroyafaied Ready for you to review.

**Comment by Maroyafaied** [comment]
@mcharg This is also great, slide #27 made me laugh. Let's also practice this one since It's a lot of information for 30 minutes.

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein I added a resources slide at the end. I also found a full list of laws in the Digital.gov CX Toolkit, so I added the full list and linked out to the page on slide 8.

**Comment by mcharg** [comment]
I also added a conclusion slide that points out the excellence in public service part of ONRR's vision.

**Comment by lpgoldstein** [comment]
@mcharg approved!

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein I forgot I wanted to put the journey maps in here. I added them in slides 16 & 17.

**Comment by lpgoldstein** [comment]
Very nice. Let me know when you want me to check alt text.

**Comment by mcharg** [comment]
@lpgoldstein You can check it now.

**Comment by lpgoldstein** [comment]
@mcharg Looks good - I was looking at selection pane and missed it.

**Comment by mcharg** [comment]
I created a new issue for next sprint to practice more, so these issues can be closed once we finalize the presentations.

I'm still working on updates to this one.
