### ISSUE TITLE
Impact Expo Presentation: VSFS 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2040]
@jkwonatx @Isabelh99 Maroya suggested we do this in a panel format. I'll do a brief overview of the program and then ask you several pre-determined questions to make it more interactive. Think about what you want to share so we can make sure that the questions elicit that response. Drop any question ideas in the comments. We have a 30 minute slot.

**Comment by jkwonatx** [comment]
Who is the audience? Interns or staff? If the latter - folks who want to improve their existing internship or curious as to how they might implement it? Both?

**Comment by lpgoldstein** [comment]
@jkwonatx onrr employees and mgrs are the intended audience. We want to share the info about the program and the benefits to both onrr and interns. no other team in onrr has vsfs interns but as you've seen - many would benefit from having interns!

**Comment by jkwonatx** [comment]
@lpgoldstein For now, I'll share high level topics I have much to talk about. Common theme here are professional/career experiences that were new to me and therefore refreshing. New ways of conducting business, in other words, that I thought are efficient, effective, and engaging. 

Non-agile (commonly available to all interns):
- Interview, onboarding processes
- communication (via slack, standup, github, zenhub)
- interns specific meetings/ 1:1 mentorship
- setting expectations 

agile specific (dependent on the level of engagement interns can afford) 
- PM related
- team building/structure
- scrum/kanban
- everything else about it

I don't need to speak on all -- will certainly prioritize. Any thoughts or feedback welcome.

**Comment by lpgoldstein** [comment]
@Maroyafaied ready for your review: https://teams.microsoft.com/l/file/52F865E4-2E58-404E-A1EF-7DBC1743E1C6?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FOutreach%2FProposals%20%26%20Presentations%2FFY22%2FImpact%20Expo%2FIMPACT%20Expo%20FY22%20VSFS%20Presentation.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@lpgoldstein I've reviewed and put in some comments. Overall, I think the agenda is great. Do we have questions for the panel discussions yet?

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good. Thanks

**Comment by lpgoldstein** [comment]
@Maroyafaied Can I close and open another issue to practice next sprint?

**Comment by Maroyafaied** [comment]
@lpgoldstein yes!
