### ISSUE TITLE
Upload and review CY 2021 Production file

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2041]

**Comment by cthomasONRR** [comment]
Issues found so far: 

I'm checking Production CY 21 in Explore data. When I click on Offshore Gulf of Mexico, I get the following error. In the spreadsheet, it's just labeled as "Offshore Gulf"... maybe it needs to be changed to "Offshore Gulf of Mexico"?

I also noticed that in products there is:

- Coal (ton)
- Coal (tons)

Could we remove the Coal (tons) and make sure all data is under Coal (ton)?
