### ISSUE TITLE
Prepare All Hands Power Point Presentation 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2043]

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein @mcharg please review, it def needs some love. Keep in mind, I only have 10 min or so and expected to give a brief demo as well. https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20&%20Presentations/FY22/ONRR%20All%20Hands%20May%202022.pptx?web=1

**Comment by mcharg** [comment]
@Maroyafaied I reviewed and added a couple of comments.

**Comment by cthomasONRR** [comment]
Looks good! I added in some comments, and made minor formatting edits

**Comment by lpgoldstein** [comment]
Minor formatting as well and added alt text and actual text from FOIA report in the notes section.

**Comment by Maroyafaied** [comment]
Thank you all.
