### ISSUE TITLE
Practice IMPACT Expo VSFS Presentation 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2054]

**Comment by Isabelh99** [comment]
Quick question, where can I find a copy of the questions?

**Comment by lpgoldstein** [comment]
@Isabelh99 Sorry they were in a chat! Why did you apply for the program? Is there anything that was surprising? What was unique about your experience? And do you have any advice for offices thinking about hosting interns?

**Comment by lpgoldstein** [comment]
Also what was it like to join a virtual team?

**Comment by Isabelh99** [comment]
Got it and thank you!

**Comment by Isabelh99** [comment]
@lpgoldstein Also could you resend the teams link to join the meeting? For some reason it’s not popping up in my calendar.

**Comment by Isabelh99** [comment]
> @Isabelh99 https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_YWZjZjA5YjMtN2Q1ZS00NTBhLWE0NzItOWVlMWI3ZDI5MDkw%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%25220693b5ba-4b18-4d7b-9341-f32f400a5494%2522%252c%2522Oid%2522%253a%25220a968c00-1ccf-42b2-81dd-6848fcd15829%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=9812f344-c1cb-4e94-8455-d99792166e84&directDl=true&msLaunch=true&enableMobilePage=false&suppressPrompt=true

Just checking, it starts at 2pm EST right?

**Comment by lpgoldstein** [comment]
@Isabelh99 Yes! Let's log in a few minutes early to make sure everything works

**Comment by Isabelh99** [comment]
Noted and sounds good!
