### ISSUE TITLE
Due March 6: Government UX Summit Proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#206]
Do you have experience with a UX method or project you’d like to share with the government UX community?  Consider submitting to the 2020 Government UX Summit!  It’s a great opportunity to share your experiences and lessons learned with your government UX colleagues. 
 
The 2020 Government UX Summit will take place at the Library of Congress, near the Capital South Metro station in Washington, DC on May 12, 2020 from 9 am to 4 pm.  Eligible presenters include US government employees (all levels) and contractors with US government email addresses (with their agency’s approval).  Speakers from outside DC can present remotely. 
 
To submit a proposal, complete the attached template and email your proposal to me at [ask Shannon for email address]. Submissions are due by COB Friday March 6. 
 
Last year we had approximately 340 attendees, attending in-person and remotely, with representation from across all levels of government, and we are hoping for even more this year! Registration is FREE for remote and in-person attendance. 
 
Submissions for the UX Summit can be individual speakers, panels, or other appropriate formats.   All sessions will be streamed for our UX CoP colleagues who are outside the DC area.  The UX Summit covers all topics related to user experience work in the government, such as:
 

- Design and evaluation methods (especially more applied topics, such as training with a particular method)
- Case studies of UX projects or programs
- UX tools
- Starting and building a government UX program
- Lessons learned in managing a user experience program
- Government-specific challenges and obstacles
- UX and Agile
- Using UX to innovate
- UX research

 
New this year, we are hoping to accommodate different topics and level of discussion by offering sessions of different lengths.  Specifically, we are looking for the following:
 

- 10-minute presentations, where speakers can present short discussions or brief highlights
- 45-minute  presentations, where speakers can discuss case studies or share lessons learned with a project or method
- 90-minute sessions, where speakers can provide more in-depth training on a UX method

 
Attendees at the summit will have a range of experience in UX.  If you’re interested in presenting, please submit a proposal using the attached template.  Your proposal should include:
 

- Title
- The presenter(s) and their affiliation(s)
- Name and email for the primary presenter
- Whether presenters will be remote
- Length of the presentation (10 minutes, 45 minutes, or 1 ½ hours)
- Description (250 words) of the presentation and what the attendees will learn
- Brief abstract for the program (100 words)
- Target audience for the presentation (e.g., novice or experienced, technical vs not, any other information that will help potential attendees)
- Short bio of each presenter showing their qualifications for the proposed topic (100 words each)

 
A committee of government employees representing a variety of agencies will review the submissions and select the presentations for the final program.  The reviews will be based on:
 

- Usefulness of the information to the government UX community
- Relevance of the topic to the government UX community
- Quality of the submission

 
Note that this is a government-sponsored event where we are looking to share experiences and best practices.  We will not accept presentations that appear to serve primarily as marketing for the presenter's products or services.

**Comment by jennmalcolm** [comment]
This is due Friday @mentastc

**Comment by mentastc** [comment]
Submitted proposal
