### ISSUE TITLE
Write follow-up blog post on learning user research

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#208]

**Comment by lpgoldstein** [comment]
@mcharg @jennmalcolm This ies ready for your review https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/EUqGTs42AuhBgoJAP50cdloBpCKu4xZwFclnpVeC_h7-9g?email=Jennifer.Malcolm%40onrr.gov&e=IfwIj5

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied I added comments to the doc.

**Comment by lpgoldstein** [comment]
@mcharg @Maroyafaied I incorporated Shannon's comments

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein Looks good.  I added a few more comments (mostly indicating acronyms that need to be spelled out).
