### ISSUE TITLE
Approval for repositories to remain public after migration to DOI

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2084]

**Comment by Maroyafaied** [comment]
Emailed program manager and cc'd @lpgoldstein

**Comment by lpgoldstein** [comment]
We haven't heard anything back so I'm moving this issue to next sprint.

**Comment by lpgoldstein** [comment]
Update that Nathan doesn't have a problem with this but Joe is on vacation so let's follow up next week.

**Comment by Maroyafaied** [comment]
Moving to next sprint, I wasn't able to get an update

**Comment by Maroyafaied** [comment]
I sent another follow up email today.

**Comment by Maroyafaied** [comment]
Nathan approved for the repositories to remain public.
