### ISSUE TITLE
Add coloring to helpful tips icons for valuation examples 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2089]
The helpful tips icons were built in issue #1447,  they still need coloring.

**Comment by cthomasONRR** [comment]
@R-mohansai 

These icons are only within the interactive example webpages, located here: https://onrr.gov/references/valuation?tabs=valuation-examples

There are 4 interactive examples so far, 2 that are live:
https://onrr.gov/references/valuation/processed-gas-example
https://onrr.gov/references/valuation/pop-example
And 2 that we are waiting for final approval to go live:
https://beta.onrr.gov/references/valuation/ipmp
https://beta.onrr.gov/references/valuation/rpmp-act

Within every example, there are yellow and purple card blocks that each have an icon in the top left.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/baf8f4b3-44ee-450b-ac74-da08ddc496e5)  
Yellow card block is always the exclamation mark icon and we want this icon to be the same color yellow as the card.
Purple card block is always the info icon and we want this icon to be the same color purple as the card.

Thanks!
