### ISSUE TITLE
Set site content line length

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/nrrd#209]
Here is some nerdy stuff about line length, readability, and typographic practice, if anyone is interested.
https://practicaltypography.com/line-length.html

**Comment by jlouis-onrr** [comment]
https://209-setcontentlinelength.app.cloud.gov/

**Comment by mcharg** [comment]
@jlouis-onrr Looks good.

**Comment by jlouis-onrr** [comment]
great, adding to #245 to get merged into dev
