### ISSUE TITLE
Create PowerBI dashboard for production monthly homepage data checks 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2090]

**Comment by mcharg** [comment]
@Isabelh99 Is this done?

**Comment by cthomasONRR** [comment]
@Isabelh99 Production is always a little bit behind revenue and disbursements. Right now, we only have up to February 2022, which is in the "Production Volumes as of 06-08-2022_CSV" file.

**Comment by Isabelh99** [comment]
That makes sense. Found it!

**Comment by Isabelh99** [comment]
Updated! This file should work now :).
Its in this folder: https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Other%2520PowerBi%2520Templates&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FNRRD%252FData%252FPowerBI%2520Templates%252FProduction%252FOther%2520PowerBi%2520Templates

**Comment by lpgoldstein** [comment]
@Isabelh99 it's looking better - everything works and the correct numbers are loading but the percentage change for the source breakdowns are wrong. The overall % change is right though 
coal
![image](https://user-images.githubusercontent.com/39419003/182930431-269d0c24-08ee-48b9-9cd0-5484cf8c815d.png)
gas
![image](https://user-images.githubusercontent.com/39419003/182930756-79633ffb-8b69-41d5-b915-86e6fabd7cb7.png)
oil
![image](https://user-images.githubusercontent.com/39419003/182930992-ae840d25-a016-4956-8f6e-ef8f052f41e2.png)

**Comment by Isabelh99** [comment]
Yes, you really have to drill through the filters for each product (gas, oil, coal). These filters produce the numbers for Native American (bbl-oil)... I can put preset filters that may be helpful (blue)?... in the meanwhile, I search for a custom formula / values to display the right numbers.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/93946660/182936071-bbce9c2f-2ee6-4993-b387-28fdf314a0b5.png">

**Comment by lpgoldstein** [comment]
@Isabelh99 I think that would be helpful. Thanks!

**Comment by Isabelh99** [comment]
Awesome! Uploading same place

**Comment by lpgoldstein** [comment]
@Isabelh99 This looks good. I think we can close out the issue.
