### ISSUE TITLE
Update out of date wiki pages

### ISSUE THREAD

**Issue by mentastc** [ONRR/nrrd#210]
following is a list of pages that need to be updated 

- [x] https://github.com/ONRR/nrrd/wiki/Analytics-Segments-and-Reports
Not sure if our not having google has changed this page. 
SM: I updated with a new dashboard report and removed segments that are no longer usable with the changes to GA tracking. 
<br>
- [ ] https://github.com/ONRR/nrrd/wiki/Content-and-data-maintenance-notes
Very out of date
<br>
- [ ] https://github.com/ONRR/nrrd/wiki/Continuous-integration-tools
Will be out of date when we switch repos
<br>
- [x] https://github.com/ONRR/nrrd/wiki/Data-Catalog
Out of date
<br>
- [x] https://github.com/ONRR/nrrd/wiki/Onboarding-checklist
Out of date, goggle drive and slack stuff
<br>
- [x] https://github.com/ONRR/nrrd/wiki/Preview-urls
Will need updating when we move repos
<br>

- [x] https://github.com/ONRR/nrrd/wiki/Problem-statement
Out of date
SM: I deleted this page. It appeared to be an old stand alone page, but now it's a section on the product framing page.
<br>
- [x] Review and update research branch links
SM: I reviewed and updated everything in the research branch, except this page.
https://github.com/ONRR/research/blob/master/nrrd-research/summary-jan2016.md
Do we want to update these links or can we archive it?  I don't know where to link some of them because they were anchor links that now go to 404 pages.

**Comment by mcharg** [comment]
I went through this list and updated what I could.

**Comment by Maroyafaied** [comment]
made new issue specific to data and continuous integration
