### ISSUE TITLE
Production monthly PowerBi dashboard

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2105]
@Isabelh99 please add the ability to check percentage change year over year and align the numbers.

@Baymatt please review and test the production monthly dashboard.

**Comment by Isabelh99** [comment]
Here is the production with a slider option now!
https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/PowerBI%20Templates/Production/ONRR_Production_Copy_MayCompleted.pbix
