### ISSUE TITLE
NRRD June Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2120]
@daniel-coleman-1  please complete this task and have it ready for review no later than August 1, 2022. Please tag me in the issue when its ready for review.  After incorporating comments received from review, please  publish to the wiki no later than August 5, 2022

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this is ready for review

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please correct the following;

1. Total unique number of searches is wrong, please update with June's number.  
![image](https://user-images.githubusercontent.com/40175688/181353878-7de385c3-11a8-4516-b04b-3eb03fe33d20.png)

2. The % for devices should only be two decimal places, please correct formatting. 
![image](https://user-images.githubusercontent.com/40175688/181354164-c796a4a0-435d-4af8-87ea-4c343d11c44c.png)

3.  The tablet and mobile numbers are switched, please correct.
![image](https://user-images.githubusercontent.com/40175688/181354358-5b4e32c1-6e36-4adf-8f38-ad0f47098e6d.png)

4. The % for the Firefox desktop browser is wrong, please correct. 
![image](https://user-images.githubusercontent.com/40175688/181355405-c118aa2e-c017-40df-99ab-fae397da836a.png)

5.  Per instructions, please add all desktop browsers above 1%, there's one missing. Please add. 
![image](https://user-images.githubusercontent.com/40175688/181355644-cb26cb2a-1c81-4df7-8bb0-b5289d8a25ca.png)

6.  Fix formatting for the Android Webview to be its own line
![image](https://user-images.githubusercontent.com/40175688/181355885-3be7f4cd-8225-472b-9eb2-e54eba29d1e7.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied thanks for the edits, all have been input

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the percentage is missing for the last desktop browser listed and I'm not seeing any mobile browsers listed anymore. 
![image](https://user-images.githubusercontent.com/40175688/181497710-a3a60865-fdd6-4619-8523-934b892f07cc.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this is good to go

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks good
