### ISSUE TITLE
Update OGOR B Pull Request

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2123]

**Comment by Maroyafaied** [comment]
There was an update given to DORC that publishing this dataset is been pushed back. Moving this to next sprint.

**Comment by Maroyafaied** [comment]
@cthomas both files should load now in dev. Please review, thanks.

**Comment by cthomasONRR** [comment]
@Maroyafaied The text looks good.

My only question is that where I have "Disclaimer" highlighted in yellow in the image below, should this instead say "VDP" or "Vulnerability Disclosure Policy"?

![image](https://user-images.githubusercontent.com/72526208/196950029-bc2a963b-8b5f-462e-aa7c-1292ea601636.png)

Other than that, I think it's good to link!

**Comment by cthomasONRR** [comment]
@Maroyafaied I was able to download the OGORB files from dev. 

I checked historical revenue and disbursements, and I cannot download those any more. Their file path changed to "/downloads/downloads/historical_revenue_CY1982-2002.xlsx"
