### ISSUE TITLE
Develop Interview Questions 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2124]

**Comment by cthomasONRR** [comment]
Messaged Amy and Chris in RV to see if they would share how they developed their interview questions.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein I added different types of questions to the documents, please review and we can meet to refine it. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks good- I noticed you added the same question to a few categories. I'm ok with that, it's good to have lots of questions compile and categorized.

**Comment by cthomasONRR** [comment]
@lpgoldstein @Maroyafaied I highlighted questions that I think would be good for the interview. Please add comments and let me know what you think. Thanks!
