### ISSUE TITLE
July NRRD analytics

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2133]

**Comment by cthomasONRR** [comment]
@lpgoldstein @Maroyafaied 

July analytics are up on the wiki: https://github.com/ONRR/nrrd/wiki/Analytics
Here is my word to to help with reviewing: [link](https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/Analytics%20July%2022.docx?d=wd769a231ce6244cd86d8ba12fa29b34d&csf=1&web=1&e=O5hQXj)

Could one of you please review?
Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR @Maroyafaied looks good!
