### ISSUE TITLE
Upload and review new monthly Revenue and Production data

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2137]

**Comment by Maroyafaied** [comment]
@Maroyafaied merge pr to dev

**Comment by Maroyafaied** [comment]
@cthomasONRR I'm seeing the data in dev now. https://dev-nrrd.app.cloud.gov/downloads/production-by-month/

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage


**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State (for Yearly data only)
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@Maroyafaied I checked the data again, everything looks good!

**Comment by Maroyafaied** [comment]
@cthomasONRR Great, you can go ahead and close this issue since what's on dev will go to the live site.
