### ISSUE TITLE
NRRD FY23 Metrics Planning 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2156]

**Comment by lpgoldstein** [comment]
@Maroyafaied Here is the link to the NRRD metrics document 
https://doimspp.sharepoint.com/:w:/s/NRRD/Ec1wrxWIc8JDvUlieut3e34BsL7uaLabPD6cztB5gXZYgQ?email=Maroya.Faied%40onrr.gov&e=5cQJkH

**Comment by Maroyafaied** [comment]
@lpgoldstein I'll probably have to move this to next sprint but I'll leave it for now and see by next week

**Comment by lpgoldstein** [comment]
@Maroyafaied I started earlier than usual this year so plenty of time.

**Comment by Maroyafaied** [comment]
@lpgoldstein I'm moving the issue to next sprint, please reschedule the meeting that you had set up for today.
