### ISSUE TITLE
Explore Data: Increase contrast between chart oranges

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#216]
They need to be at least 1.4:1, but preferably 1.5:1.

Current contrast:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e68686c0-1b10-46f4-9f9f-41638e8ed531)

Palette with 1:4:1:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/564177c6-84b9-4ec5-b64d-b91606b8ea4d)

**Comment by mojobnichols** [comment]
It was a bug where color linear scale used the data domain instead of max circles.
