### ISSUE TITLE
research lighthouse 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2160]

**Comment by lpgoldstein** [comment]
@Maroyafaied All of our scores should be above 50 and they are. 90-100 is optimal. Most of our scores are very good. There are areas for improvement but we don't have the bandwidth right now to do that. I think that when we do have more capacity we can go to the page with the low score and run the lighthouse audit. The actual report will suggest areas for improvement. We can then create issues to fix those items but we will need to work with a developer to do that.

**Comment by Maroyafaied** [comment]
@lpgoldstein Ok thanks for explaining, lets continue to track the lighthouse reports as part of our metrics.
