### ISSUE TITLE
Explore Data: Map cuts off on right in Edge

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#217]
This is in the branch with the dot charts (#212). It disappears behind a line when you pan.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/357767cd-b4ba-4ede-a4b5-9ab651d71da5)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e514d285-2070-41ef-a2c7-ee37a129db92)

**Comment by jennmalcolm** [comment]
Not an issue anymore.
