### ISSUE TITLE
Q 4 metrics and annual metrics fy22

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2185]

**Comment by lpgoldstein** [comment]
@Maroyafaied Here are both documents. [FY22 metrics ](https://doimspp.sharepoint.com/:w:/s/NRRD/EXSwOml8S01Jlxm_N-6tFpgBkVw5QktxD2YfJh-cki7O2w?e=ZCfnAG)  and [Q4 metrics](https://doimspp.sharepoint.com/:w:/s/NRRD/EWLhdTwT2QBOvJ5j12SoCbQBbj7wlWyDvFk8pkXPKkTQWQ?e=8NsqLd)

**Comment by Maroyafaied** [comment]
@lpgoldstein I've reviewed and made edits. Thanks
