### ISSUE TITLE
September 2022 Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2190]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

Blog analytics are ready for your review: https://github.com/ONRR/blog-nrrd/wiki/Analytics

Here's a copy of the excel for you to cross-reference
[Blog_Analytics_September22.xlsx](https://github.com/ONRR/nrrd/files/9699127/Blog_Analytics_September22.xlsx)

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good
