### ISSUE TITLE
FY 22 Analytics - NRRD

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2199]

**Comment by cthomasONRR** [comment]
@Maroyafaied

FY 22 is ready for your review: https://github.com/ONRR/nrrd/wiki/Analytics

Link to word doc to help with reviewing: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Analytics%20FY%2022.docx?d=w6622e54769a74040b0eac3161d99091e&csf=1&web=1&e=l1DiTG

(Sending this to you since Lindsay is out of the office next week.)

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great. Thanks
