### ISSUE TITLE
Review & update onboarding checklist 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2201]
https://github.com/ONRR/nrrd/wiki/Onboarding-checklist

**Comment by cthomasONRR** [comment]
I can create a new section about the CMS

**Comment by cthomasONRR** [comment]
I checked to make sure all links work, updated the humans.txt, and added a new section for the CMS.

**Comment by cthomasONRR** [comment]
I noticed that the design checklist was NRRD only, so I added a bunch of links to onrr.gov design stuff. Please help me add more onrr.gov info to the design checklist. https://github.com/ONRR/nrrd/wiki/Onboarding-checklist#design-checklist

**Comment by Maroyafaied** [comment]
There's a design folder in Teams for onrr.gov , it should have style tiles and other design stuff we could maybe add.  Or we could just add the link the folder and let them brows on their own since we don't have a design section in the wiki for onrr.gov. 
https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design?csf=1&web=1&e=KVSp1z

**Comment by cthomasONRR** [comment]
Thanks, I added that plus a link to the axure cloud folder

**Comment by lpgoldstein** [comment]
This will be a good test of teaching someone about the new onrr.gov site. I'm sure we will need to do some updates as she works through the checklist.
