### ISSUE TITLE
Meet 1:1 with interns 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2207]
@Baymatt @Isabelh99 I would like to meet with you individually to discuss your goals and work assignments. Please let me know what days/times do you have available either this week or next week for 30 minutes. Thanks

**Comment by Isabelh99** [comment]
This week I have available:
Thursday: after 11:15am & before 12:30pm ET
Friday after 2pm ET
Saturday 11am- 1pm

Next Week:
After the interns meeting.
Wednesday after 2pm ET
Friday after 2pm ET

**Comment by Maroyafaied** [comment]
@Isabelh99 Thank you for responding, since Matt won't be able to attend the next intern meeting we can meet 1:1 at that same time. Does that work?
