### ISSUE TITLE
Write up on how ONRR implements OPEN DATA act 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2211]

**Comment by lpgoldstein** [comment]
https://blog-nrrd.doi.gov/beyond-open-data/

**Comment by Maroyafaied** [comment]
@lpgoldstein this is ready for your review https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/OPEN%20Act%20-%20ONRR%27s%20Implementation%20.docx?d=w97faf88dc3f949958f100827a10de386&csf=1&web=1&e=waJFos

**Comment by Maroyafaied** [comment]
This has been submitted to the GAO
