### ISSUE TITLE
Get access to our shared mailboxes 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2213]
@eelzi-ONRR  The team has two shared mailboxes that we monitor for any requests or questions we receive. The onrrweb@onrr.gov mailbox is for the onrr.gov website and the nrrd@onrr.gov mailbox is for the revenuedata.doi.gov website. Please follow the instructions below to get access to both. 

Here are instructions on how to add our shared inboxes (onrrweb@onrr.gov and nrrd@onrr.gov) to Outlook desktop
a.     Open Outlook.
b.     Choose the File tab in the ribbon.
c.     Choose Account Settings, then select Account Settings from the menu.
d.     Select the Email tab.
e.     Make sure the correct account is highlighted (your own onrr.gov email acct), then choose Change.
f.      Choose More Settings > Advanced > Add.
g.     Type the shared email address, onrrweb@onrr.gov and nrrd@onrr.gov
h.     Choose OK > OK.
i.       Choose Next > Finish > Close. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/a62b6b0e-0d10-4e7e-bf60-be0a5dfeaa65)

**Comment by eelzi-ONRR** [comment]
These instructions worked to add the mailboxes to my Outlook, but Maroya had to ask IT to add me to the mailboxes. Waiting on IT to respond
