### ISSUE TITLE
Complete transportation subsidy training and application

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/nrrd#2216]
Erin will complete the training and application, then let Maroya know it's ready to approve. Maroya will need to create an account if she doesn't already have one.

[Transportation Subsidy Benefit Program](https://onrresource/Employee-Resources/Transportation-Subsidy-Benefit-Program/)

**Comment by cthomasONRR** [comment]
For the EcoPass, ONRR Resource has some information:
https://onrresource/Employee-Resources/Benefits/Benefit-Programs/
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/8b527a6b-0b6d-41e0-9f23-c404fdc89ee3)

**Comment by eelzi-ONRR** [comment]
I talked with the contact for this - ends up the internal site is outdated and we no longer can get Ecopasses. And the transportation subsidy does not apply to RTD single passes either - we can only use the transportation subsidy program to arrange for ride share. Closing this since I'm not interested in ride share.
