### ISSUE TITLE
Update OGOR B Wiki instructions 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2221]
Rewrite the steps in the pic below. New folder is static>downloads>OGOR-B

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/2a10e7b9-e566-4146-822e-0189aad591d1)

**Comment by Maroyafaied** [comment]
@cthomasONRR I've updated the instructions, I'll leave the issue open until you upload the new data with the instructions to see if any steps were not clear. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied I understood your instructions, and was able to easily follow them to upload OGOR-B. I think this issue is good to close.
