### ISSUE TITLE
Correct state in January 2017 monthly disbursements

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2239]
Correct state from AC to RI in January 2017 monthly disbursements

**Comment by Maroyafaied** [comment]
@lpgoldstein can you please double check if this was corrected in the file on the live site ?

**Comment by lpgoldstein** [comment]
@Maroyafaied Sorry I forgot to mention it on Friday. It is no longer corrected. I can do that in the next release.
