### ISSUE TITLE
October Analytics - NRRD

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2257]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

The NRRD analytics are ready for your review:
https://github.com/ONRR/nrrd/wiki/Analytics

Check sheet: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Check%20Sheets/Analytics%20October%2022.docx?d=w6ff1bbc7f74345be9d940602172dd133&csf=1&web=1&e=GDmasL

**Comment by lpgoldstein** [comment]
@cthomasONRR Looks good!
