### ISSUE TITLE
Access to  Hasura 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2269]

**Comment by Maroyafaied** [comment]
Email from cloud.gov:

Anyone who has a .gov or a .mil email address can signup for an account here: https://cloud.gov/docs/orgs-spaces/roles/#make-sure-the-user-has-a-cloudgov-account
 
However, to add new users to your organization, you need to have the Org Manager role. There are existing org managers for your organization who would be able to add you or other users to your organization. 

Below I've attached a link regarding how to add another team member and provide them with access. 

https://cloud.gov/docs/orgs-spaces/roles/#managing-roles-via-the-dashboard

We currently do not have a cloud gov dashboard for S3 browsing. However, you can use command line tools to view your s3 contents. However you can interact with your s3 bucket per what is contained in the article linked below.

https://cloud.gov/docs/services/s3/#interacting-with-your-s3-bucket-from-outside-cloudgov

**Comment by greensomes** [comment]
The username and password for Hasura instances are stored in environment variables vi cf cli. To retrieve the Hasura credentials for the hasura-sandbox app, for example, take the following steps:

1. Target the dev space: `cf target -s dev`
2. Display environment variables: `cf env hasura-sandbox`
3. See `HASURA_GRAPHQL_ADMIN_SECRET` under the User-provided section of the output.
