### ISSUE TITLE
Finalize interview questions and notes template 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2272]

**Comment by Maroyafaied** [comment]
@lpgoldstein please review the interview questions. I'll create a note template once the questions are finalized. https://doimspp-my.sharepoint.com/:w:/g/personal/faiedm_mms_gov/EefWEXijmBNPm8G0AXQ0XcIBRCShxSp94QOYFI_-UL6ghQ?email=Lindsay.Goldstein%40onrr.gov&e=Ey8no4

**Comment by lpgoldstein** [comment]
@Maroyafaied These are great questions!

**Comment by Maroyafaied** [comment]
I sent an email to the interview panel with the notes template and scoring sheet. We are meeting tomorrow to discuss the process.
