### ISSUE TITLE
Create cloud.gov account 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2276]

**Comment by cthomasONRR** [comment]
I got my account established and logged in: 
![image](https://user-images.githubusercontent.com/72526208/200361417-ae239245-168b-40d9-b5b3-4dac762c9cd4.png)

**Comment by eelzi-ONRR** [comment]
My account is created and I'm able to login

**Comment by R-mohansai** [comment]
I got my account created and able to login.

**Comment by lpgoldstein** [comment]
Same!
