### ISSUE TITLE
Revise & test RRM's spreadsheet with adding Indian/Federal to roles 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2294]

**Comment by Maroyafaied** [comment]
[Contacts Spreadsheet - To Update.xlsx](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Contacts%20Spreadsheet%20-%20To%20Update.xlsx?d=wfe85082c23bf4aa88cd0c716c3d4a48b&csf=1&web=1)

**Comment by cthomasONRR** [comment]
I tried to add the words "Federal" and "Indian" to the Primary Contact and Supervisor headers. When I added the words, the headers disappeared in dev. 

![image](https://user-images.githubusercontent.com/72526208/206732688-c020aa80-a8e5-4d21-af19-cdffffa8b46a.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR can you send a screenshot of the excel sheet or the link of it to see how you did it?

**Comment by cthomasONRR** [comment]
@Maroyafaied I manually added it to one entry within the CMS. We can work on it on Monday.

**Comment by Maroyafaied** [comment]
@cthomasONRR Ok. Try typing it as "Primary Contact Federal". If it doesn't work, we'll touchbase on Monday.

**Comment by cthomasONRR** [comment]
@Maroyafaied That worked! 
![image](https://user-images.githubusercontent.com/72526208/206738543-85fbb1bb-28a3-461e-9fe4-d3ce5c8c667b.png)

**Comment by cthomasONRR** [comment]
@lpgoldstein Royalty contacts are updated and ready for review: https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

I'm about to start working on the Onshore Production.

**Comment by cthomasONRR** [comment]
@lpgoldstein Ok Onshore Production contacts are now updated too: 
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by lpgoldstein** [comment]
@cthomasONRR royalty looks good

**Comment by lpgoldstein** [comment]
@cthomasONRR onshore looks good as well

**Comment by cthomasONRR** [comment]
@lpgoldstein Yay! Do we need to tag Jessica to review?
