### ISSUE TITLE
Update fiscal year to 2022 in revenue & disbursements download page 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2298]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Is this what we did last week to teach me how to open pull requests? If so, can we close this ticket?

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Yes, we already completed this and it can be closed.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Yes, we already completed this and it can be closed.
