### ISSUE TITLE
Configure settings in new DOI ONRR test github repo 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2301]

**Comment by lpgoldstein** [comment]
https://github.com/organizations/ONRR/settings/domains

**Comment by Maroyafaied** [comment]
We were able to get onrr.gov verified with the BSEE web manager and the NRRD site verified with DOI. @lpgoldstein go ahead and close this issue if we are done with all the settings configurations. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/59bec629-adc0-41e0-bff8-7a0130004e9c)

**Comment by lpgoldstein** [comment]
@Maroyafaied verifying our domains was the last step!
