### ISSUE TITLE
Respond to Human of Public Service nomination 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2307]
Good morning Maroya,

Congratulations!

You have been nominated to be featured on Humans of Public Service. Our purpose is to humanize the perception of government by celebrating the spirit of people who work in public service. We formally launched in May and would love to share your story. 

To participate please complete this form and reply to this email with one to three clear pictures of yourself. Below are examples of our content and a preview of the questions in the form. 

Examples

LinkedIn and Instagram 

Questions

Tell us about who you are and what you do. 
What inspired you to join the public service? 
What has been the highlight of your public service career so far? 
Thank you for serving your community, feel free to follow up with any questions and we look forward to hearing from you

**Comment by Maroyafaied** [comment]
@lpgoldstein please review https://doimspp-my.sharepoint.com/personal/faiedm_mms_gov/_layouts/15/doc.aspx?sourcedoc={837d78d3-f573-46b9-8e6a-8fc38c7b6276}&action=edit

**Comment by lpgoldstein** [comment]
@Maroyafaied I commented  in the document. Looks great!
