### ISSUE TITLE
Break up OGOR B file into two files

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2309]
Have one file as historical that won't get updated.

**Comment by Maroyafaied** [comment]
I sent the DORC team an email with the idea and will wait for their response before taking the following approach:
- The first file would provide data from January 2003 to December 2011. 
-The second file would provide data from January 2012 till the most recent month update.  
-We wouldn't be making any monthly updates to the first file and we would update the second file as we receive the data from the DORC Team.  
-Once the year 2012 data is not longer being updated thenwe would move 2012 data to the first file.

**Comment by Maroyafaied** [comment]
@cthomasONRR We met with the DORC team and they offered to give us updated OGOR B and monthly production files starting with January 2012 each month so it's easier to update. This is a great solution and makes updates much easier since we would be uploading the OGOR B file that DORC sends as is.  We agreed that we will start this new process in Feb so moving this issue

**Comment by Maroyafaied** [comment]
@cthomasONRR if its ok with you I'll close this issue since we have a plan with the DORC team and I'll create another issue for creating the file that will be "historical",

**Comment by cthomasONRR** [comment]
@Maroyafaied Sounds good!
