### ISSUE TITLE
Add accessibility page on NRRD 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2335]

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I set up a meeting for us to do this today. We will need the accessibility page put in markdown, it's easiest to do this in a word document then copy and paste when we're doing the PR.  Here's an example of the VDP page put in markdown in a word doc, let me know if you have questions on putting it in markdown.  https://doimspp.sharepoint.com/:w:/s/NRRD/EbeYeRLUYMVAs9avQQIP8OUB8cJdK7scig4JsgPz_ZE_Ew?email=Maroya.Faied%40onrr.gov&e=PvAr4Z


Notes for the PR:
Footer location: src/components/content-partials/footer.mdx
Page location: src/pages/ (create new page)

**Comment by eelzi-ONRR** [comment]
Completed via PR #2349
