### ISSUE TITLE
Get approval to speak at The Partnership for Public Service - Implementing Agile Digital Transformation No Matter the Budget workshop

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2338]
The Partnership for Public Service, in collaboration with Slalom and Fearless, is hosting a four-part series of in-person workshops on Agile Government and Digital Transformation to begin late-January 2023 at our Partnership offices in Washington DC. We are inspired by your agile practices and innovative modernization work, and hope you’ll be willing to join us to share your story. We hope you’ll speak at our third session, Implementing Agile Digital Transformation No Matter the Budget, for a fireside-style chat alongside Robert Wood (CMS CISO).

Our sessions:

Jan 27, 2023: Getting Started on Your Digital Transformation Journey 
Feb 17: Adopting Digital Transformation for Internal Infrastructure
Feb 24: Implementing Agile Digital Transformation No Matter the Budget 
Mar 10: Digital Transformation: Making it Happen at Your Agency   
The audience, which we are capping at 30, includes program managers and career employees around the GS 14–15 level, and potentially some SES who work on a variety of digital-related initiatives. The workshop will last a total of 90 minutes and we anticipate your time commitment will be ~30 minutes. We are aiming for a start time of 10:00 am ET

This engagement will have no press and is free for attendees.

**Comment by Maroyafaied** [comment]
@lpgoldstein I've requested approval but I haven't heard back. I will also move this to next sprint since Nathan is out this week.

**Comment by Maroyafaied** [comment]
@lpgoldstein we have approval from the ethics counselor and Howard.
