### ISSUE TITLE
Explore data: Build GOMESA chart

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#234]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/49fb359c-652e-4214-8353-d6fd44795c5b)

**Comment by jennmalcolm** [comment]
We should do more user research on the design before building.

**Comment by mcharg** [comment]
Closing, since we won't know if we want to build one until we do #291.

**Comment by mcharg** [comment]
Good candidate for clickable circle chart.
