### ISSUE TITLE
Meet 1:1 - UX internship 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2340]
@eelzi-ONRR @Isabelh99 please coordinate a time to meet 1:1 to talk about Isabel's interests and how Erin can help mentoring. Thanks

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Due to holiday schedules, @Isabelh99 and I decided we'll touch base on Jan 3, and set a time that week to meet.

**Comment by eelzi-ONRR** [comment]
We met today and will continue to meet once a week. Isabel will be developing and executing a user research project for the pricing tables. I've shared with her the ONRR UX Strategy, the Design Review for the Pricing page, and some previous research projects to help her start planning.
