### ISSUE TITLE
nrrd monthly analytics

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2345]

**Comment by cthomasONRR** [comment]
@lpgoldstein 
NRRD December analytics are ready for your review:
https://github.com/ONRR/nrrd/wiki/Analytics

Link to check sheet (you should have an email allowing you access to the doc): 
https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Analytics%20December%2022.docx?d=wc32556cd929848c2bc97b9adeccb8978&csf=1&web=1&e=YSR8Yp

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good!
