### ISSUE TITLE
Enhance the wiki instructions for creating branches for NRRD

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/nrrd#2350]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied These instructions are ready for review. I want to add another screenshot or two near the end of the instructions, but those steps only show when you're making changes. So I'll wait until the next time I'm making chages to a branch in NRRD to get those shots. 
https://github.com/ONRR/nrrd/wiki/Creating-a-new-branch

**Comment by Maroyafaied** [comment]
@eelzi-ONRR this looks great.  We should be doing a nrrd release next week so just remind me and I can grab those screenshots for you.
