### ISSUE TITLE
Buildpack updates

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2358]
Hi cloud.gov user,

cloud.gov frequently updates the programming language buildpacks available to
our customers. Buildpack updates include programming language updates and
often include security fixes.

We recently updated buildpacks in use by your applications. You should
restage or redeploy your applications to take advantage of the update.

A rolling restage operation is the quickest way to upgrade without incurring
downtime. You may still want to leverage your deployment infrastructure to
perform the upgrade if you have compliance requirements for redeployment operations.

You can restage your applications by opening the command line and entering
the following commands:

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-nrrd

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-blog-nrrd

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-onrr-cms

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling hasura-sandbox-interface

For more information about the buildpack update(s), please see the following release notes:

  go_buildpack v1.10.2: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fgo-buildpack%2Freleases%2Ftag%2Fv1.10.2&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=SRFhIGPratWIxjE23%2FdmLMQwFVS0FVTgkT2TV08nBUs%3D&reserved=0

  staticfile_buildpack v1.5.36: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fstaticfile-buildpack%2Freleases%2Ftag%2Fv1.5.36&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=SnQjFy1IB1xMzoAaafLMbBQ1c5KBXm4diqhxmDgXVog%3D&reserved=0

  nodejs_buildpack v1.8.4: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnodejs-buildpack%2Freleases%2Ftag%2Fv1.8.4&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=DgXLqoBYM5%2BHhk6BIqj3PgD2rtdjSdctezpoXpK4OWg%3D&reserved=0

  python_buildpack v1.8.3: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fpython-buildpack%2Freleases%2Ftag%2Fv1.8.3&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=a26Iz567TPqQnzM665iLdiAl1iBX3jtaKNXl1KmBNmU%3D&reserved=0

  java_buildpack v4.53: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fjava-buildpack%2Freleases%2Ftag%2Fv4.53&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=PZYNWBACfIrpEdfFSZ3LQFWFdhIr80aJ9ZjKV6jLjdU%3D&reserved=0

  ruby_buildpack v1.9.0: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fruby-buildpack%2Freleases%2Ftag%2Fv1.9.0&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=C8zWFwTnJdN4EGr5L58ThVHeHA5birqND2LY1eYbPME%3D&reserved=0

  php_buildpack v4.5.0: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fphp-buildpack%2Freleases%2Ftag%2Fv4.5.0&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767256115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=O%2FaePW7rhZIY33emf2poM5%2BBm3wCgf%2BVaR3CIAsZdaI%3D&reserved=0

  dotnet_core_buildpack v2.4.5: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fdotnet-core-buildpack%2Freleases%2Ftag%2Fv2.4.5&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767412344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=YKRfSPCZ7bhZYNpcdQRVyA6zNAiT36Y0JorgkfucLa0%3D&reserved=0

  r_buildpack v1.1.36: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fr-buildpack%2Freleases%2Ftag%2Fv1.1.36&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767412344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=wTobrBIki6UeAr9lGrct8WsIIADC%2FJ1AVBi2G22G8aM%3D&reserved=0

  binary_buildpack v1.1.0: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fbinary-buildpack%2Freleases%2Ftag%2Fv1.1.0&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767412344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=2NCMHNMpKzFAIAsfOh%2FBG0qutIMtPVgxKCMTvBkfi7s%3D&reserved=0

For more information on keeping your application updated and secure, see:
https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.gov%2Fdocs%2Fgetting-started%2Fapp-maintenance%2F&data=05%7C01%7Cmaroya.faied%40onrr.gov%7Cb7d6ab8c85aa45b8a77b08daf02e9f3e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086381767412344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=K4nAGJ5lK621FT0igBSfCQ5E3I3x9LHv1xWKDcrn0No%3D&reserved=0

If you have questions, you can email us at cloud-gov-support@gsa.gov.

**Comment by Maroyafaied** [comment]
@greensomes I emailed cloud.gov support and cc'd you regarding the memory error you are receiving.

**Comment by greensomes** [comment]
Restating `dev-onrr-cms` game memory limit errors. This was resolved by scaling app memory down to 1G.
