### ISSUE TITLE
Schedule & Conduct Interviews - IT Specialist

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2362]
- [ ]  Form a panel

- [ ] Develop interview questions

- [ ] Schedule & Conduct Interviews

**Comment by cthomasONRR** [comment]
@Maroyafaied 

I compiled some interview questions [here](https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/GS-13%20Developer%20Interview%20Questions.docx?d=w314c38b8d25940cd8642a42ba4297c78&csf=1&web=1&e=NDLmfm). There's probably a few too many to fit into a 1-hr interview, but we can remove and expand some if needed. 

Let me know what you think!

**Comment by Maroyafaied** [comment]
We interviewed 5 candidates and the panel agreed on a top candidate.
