### ISSUE TITLE
Complete GitHub Training in DOI Talent

### ISSUE THREAD

**Issue by AlexandracmONRR** [ONRR/nrrd#2371]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I added this issue to this sprint. Here is the link to the training https://doitalent.ibc.doi.gov/enrol/index.php?id=20144 and here is the link to request a license after you have completed the training https://apps.gov.powerapps.us/play/36a8a424-404e-45e6-8577-0c886171a2ce?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494
