### ISSUE TITLE
Research and select a new text editor

### ISSUE THREAD

**Issue by AlexandracmONRR** [ONRR/nrrd#2372]
- Visual Studio
- Sublime
- Notepad++
- More...

**Comment by greensomes** [comment]
The code editor of my choice the last few years has been Visual Studio Code. It's nice because it's relatively lightweight, has great community support, and integrates with git repositories very well. 

I'm not sure if this is supported by IT at ONRR, but it's worth checking on.

**Comment by eelzi-ONRR** [comment]
I second Visual Studio Code. It's what I have used previously so I already had IT install it on my machine. So, yes - IT supports it.

**Comment by AlexandracmONRR** [comment]
As a part of the "Non-Core Software Request" the software drop down includes Microsoft Visual Studio 2022 as well as several other versions of it - just to bolster Erin's point that IT supports it!

**Comment by greensomes** [comment]
Just a note to state that Visual Studio 2022 is a different product than Visual Studio Code. VS 2022 can definitely do the trick, but is a bit more cumbersome to use. VS Code is much more lightweight similar to Atom, but sounds like it doesn't have the same support as VS 2022.

Separately, among other plugins available, there is a VS Code plugin for circleci that I just installed. It's pretty nifty.
