### ISSUE TITLE
Install VS Code 2022

### ISSUE THREAD

**Issue by AlexandracmONRR** [ONRR/nrrd#2377]
Download VS Code installer using this link: 
https://code.visualstudio.com/docs/?dv=win64user

This install request can be submitted to IT as a Non-Core Software Request.

**Comment by cthomasONRR** [comment]
I was able to install without IT approvals. I still made the non-core request, but it's definitely on my computer and working.

**Comment by cthomasONRR** [comment]
FYI:
![image](https://user-images.githubusercontent.com/72526208/214400632-c4341955-ca7d-4533-bf47-e6a381249899.png)

**Comment by lpgoldstein** [comment]
Also downloaded and put in a request.

**Comment by Maroyafaied** [comment]
Installed.
