### ISSUE TITLE
Add blog to cloud.gov

### ISSUE THREAD

**Issue by master12** [ONRR/nrrd#238]

**Comment by mojobnichols** [comment]
@mcharg    Is this fixed now?

**Comment by mcharg** [comment]
@mojobnichols I think we still need to work out linking to the new blog from the beta site and redirecting the urls from the old blog posts to the new url.

**Comment by mcharg** [comment]
Created a new issue for the remaining tasks.
https://github.com/ONRR/blog-nrrd/issues/9
