### ISSUE TITLE
Review and publish remote design studio blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#241]

**Comment by lpgoldstein** [comment]
@mcharg this looks good to me. Do we want to add any pictures of our different sketches?

**Comment by mcharg** [comment]
@lpgoldstein Oh yeah, I forgot I was going to add images.  Thanks for the reminder!

**Comment by mcharg** [comment]
@lpgoldstein I added images.

**Comment by lpgoldstein** [comment]
So I can find it again! 
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Blog/Remote%20Design%20Studio.docx?d=wa9f71c28927243ea8f9de7a10abd1879&csf=1&e=irsB7t

**Comment by lpgoldstein** [comment]
@mcharg looks good!

**Comment by jennmalcolm** [comment]
Looks good. I added my comments @mcharg.
