### ISSUE TITLE
Explore Data: Revenue Detail Cards: Ownership

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#25]
Design and add ownership map and percentage to revenue detail cards.

@lpgoldstein will be doing design.

Something like:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ab530e3f-2ae3-4e0c-b0bf-79f5e50ade77)

**Comment by lpgoldstein** [comment]
@mcharg what do you think? We can update once we have updated colors/maps. ![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/9bfe21fb-cdb3-4006-9fd0-6482201b0feb)

**Comment by mcharg** [comment]
We may need to add some sort of explanation about why ownership is important or at least link to a glossary or How It Works, since all that content at the top of the current Explore Data page will be gone and this will be the first explanation of ownership.

This is the content that will be gone:
![image](https://user-images.githubusercontent.com/38465926/72266651-cb71ac80-35ec-11ea-9f50-6ab93daff35e.png)

**Comment by mcharg** [comment]
Figuring out where we get the ownership data and how we can sustainably update it should be part of this issue.

**Comment by jennmalcolm** [comment]
This issue will be for getting the federal percentage on the cards. We will have another issue for researching the source of this data and determining what to include. and another for the map (#121).

**Comment by mcharg** [comment]
@alenahuang is looking at where ownership percentage should display on the card as part of #29.

**Comment by mcharg** [comment]
Thoughts on putting ownership in the card headers?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2ad8dbd2-9f05-45b4-be23-27c1d1eee79f)

**Comment by jennmalcolm** [comment]
I think it works well in the header to provide the context for the rest of the numbers in the cards.

**Comment by mcharg** [comment]
It's going in the card headers.
