### ISSUE TITLE
Fix About Page issues on cloud.gov

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#254]
This relates to issue #243 

- [x] links don't work under "understand natural resource management on federal land" - the anchor links on how it works don't scroll down to the anchor
- [x] Remove How it works button/link
- [x] agency logos 
- [x] links in agency descriptions don't work 
- [x] glossary definitions don't work 
- [x] links under the History section don't work (EITI and archive link)
- [x] Agency names should be an H level (h4?)

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/77571560-2f3d0f00-6e93-11ea-88b3-ce04d38addbc.png)

![image](https://user-images.githubusercontent.com/40175688/77571627-4d0a7400-6e93-11ea-866c-5377f6c6b427.png)

![image](https://user-images.githubusercontent.com/40175688/77571724-6dd2c980-6e93-11ea-9454-2082fcb24195.png)

![image](https://user-images.githubusercontent.com/40175688/77571787-893dd480-6e93-11ea-87c8-f9e260e92f6f.png)

**Comment by mcharg** [comment]
- [ ] The bureau names should be h3s, but they're not.
![image](https://user-images.githubusercontent.com/38465926/77577160-ae8b0c80-6eac-11ea-9334-1b147fa9e093.png)

**Comment by mcharg** [comment]
- [ ] The h2s should add the green bar.
![image](https://user-images.githubusercontent.com/38465926/77577337-f316a800-6eac-11ea-863e-d827ef23fd79.png)

**Comment by master12** [comment]
@Maroyafaied Fixed

[Preview](https://dev-nrrd.app.cloud.gov/about)

**Comment by mcharg** [comment]
@master12 The links that go to anchors on the How It Works page aren't scrolling down the page.

**Comment by Maroyafaied** [comment]
@master12 missing parentheses at the end 
![image](https://user-images.githubusercontent.com/40175688/80009206-fdb16680-8485-11ea-9982-f607ea6bf034.png)
