### ISSUE TITLE
Fix How it Works main page on cloud.gov

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#255]
This relates to issue #243 

[How it works main page](https://dev-nrrd.app.cloud.gov/how-it-works)
- [ ] white spacing between the light blue and dark blue boxes in the first section seem off
[jk] No idea what you want to change

- [x]  might be nice to have more spacing in between sections
- [x] more space between last body/content line and footer (seen on all How it Works pages)
- [x] links say "Learn more about economic impact" rather "Coal" "Renewable"... (under the production process)

**Comment by master12** [comment]
@lpgoldstein Updated dev with changes also see question above

[preview](https://dev-nrrd.app.cloud.gov/how-it-works)

**Comment by lpgoldstein** [comment]
@master12 Thank you! Here is a screenshot that shows where the spacing is off between the boxes 
![image](https://user-images.githubusercontent.com/39419003/80012042-b386b000-849a-11ea-91a2-705351486456.png)
