### ISSUE TITLE
Fix in How it works individual pages 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#256]
This relates to issue #243

[How it works - federal laws](https://dev-nrrd.app.cloud.gov/how-it-works/federal-laws/)
- [x] remove '>' before "not specified" in Indian Mineral Leasing Act information line

[How it works - Native American revenue](https://dev-nrrd.app.cloud.gov/how-it-works/native-american-revenue/)
- [x]  add more spacing below the revenue collection table

[How It Works / Onshore Oil and Gas](https://dev-nrrd.app.cloud.gov/how-it-works/onshore-oil-gas/)
- [ ]  left side dropdown has bolded text? not sure if this is supposed to be
[JK] Bold matches current site?

[How It Works / Coal](https://dev-nrrd.app.cloud.gov/how-it-works/coal)
- [x] no header to indicate it's the "Coal" page

[How It Works / Nonenergy Minerals](https://dev-nrrd.app.cloud.gov/how-it-works/minerals)
- [x] the white spacing is not consistent to the other "How It Works" pages
[JK] No idea what you want me to do?

[How It Works / Onshore Renewable](https://dev-nrrd.app.cloud.gov/how-it-works/onshore-renewables)
- [x] should have white space on the bottom of the top section like the other pages to break up the sections
[jk] Didnt do it that way because due to the background image for this it looks weird but made the space so you can see

[How It Works / Offshore Renewables](https://dev-nrrd.app.cloud.gov/how-it-works/offshore-renewables/)
- [x] no background graphic like other pages (?)

[How It Works / Revenues](https://dev-nrrd.app.cloud.gov/how-it-works/revenues)
- [ ] the tables don't line up for each section (see bonuses), some green lines do not extend all the way; overall, the table is very confusing to look at because the sections of text seem to be floating
[jk] No idea what to do?

[How It Works / Audits](https://dev-nrrd.app.cloud.gov/how-it-works/audits-and-assurances)
- [x] two download icons (second one is not consistent)

**Comment by master12** [comment]
@lpgoldstein Please review in the dev branch here is the link. Also see comments above and let me know when you want to chat about what I dont understand

[Preview](dev-nrrd.app.cloud.gov)
