### ISSUE TITLE
Fix download page issues on cloud.gov

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#257]
This relates to issue #243 

- [ ] The "contact us" section does not show as it does on the live site

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/77572668-ff8f0680-6e94-11ea-93b4-8bb8ea7a7c34.png)

![image](https://user-images.githubusercontent.com/40175688/77572639-f30aae00-6e94-11ea-96f8-5da79d179e17.png)

**Comment by master12** [comment]
@Maroyafaied Please review in the dev branch, here is the link
[Preview](dev-nrrd.app.cloud.gov)

**Comment by Maroyafaied** [comment]
@master12 the preview link is not working for me.

**Comment by jennmalcolm** [comment]
Here's the link @Maroyafaied https://dev-nrrd.app.cloud.gov/

**Comment by Maroyafaied** [comment]
@master12 it looks good, I don't see where the pull request is to approve it.
