### ISSUE TITLE
Q/A test homepage on cloud.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#260]

**Comment by lpgoldstein** [comment]
check list for data items 
Revenue 
- [ ] fiscal year
- [ ] calendar year
- [ ] monthly
- [ ] trends
- [ ] links

Disbursements
- [ ] fiscal year
- [ ] monthly
- [ ] trends
- [ ] links

Production
- [ ] fiscal year oil
- [ ] fiscal year gas
- [ ] fiscal year coal
- [ ] calendar year oil
- [ ] calendar year gas
- [ ] calendar year coal
- [ ] monthly oil
- [ ] monthly gas
- [ ] monthly coal
- [ ] links

- [ ] what's new
- [ ] footer

**Comment by lpgoldstein** [comment]
revenue by company link is gone

**Comment by lpgoldstein** [comment]
reclamation link broken  Reclamation Fund disbursements
![image](https://user-images.githubusercontent.com/39419003/78384534-550b9780-75a8-11ea-8a8d-6923f9dbe46c.png)

**Comment by lpgoldstein** [comment]
production numbers are all off - not sure how they are being calculated

**Comment by lpgoldstein** [comment]
@Maroyafaied if you want to take a second look at the numbers that would be great. Mojo figured out the production numbers and now the rounding just is a $1 or 2 off from the current page - but only on the production numbers.

**Comment by mcharg** [comment]
Should we have a production by location link that brings up oil by default?  I think leaving it out may make users think we don't have that for production.

![image](https://user-images.githubusercontent.com/38465926/78675860-a8852a80-78b3-11ea-86fb-23ffe4de1e38.png)

**Comment by mcharg** [comment]
Created #271 to address moving what's new up into the open space to the right of the intro content.

**Comment by Maroyafaied** [comment]
All the source file links are not there (under bar charts, under trendlines, and FY so far)

**Comment by Maroyafaied** [comment]
Add the word "Total" before Revenue , Disbursement and Production data . 
![image](https://user-images.githubusercontent.com/40175688/78685888-973a1f00-78af-11ea-93c7-00c828ebd869.png)
![image](https://user-images.githubusercontent.com/40175688/78685913-a15c1d80-78af-11ea-9175-3a0227af29f7.png)

**Comment by Maroyafaied** [comment]
units are missing for the commodities in the production tab on the horizontal max line 
![image](https://user-images.githubusercontent.com/40175688/78686274-14659400-78b0-11ea-8d50-d9322d916f94.png)
![image](https://user-images.githubusercontent.com/40175688/78686315-1fb8bf80-78b0-11ea-900a-d2f04b372e96.png)

**Comment by mcharg** [comment]
Created #277 to fix bugs.
