### ISSUE TITLE
Q/A Test Explore Data on cloud.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#261]

**Comment by mcharg** [comment]
Things to test:
- [ ] Revenue data
- [ ] Revenue cards
- [ ] Map functionality

**Comment by Maroyafaied** [comment]
It's not clear if you are viewing FY or CY data on cards on top of the map like it is on the bottom cards. 
![image](https://user-images.githubusercontent.com/40175688/78074375-e3410d00-735f-11ea-81f6-f4468bb64fd0.png)
![image](https://user-images.githubusercontent.com/40175688/78074404-edfba200-735f-11ea-83de-8c10bb034ba5.png)

**Comment by Maroyafaied** [comment]
county cards still appear after I select the view map as state, I expected them to disappear when I changed the view selection. 
![image](https://user-images.githubusercontent.com/40175688/78074947-e38dd800-7360-11ea-89f0-95759ad1b969.png)

**Comment by Maroyafaied** [comment]
Offshore data does not seem to work. 
![image](https://user-images.githubusercontent.com/40175688/78075600-1389ab00-7362-11ea-8c53-0d7a65a7fa27.png)

**Comment by mojobnichols** [comment]
> county cards still appear after I select the view map as state, I expected them to disappear when I changed the view selection.
> ![image](https://user-images.githubusercontent.com/40175688/78074947-e38dd800-7360-11ea-89f0-95759ad1b969.png)

I would think it would be useful for some people to open a state card, then swithc to county and open  some counties in that state.    So have cards be NM,  Taos, Rio Arriba,

**Comment by mojobnichols** [comment]
> Offshore data does not seem to work.
> ![image](https://user-images.githubusercontent.com/40175688/78075600-1389ab00-7362-11ea-8c53-0d7a65a7fa27.png)

I checked my  local dev and it worked.   I had performed an npm audit fix so I committed that and it seems to be working.    I doubt it was simple the audit fix that corrected it but maybe.

**Comment by mcharg** [comment]
@Maroyafaied It's as designed to keep selected cards when you toggle between state and county, so users can compare counties to the whole state or nationwide.

**Comment by Maroyafaied** [comment]
@mojobnichols @mcharg , Just for consistency, I noticed for the revenue by type circle chart, the nationwide card has a category titled just "other", but the state cards has that category titled "other revenues".   Just a thought for consistency, otherwise data is correct.
![image](https://user-images.githubusercontent.com/40175688/78151896-55643100-73f6-11ea-8f59-0e55b33614a4.png)

**Comment by mcharg** [comment]
The reset button on the map shrinks it and puts it in the corner instead of resetting to the default size.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/aa943973-95ad-4e12-9c44-e06acff846dd)

**Comment by mcharg** [comment]
Counties display multiple times in the search.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8e801c0d-109e-4279-a524-b1ff4ea546dc)

**Comment by mcharg** [comment]
@Maroyafaied Not sure if you saw @mojobnichols response about the circle charts.

"Yeah the circle chart has option max circles it the combines any remaining points into other. So it's quite possible to have rents, ..., Other revenues, other. I'm happy to use a different description. Or maybe a better description for other revenues."

**Comment by Maroyafaied** [comment]
@mcharg I didn't see it, thanks! I think we should just use one consistent label for any remaining labels, just "other" is good.

**Comment by Maroyafaied** [comment]
@mojobnichols I'm still not able to get offshore data to load.

**Comment by mojobnichols** [comment]
> @mojobnichols I'm still not able to get offshore data to load.

Try control-f5 in browser.

**Comment by mcharg** [comment]
Added #273 for map zooming issues.

**Comment by mcharg** [comment]
Created #274 for county search issue.

**Comment by mcharg** [comment]
Created #275 for small bugs.
