### ISSUE TITLE
Explore Data: Hook up commodity drop-down for revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#262]
Hook up data to the drop-down.

**Comment by mojobnichols** [comment]
I put this directly into dev so there is no PR.   If actually had a lot to do with the other bugs from this morning.   So I increased estimate to cover the other bugs as well. 

Commodity dropdown for revenue should work for Revenue

**Comment by mcharg** [comment]
@mojobnichols It's not updating the cards or graphs when I pick a commodity for revenue.  It's only updating the map.
