### ISSUE TITLE
Record Code for America Presentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#263]
To be included in a YouTube channel.

**Comment by mcharg** [comment]
@jennmalcolm I put in the opening/closing slides from the CfA template, but need help figuring out how to edit the background on the title slide. 
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B016D7D6D-77F7-408C-A019-171B80A78D0F%7D&file=Code-for-America_Shaping.pptx&action=edit&mobileredirect=true

**Comment by jennmalcolm** [comment]
I got the background images removed on the title slide @mcharg

**Comment by mcharg** [comment]
Recorded and submitted.
