### ISSUE TITLE
Consolidate explore data study findings 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#266]

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg I have consolidated the findings and came up with recommendations, please review and change or add recommendations as you see fit.
 https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B2f290b0b-ee40-41bf-8bba-bb2ba2c6c78d%7D&action=editnew&cid=0fbfe848-80fc-4cae-8c77-219db3ca05a9

**Comment by mcharg** [comment]
@Maroyafaied I added comments to the spreadsheet.

**Comment by Maroyafaied** [comment]
@mcharg I worked through all the comments, please take another look when you have time. Thanks

**Comment by mcharg** [comment]
@Maroyafaied Looks good.

**Comment by Maroyafaied** [comment]
For the presentation at demo 
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={0f518766-bada-4dda-938a-a4dd737ed3e8}&action=edit
