### ISSUE TITLE
Create posting for VSFS Interns for 2020-2021

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#268]
We can start submitting intern positions on May 1st. 
https://vsfs.state.gov/

**Comment by lpgoldstein** [comment]
@mcharg I copied out the UX job description from last year as a starting point for next year. 
https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/Ed6qL-Iox0ZDs_CGAlVlAvgBYUIgKPZb5UwwjNJT24UkdQ?email=Lindsay.Goldstein%40onrr.gov&e=rbxEgV

**Comment by lpgoldstein** [comment]
@mcharg I added a data position posting.

**Comment by mcharg** [comment]
@lpgoldstein I took a look and added a couple comments.
