### ISSUE TITLE
Add what's new to the space to the right of the intro content on the homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#271]
And have it move to the bottom on smaller viewports.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/dcaa801b-391f-4acc-bfd6-4455bd4d8eaa)

**Comment by jlouis-onrr** [comment]
You can see this update in 202:
https://202-pagesubnavigation.app.cloud.gov/

**Comment by mcharg** [comment]
@jlouis-onrr It feels like what's new has more weight than the intro paragraph.  Can you try reducing the font size and removing the extra space between the two bullets to make the box take up less space and feel less prominent?
![image](https://user-images.githubusercontent.com/38465926/79364253-19ad8900-7f17-11ea-9abf-9af346a6e9c7.png)
