### ISSUE TITLE
Fix map zooming for Explore Data

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#273]
- [ ] Make reset button reset the map to default zoom
- [ ] Enable zooming before using the scroll wheel

**Comment by jennmalcolm** [comment]
At least not have a non-functional reset button before hard launch.

**Comment by jennmalcolm** [comment]
Related to #287--work at the same time.

**Comment by jennmalcolm** [comment]
Making a part of #314, so closing this.
