### ISSUE TITLE
Explore Data: Fix counties displaying multiple times in search

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#274]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0040ba56-4442-4a00-a131-6afa37585adf)

**Comment by jennmalcolm** [comment]
Need one true source data lookup for county, state name. To start, we could just not show duplicates or update data to not have "county" or "parish."

**Comment by jennmalcolm** [comment]
Quick fix, make the search box only get county names from relevant data set.

**Comment by mcharg** [comment]
Appears to be fixed in #443
