### ISSUE TITLE
Reduce confusion of "other" revenue type

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#275]
- [ ] Make revenue type circle chart display 6 values instead of rolling up "Other"

**Comment by mcharg** [comment]
#334 covers the CY/FY issue, so repurposing this issue to just be about the revenue types.

**Comment by jennmalcolm** [comment]
make revenue type accommodate all 6 categories

**Comment by mcharg** [comment]
This didn't make its way into #189

**Comment by mojobnichols** [comment]
Available in PR:

https://511-offshorecards.app.cloud.gov/explore/

**Comment by mcharg** [comment]
This is no longer fixed in dev.
![image](https://user-images.githubusercontent.com/38465926/89037950-70e03980-d30d-11ea-8f61-5bc2cb5cd102.png)

**Comment by mcharg** [comment]
The fix broke this in dev.  Royalties is displaying multiple times.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1cf38c3f-d065-4c83-9993-5eb280f9b4da)

**Comment by mojobnichols** [comment]
Fixed in PR https://github.com/ONRR/nrrd/pull/709
