### ISSUE TITLE
Define what glossaries we want to add to tables below charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#289]
For things like oil & gas, NGL, GOMESA

Will need to list terms to include glossaries for and then implement.

**Comment by jennmalcolm** [comment]
First step, identify terms that we want to have glossary links on.

**Comment by mcharg** [comment]
@jnwang01 Jeff is going to be implementing the glossary in the query tool this sprint, if you want to start looking at terms that we should define and whether we already have a definition for them.  Offhand, I know we need anything that's an acronym (for example, NGL), "not tied to a lease" (or location or commodity - we're looking to standardize this), and any time we use "other" (for example, "other revenue").

**Comment by jnwang01** [comment]
@mcharg I have the terms in the draft for the full page glossary I'll link it here

**Comment by jnwang01** [comment]
https://3qh5zb.axshare.com/

**Comment by mcharg** [comment]
@jnwang01 It would be helpful if you could take a look at the query tool and identify terms we don't already have definitions for that we should create new content for.

**Comment by jnwang01** [comment]
@mcharg Oh I see what you mean now, okay I'll look at the query tool and make a  doc with terms.

**Comment by mcharg** [comment]
"Oil & gas" is another one users have trouble with, but we should be changing it to "oil or gas (pre-production)" soon, so the definition should be for that.

**Comment by jnwang01** [comment]
Here are the terms I think should be defined the query tool, the last 3 terms which are highlighted in red I don't have the definition to.
[glossary terms query tool.xlsx](https://github.com/ONRR/nrrd/files/5914582/glossary.terms.query.tool.xlsx)

**Comment by mcharg** [comment]
Uploaded file to Teams for commenting and editing:
https://teams.microsoft.com/l/file/73985E53-3C81-40A9-8853-A10482F267AB?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FGlossaries%2Fglossary.terms.query.tool.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@jnwang01 This is a great start.  I added a few terms and a comments column.

@Maroyafaied @jennmalcolm @lpgoldstein Do any of you want to review, as well?

**Comment by mcharg** [comment]
The terms in the query tool are probably the same ones we're going to want defined in the Explore Data charts.

**Comment by jennmalcolm** [comment]
I will take a look.

**Comment by lpgoldstein** [comment]
I added one item to the list but it looks like now have all of the revenue and disbursement types covered.
