### ISSUE TITLE
Explore Data: Design revenue Detail Cards: Overall card layout

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#29]
Determine the best order for all the components and make sure they all work together.

**Comment by jennmalcolm** [comment]
This is for the layout of the cards and on the cards as well.

**Comment by mcharg** [comment]
Here's what all the sections look like on the card together (assuming we're leaving off ownership).
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7328b1e3-6957-4f7c-b720-575edc895daf)

**Comment by mcharg** [comment]
Here's what a county card looks like:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a5761065-2201-4c05-a629-7b0e7b88a4c7)

**Comment by mcharg** [comment]
Final cards.  Colors will be determined in #176.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d4539167-8714-4037-8bb5-399364c99230)

Prototype: https://935313.axshare.com/#g=1&p=revenue_detailed_cards
