### ISSUE TITLE
Q/A testing on query tool

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#292]

**Comment by Maroyafaied** [comment]
the drop down arrow is overlapping  with the wording 
![image](https://user-images.githubusercontent.com/40175688/79891053-a778f080-83bd-11ea-85eb-2ce285016813.png)

**Comment by Maroyafaied** [comment]
numbers are not formatted with commas and too many decimal points.
![image](https://user-images.githubusercontent.com/40175688/79891222-ec048c00-83bd-11ea-97bb-dfffce52a209.png)

**Comment by Maroyafaied** [comment]
no option to select all states 
![image](https://user-images.githubusercontent.com/40175688/79891601-73ea9600-83be-11ea-9880-236845b76bfe.png)

**Comment by Maroyafaied** [comment]
space is needed 
![image](https://user-images.githubusercontent.com/40175688/79891646-88c72980-83be-11ea-93de-08bf44924b49.png)

**Comment by lpgoldstein** [comment]
space, commas, and confusing blank after offshore region

![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/974d85b9-d9f5-44c6-aa5f-b77fe3b117c9)

**Comment by lpgoldstein** [comment]
multiple rows of the same commodity ![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/a1d48106-6f2e-405f-a243-8705b1c4a146)

**Comment by Maroyafaied** [comment]
multiple rows for the same revenue type 
![image](https://user-images.githubusercontent.com/40175688/79892583-03dd0f80-83c0-11ea-9212-0cc6d5568ebf.png)

**Comment by mcharg** [comment]
State and offshore region should be grouped into a single location filter.

**Comment by mcharg** [comment]
State names are missing when you group by state. 
![image](https://user-images.githubusercontent.com/38465926/79992776-f12b0f00-8481-11ea-9df3-02477efa37c6.png)

**Comment by mcharg** [comment]
There's no ability to select "all" for the multi-select filters.

**Comment by mcharg** [comment]
Need to update what happens when there is no data: 
* Only display rows when there is data for at least one year the user has selected.
* If there are years with no data in the user's selection, but numbers for at least one other visible year, the years with no data get a dash.

**Comment by mcharg** [comment]
@master12 How far did you get on fixing these on Friday?  We need to create new issues for any you didn't fix.

**Comment by master12** [comment]
@mcharg I got a lot but my data has seemed to changed. I am not getting back the states anymore. I will address when we consolidate location stuff. I am going to add several issues that will address our data that will fix the issues you are noting. 

However there is not select all because not selecting an option to filter is essentially select all. Not sure what to do about that so lets chat about that stuff.

**Comment by mcharg** [comment]
@master12 Users haven't been understanding that not selecting selects all in the user interviews.  I think we need to be more explicit.

**Comment by mcharg** [comment]
I created a new issue for the one remaining issue that wasn't covered by existing issues.
