### ISSUE TITLE
Split out LWCF and HPF from Other funds on the disbursements trends section of the homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#3]
@mojobnichols Said it will be a lot easier to split out LWCF and HPF once the database is hooked up because of the way things are categorized differently in the monthly and yearly files, so we're proposing launching with them rolled into the Other funds and create a new issue for splitting it out when the database is hooked up.

**Comment by jennmalcolm** [comment]
@brentryanjohnson and @mcharg have you discussed the strategy on this? Should the categories on the disbursements trends section be the same as in the current explore data disbursement feature?

**Comment by mcharg** [comment]
I think it should be.

**Comment by mcharg** [comment]
Covered in #1147
