### ISSUE TITLE
Design link to beta site

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#305]

**Comment by mcharg** [comment]
This uses a pattern we have to shutdown messaging, so it should be easy to implement.  @jennmalcolm Does this work for you?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6b85dc6e-5f5b-4fe5-9d88-19ea65e251b6)

**Comment by jennmalcolm** [comment]
Yes, I think that works.
