### ISSUE TITLE
QA testing of dev

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#306]
With an eye towards what we need to fix before beta launch.

**Comment by mcharg** [comment]
I went through the homepage in detail and created issues #316-#323 with bugs I found.

**Comment by Maroyafaied** [comment]
@mcharg what page do your recommend I look at?

**Comment by mcharg** [comment]
@Maroyafaied We should probably all go through all of the pages again to make sure we don't miss anything.

**Comment by mcharg** [comment]
I just created labels for About and Downloads, so we can easily flag issues with those pages and filter the issues to view as we're looking at each section and avoid duplicates.

**Comment by mcharg** [comment]
Made it through Explore Data (issues #224-#241) for both revenue and disbursements.

**Comment by mcharg** [comment]
Issues #342-#362 are for the query tool.

**Comment by Maroyafaied** [comment]
The revenue types and definitions don't match on the nationwide revenue summary, added issue #364

**Comment by mcharg** [comment]
I also created a smattering of issues for About, How It Works, and the footer.  Didn't see any issues with downloads.

**Comment by Maroyafaied** [comment]
I added issue #370 for two of the download pages.

**Comment by Maroyafaied** [comment]
For the homepage  monthly bar charts, the title on top of the table doesn't show the selected year when viewing monthly. I added issue #373

**Comment by mcharg** [comment]
Closing and will create a new issue for the next sprint.
