### ISSUE TITLE
Add disbursement data to query tool

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#308]

**Comment by mcharg** [comment]
@master12 Is there a PR for this?

**Comment by mcharg** [comment]
@master12 I'm not seeing disbursements data in what you merged into dev.  Does this need to come into this sprint?

**Comment by mcharg** [comment]
@master12 Is there a reason why the group by/breakout by function isn't there for disbursements the the table is just flat with all fields?

**Comment by mcharg** [comment]
There's some logic to the grouping and when we allow grouping by state in the current query tool that isn't there in the new one.  I'll create a new issue for that.
