### ISSUE TITLE
How its works homepage links don't work

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#318]
It's not reading the anchor text and brings up a blank white page.  This is the case for revenue, disbursements and produciton.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5fec004f-7a68-4268-99e4-f410f0e4a1b6)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8ccc9daf-374c-404c-ac95-870dced70066)

**Comment by mcharg** [comment]
Still linking to how "it" works instead of "revenue".

**Comment by mcharg** [comment]
The pages open in #311, but it's not scrolling to the anchors.

**Comment by mcharg** [comment]
The links aren't scrolling to the anchors.

**Comment by jlouis-onrr** [comment]
I wonder if this is cached on your side.  Im seeing the link resolve to the new url, for example:

https://dev-nrrd.app.cloud.gov/how-revenue-works/#revenues

**Comment by mcharg** [comment]
It resolves the url, but doesn't scroll down to the revenue section.

**Comment by jlouis-onrr** [comment]
Seems like the anchor is different now, which section should it be going to now on that page?

**Comment by mcharg** [comment]
Revenue should go to: https://dev-nrrd.app.cloud.gov/how-revenue-works#understanding-federal-revenues

Disbursements should go to: https://dev-nrrd.app.cloud.gov/how-revenue-works#understanding-federal-disbursements

Production should go to: https://dev-nrrd.app.cloud.gov/how-revenue-works#the-production-process

**Comment by mcharg** [comment]
@jlouis-onrr Disbursements and production are now going to the right places.  Revenue is going to the Native American revenue section.

**Comment by jlouis-onrr** [comment]
@mcharg just pushed update out to dev
https://dev-nrrd.app.cloud.gov/

**Comment by mcharg** [comment]
Looks good
