### ISSUE TITLE
Make query tool links on detail cards smart (and add them back)

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#328]
They should automatically filter to the state or county that the card is for and be grouped by the appropriate thing.

For example, the link here should filter to Colorado, grouped by commodity with no breakout.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b0555b45-d3c2-4ada-94e2-b38363df3e0a)

**Comment by mcharg** [comment]
If we don't make this change before the soft launch, we should remove the links to the query tool.

**Comment by mcharg** [comment]
#419 is to take them out until the query tool is ready for them to work right.

**Comment by mcharg** [comment]
This shows where the links should go on the Explore Data page and what parameters should be set in the query tool when clicking on each link.

Revenue:
https://935313.axshare.com/#g=1&p=revenue_1

Production:
https://935313.axshare.com/#g=1&p=production_1

Disbursements:
https://935313.axshare.com/#g=1&p=disbursements_1

**Comment by jlouis-onrr** [comment]
@mcharg, how do you want to handle the year?  Since the query tool uses a 5 year range, do you want to take the current year + 5 or what I was thinking is to take the current selected year - 5? So, if you have selected 2017 in explore data, when you arrive from the query link you would get the range of 2012 -2017?

**Comment by mcharg** [comment]
@jlouis-onrr I think selected year -5 works.

**Comment by mcharg** [comment]
Or we could put the selected year in the middle of the range, so 2015-2019 if you select 2017.
