### ISSUE TITLE
Make the commodity selection update revenue cards and charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#331]
Right now it's only updating the map, but it should update everything on the page.

**Comment by jennmalcolm** [comment]
What will happen to the commmodity portions of the detailed cards and summary cards when we do that? Do we already have a design for that?

**Comment by mcharg** [comment]
I think we should just hide those sections.

**Comment by jennmalcolm** [comment]
Also, when no commodity is selected, the map (and cards) shouldn't display the data for all. Perhaps the tool tip on the map should say, "no commodity selected." 

![image](https://user-images.githubusercontent.com/30806839/87448629-16837100-c5ca-11ea-804b-ba82d257c30c.png)

**Comment by mojobnichols** [comment]
The wording really has facilitated fixing this issue to make data visualizations match commodity selection.

**Comment by mojobnichols** [comment]
Fixed in  [603 githup PR ](https://github.com/ONRR/nrrd/pull/709)
