### ISSUE TITLE
Decide and Add a close or apply button to drop-down selectors 

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#332]
We've seen it as an issue in testing the query tool .

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5a2292a8-cbbe-4816-9c47-5b83cac71271)

**Comment by jennmalcolm** [comment]
Test to see if removing x from clear filters is enough to make it obvious.

**Comment by master12** [comment]
removed the X. it is available in dev @mcharg @jennmalcolm

**Comment by mcharg** [comment]
We still need to watch this in user testing.  This issue is not closed.

**Comment by mcharg** [comment]
Will be addressed by #561.
