### ISSUE TITLE
County level disbursements aren't showing up in the map

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#341]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/685e2aeb-0741-4c1b-8285-eebf18d30eab)

**Comment by mojobnichols** [comment]
Fixed and commited to preview

https://421-422-423-databasechanges.app.cloud.gov/explore/

PR: 

https://github.com/ONRR/nrrd/pull/443

**Comment by mcharg** [comment]
@mojobnichols Getting a 404 error on the preview.
