### ISSUE TITLE
Put highest volume commodities first in the drop-down

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#346]
Users are having a hard time finding oil and gas and a couple of participants have suggested putting those first.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/48db8cc4-cc51-4229-99f3-8d5b8a989e0a)

We should copy the ordering we have on the live site:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/27acfcab-9b33-428d-a2b7-b032d8365d81)

**Comment by jennmalcolm** [comment]
Put in the same order as the old query tool. Could consider going by highest revenue items.

**Comment by jennmalcolm** [comment]
Should we also organize he query results in the same way when we have it by commodity. It currently seems pretty random. ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/349e59c9-8099-4a88-a950-ef2ac9d618cb)
