### ISSUE TITLE
Always have drop-down labels outside the box

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#348]
Having them in the box when there isn't a selection makes users think they have a selection.

We should always use the placement like on the "land category" drop-down below, not the "land class" one.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/65020e61-ebf9-4778-9ca9-e7029d3cf12a)

**Comment by jennmalcolm** [comment]
Should we use the explore data dropdowns on query tool and home page as well?

**Comment by mcharg** [comment]
Will be addressed by using the Explore Data drop-downs.

**Comment by mcharg** [comment]
Wasn't fixed by using the Explore Data components.  We still have drop-downs with the label in the box.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c83ba82f-b24c-4203-8235-a6e8a8839f06)

**Comment by mcharg** [comment]
I think the one drop-down where this is still an issue, is County on the query tool.

**Comment by jennmalcolm** [comment]
part of #592
