### ISSUE TITLE
Total rows need a label

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#353]
They should be labeled as "Total"
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a37823a6-4fec-4e56-a174-82e292d43f68)

**Comment by mcharg** [comment]
@master12 The total at the bottom should be "All revenue types" not "All commodities".
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/86d6793c-f0da-4515-8ba3-8f9a5b905dbe)

**Comment by mcharg** [comment]
See my comment above.  This is not closed.

**Comment by master12** [comment]
Are the other labels right? because this column is in the commodity column? @mcharg

**Comment by mcharg** [comment]
It's not adding up commodities.  It's adding up all the revenue types.   It's an issue in the current site, as well and causes confusion for users.

**Comment by master12** [comment]
So are all the labels wrong or just the last one?

**Comment by mcharg** [comment]
Just the one on the bottom.  The ones within the expandable sections are totaling the commodity.

**Comment by master12** [comment]
Ok closing this issue and making a new one for the last row
