### ISSUE TITLE
All fields should be in the group by drop-down

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#355]
Right now, the selected one in the breakout by drop-down is omitted, which is confusing to users.  If the user selects that one from group by, it can change the breakout by to no selection.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c4af6032-bf38-4ff8-92da-3f90de7abe93)

**Comment by jennmalcolm** [comment]
If every option is in the first and the same thing is selected in the first as what's in the second, the second column should clear.

**Comment by mcharg** [comment]
This is done.
