### ISSUE TITLE
Add labels to blank values

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#356]
We need a label whether it's "not tied to a lease", "not tied to a commodity" or whatever it is, so users aren't confused.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/45d41321-7fd5-4e09-85e9-8f6e1f963d2a)

Withhelds do not exist in new data.

**Comment by Maroyafaied** [comment]
I confirmed, when commodity is not specified we use "Not tied to a commodity", and "withheld" for location.

**Comment by mcharg** [comment]
There are still blank lines in dev.
![image](https://user-images.githubusercontent.com/38465926/82483394-559fb500-9aa6-11ea-8f16-50a385d23204.png)

**Comment by master12** [comment]
Sorry wrong blank lines. Moving this to next sprint so we can check against the new columns we made to address this issue
