### ISSUE TITLE
Remove expand/collapse functionality when the user doesn't have a breakout by selected

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#358]
It's confusing to have no column header and totals in this view.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4ff17b62-7c50-4cc8-b2cc-a8b434aade38)

**Comment by master12** [comment]
This has been fixed in current build. @mcharg 

https://beta-nrrd.app.cloud.gov/query-data/

**Comment by mcharg** [comment]
Looks good.
