### ISSUE TITLE
Revenue types & definitions don't match - Nationwide revenue summary

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#364]
Some of the revenue types and definition don't match. 
- [ ] other revenues should be Bonus
- [ ] Civil penalties should be "rent"
- [ ] Bonus should be Inspection fees
- [ ] add title to civil penalties definition
- [ ] Rents should be other revenues
- [ ] Delete inspection fee

**Comment by mcharg** [comment]
Appears to be fixed in dev now.
