### ISSUE TITLE
Revenue over time chart - change scale

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#365]
When comparing two states with one having much higher revenue, the other state just shows as a straight line. Maybe changing the scale would make it less confusing. Here is an example of Texas and Wyoming. 
![image](https://user-images.githubusercontent.com/40175688/81086905-546f6500-8eb6-11ea-9ad6-0298ebcb5cac.png)

**Comment by jlouis-onrr** [comment]
@mcharg, @Maroyafaied, @mojobnichols, heres what the chart looks like going with a logarithmic scale.  Thoughts?

![line_chart_logarithmic_scale.PNG](https://images.zenhubusercontent.com/5d893e494c2d9e0001fa99ad/58e7654b-31e7-4730-8c9d-a264a3b160fd)

**Comment by mcharg** [comment]
Fixed in #365
