### ISSUE TITLE
Wrong section highlighting in left nav

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#369]
The Accountability section should be highlighting instead of resources to revenuw - I clicked on the accountability link in the intro text at the top of the page.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8dc90c49-d727-4fbe-ba40-5edf30e125af)

**Comment by Maroyafaied** [comment]
Revisit left nav component (table of contents component)
