### ISSUE TITLE
Explore data: production page navigation update

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#371]
Production page navigation currently says "Compare oil production" no matter what commodity has been selected. It needs to be changes to say the selected product or simply remove "oil". Removing "oil" is probably the easiest for now and then would also match the navigation menu's behavior for revenue (I.e., not update with commodity names when a commodity is selection)

**Comment by jlouis-onrr** [comment]
removed oil for now and it was added to #313
