### ISSUE TITLE
Glossary links don't work on mobile

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#372]
Nothing happens when I tap on them on iPhone using Safari or on Android using Chrome.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/04a39a87-9fe0-46dd-b37f-edabbbf4c44a)

**Comment by jlouis-onrr** [comment]
looks like its working in mobile with the long press approach.   According to mui, "On mobile, the tooltip is displayed when the user longpresses the element and hides after a delay of 1500ms. You can disable this feature with the disableTouchListener property."  im going to adjust the delay to see if that can make it more obvious

**Comment by mcharg** [comment]
This still isn't working on iPhone.  It just outlines the link when I tap on it no matter how long I press.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3039a857-8edd-4479-a893-829b297210c0)

**Comment by mcharg** [comment]
It's also not working on Android.

**Comment by jlouis-onrr** [comment]
@mcharg the latest updates for this can be found in the following branch.  I adjusted the initial touch delay so it seems to be a little more intuitive now.

https://333-createbasedatafilter.app.cloud.gov/

**Comment by mcharg** [comment]
@jlouis-onrr Much better!
