### ISSUE TITLE
Homepage - add year next to the selected month on the bar charts

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#373]
We need to add  year next to the month selected on top of the table for the bar charts like we have on the site now.  The year is not there for production, revenue and disbursements.
![image](https://user-images.githubusercontent.com/40175688/81101740-d027dc80-8ecb-11ea-8add-fba2ca5b9494.png)
![image](https://user-images.githubusercontent.com/40175688/81101801-e0d85280-8ecb-11ea-81c9-ed0709f150df.png)

**Comment by mcharg** [comment]
Fixed in #365
