### ISSUE TITLE
Line chart is poorly formatted on mobile

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#380]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ae553201-142d-4a32-b29b-29d887385beb)

**Comment by mcharg** [comment]
This is in both iPhone SE and Android Samsung S8.

**Comment by jlouis-onrr** [comment]
@mcharg, looks like this one has been addressed already.  Would you like to confirm?

**Comment by mcharg** [comment]
Looks good on my phone.
