### ISSUE TITLE
Explore data: Rename "offshore data" selector

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#388]
The "offshore data" selector really doesn't turn the data on and off. The nationwide totals are the same with the offshore data on or off. Offshore always shows up in the nationwide graphs at the bottom of the page. So, I'm thinking we should rename that selector to "Offshore map" since it's really just turning the offshore layer of the map on and off, not impacting any of the data below on the page.

What do you think @shannonmcharg?

**Comment by jennmalcolm** [comment]
In exploring a bit further, it seems that you cannot add a card for an offshore area unless the offshore data selector is on. So, I guess we many need to discuss the functionality and label a bit further to make sure it's doing what we want and it's clear to users what that selector does.

**Comment by jennmalcolm** [comment]
Never mind, you can find offshore areas in the search box, but you can't add them whether the offshore selector is on or off.

**Comment by mcharg** [comment]
We could call it "offshore map" and change "on/off" to "show/hide".

**Comment by mcharg** [comment]
@jlouis-onrr The options in the drop-down look good in #311, but the label should be "offshore map" instead of "offshore data".
