### ISSUE TITLE
Explore data: change copy for revenue and disbursements and fix for production

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#392]
I would like the summary sentence to say the amount of federal revenue and the amount of Native American revenue for the year and possibly the total. Currently it only has federal, but it should specify federal. Also, when you switch to a new data set, that sentence doesn't update the number. 
![image](https://user-images.githubusercontent.com/30806839/81192045-c1066480-8f87-11ea-968b-1e967c57c8cd.png)

![image](https://user-images.githubusercontent.com/30806839/81192441-3a05bc00-8f88-11ea-8353-e7c2119d35c4.png)

**Comment by mcharg** [comment]
The number is now updating when you select another year.  @mojobnichols will make the text change.

**Comment by mcharg** [comment]
Also not in #189

**Comment by jennmalcolm** [comment]
We also need to change the summary sentence for disbursements to include Native American and the total. It may be the same for production, but that sentence doesn't work at all for me right now, so I'll have to see what it says when I can view it.

**Comment by jennmalcolm** [comment]
This is what I would like to see for the sentences:

Revenue
In fiscal year/calendar year (year), ONRR collected ($) from federal sources and ($) from Native American sources for a total of ($total of fed + Native American).

Disbursements
In (fiscal year/calendar year) (year), ONRR disbursed ($) from federal sources and ($) from Native American sources for a total of ($total of fed + Native American).

Production
In (fiscal year/calendar year) (year), companies produced (#)(units) of (product) from federal sources and (#)(units) of (product) from Native American sources for a total of (#total of fed + Native American) (units) of (product).

If there is zero production for a year for both federal and Native American:
In (fiscal year/calendar year) (year), companies produced no (product) from federal or Native American sources

**Comment by mcharg** [comment]
@jennmalcolm Do we also want copy that explains what revenue, production, and disbursements are?  Maybe copy the sentences from the homepage tabs?

**Comment by jennmalcolm** [comment]
Oh, yes, @mcharg  I was just working on the sentences that provide the totals I think we already have a start of this in the beta site now. I made a few changes (new stuff noted in italics) to what we have now for the sentences below to try to incorporate the whole thing together. I'm open to any feedback to improve these. @lpgoldstein @Maroyafaied do you have any edits?

When companies extract natural resources on federal _or Native American_ lands and waters, they pay royalties, rents, bonuses, and other fees, much like they would to any resource owner. _The Office of Natural Resources Revenue (ONRR) collects and disburses_ (maybe ?Help or link to disbursements page) _these revenues._ In fiscal year/_calendar year_ (year), ONRR collected ($) from federal sources and _($) from Native American sources for a total of ($total of fed + Native American)._

After collecting revenue from natural resource extraction, the Office of Natural Resources Revenue (ONRR) distributes that money to different agencies, funds, and local governments for public use. This process is called "disbursement." In (fiscal year/_calendar year_) (year), ONRR disbursed ($) from federal sources and _($) from Native American sources for a total of ($total of fed + Native American)._

The Office of Natural Resources Revenue (ONRR) collects detailed data about the volume of _mineral and energy commodities companies produce from federal and Native American lands and waters. For (fiscal year/calendar year) (year), companies reported to ONRR that they produced (#)(units) of (product) from federal sources and (#)(units) of (product) from Native American sources for a total of (#total of fed + Native American) (units) of (product)._

**Comment by lpgoldstein** [comment]
@jennmalcolm no edits from me. This looks great!

**Comment by jlouis-onrr** [comment]
@jennmalcolm , ran across this issue regarding Production products content, currently we are trying to display:

_"The Office of Natural Resources Revenue (ONRR) collects detailed data about the volume of mineral and energy commodities companies produce from federal and Native American lands and waters. For (fiscal year/calendar year) (year), companies reported to ONRR that they produced (#)(units) of (product) from federal sources and (#)(units) of (product) from Native American sources for a total of (#total of fed + Native American) (units) of (product)."_

but what about when Native American has no product, for example the product "Clay (tons)", Native American has no data.  Should I just omit the last part referring to Native American products, _"and (#)(units) of (product) from Native American sources for a total of (#total of fed + Native American) (units) of (product)."_ and end the sentence after federal sources?

**Comment by jlouis-onrr** [comment]
@jennmalcolm, or just zero out the value like:

_"The Office of Natural Resources Revenue (ONRR) collects detailed data about the volume of mineral and energy commodities companies produce from federal and Native American lands and waters. For fiscal year 2019, companies reported to ONRR that they produced 57,715 tons of clay from federal sources and 0 tons of clay from Native American sources for a total of 57,715 tons of Clay."_

**Comment by jennmalcolm** [comment]
I think the 0 is the right choice @jlouis-onrr. Could you remove the extra units in paranthesis and also make sure that all of the commodities/products are not capitalized.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/42378240-b6c7-4656-a21d-1302a22ef617)
