### ISSUE TITLE
Explore Data: Nationwide summary onshore royalties number slightly off

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#394]
All the numbers seem right, so I'm not sure if this is just a strange rounding thing somewhere, but onshore royalties is off just a bit.

![image](https://user-images.githubusercontent.com/30806839/81206208-c9679b00-8f99-11ea-9008-b8337816ab02.png)

**Comment by mcharg** [comment]
@jennmalcolm Were you looking at FY or monthly data for this?

**Comment by jennmalcolm** [comment]
FY. Why would we be using monthly data on this chart?

**Comment by jennmalcolm** [comment]
This looks to be fixed.
