### ISSUE TITLE
Explore data: Nationwide summary revenue doesn't work for 2009 or before

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#396]
Works well for 2010 and newer but doesn't load for 2009 or before.

![image](https://user-images.githubusercontent.com/30806839/81208630-5bbd6e00-8f9d-11ea-8fee-0fa0083a668b.png)

**Comment by mcharg** [comment]
The monthly file only goes back to 2009, so need to pull in the FY file for earlier years.

**Comment by jennmalcolm** [comment]
Also, I thought you were using the data from the FY files for this page. I'd definitely don't think we should be mixing the two--especially for production, but there are often slight variations on revenue as well.

**Comment by jlouis-onrr** [comment]
@mcharg, is this still occurring?  Having a hard time recreating in dev.

**Comment by jennmalcolm** [comment]
@jlouis-onrr it's working in dev now, so I will close.

**Comment by jennmalcolm** [comment]
Actually, I'm opening back up because the 2009 and before version does not have the same sorting. It should be sorted the same as it does post 2009. Can you fix that @jlouis-onrr? 
![image](https://user-images.githubusercontent.com/30806839/88726295-7403db80-d0fb-11ea-9cf7-a6fa33960e2a.png)
![image](https://user-images.githubusercontent.com/30806839/88726366-94cc3100-d0fb-11ea-93ee-bc1c11ffea06.png)
