### ISSUE TITLE
Explore data: revenue top locations- other data wrong

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#399]
In revenue top locations, the other data isn't coming through correctly. Also, since this is only showing federal revenue, we need to make that clear somewhere, either in the header or in some text. Ideas for that @mcharg.

![image](https://user-images.githubusercontent.com/30806839/81218443-3421d200-8fac-11ea-96d4-d4f348818d08.png)

**Comment by mcharg** [comment]
I had a withheld note to address the Native American issue in the design.  We should add that.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/96abff43-b745-4622-aacb-04628595b8f2)

**Comment by mcharg** [comment]
The withheld text is now in dev and looks good.

**Comment by mojobnichols** [comment]
Closer but still off 
it can be previewed at 

https://421-422-423-databasechanges.app.cloud.gov/explore/

I was rolling offshore and state up together it was confusing way to do it.  Some how other contained some states that didn't have state name.  Now I simply union offshore with state with county with nationwide and indian.    The numbers are much closer, but I was still off for 2012

with other coming in at:

2012 Other	$1,388,282,096 (~$60 million more)
         
2004 Other   $589,805,724 ($100 more)

**Comment by mojobnichols** [comment]
PS the top locations now works with the show hide map so if we have an issue for that it can probabably be pulled in.

**Comment by mojobnichols** [comment]
Added Native American and not tied to a lease to top locations.
