### ISSUE TITLE
Explore Data: state card total disbursements pulling only state onshore as state total

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#402]
State total at the top of the card is off. It's not including the GoMESA number. Here's what I have from the spreadsheet: 

2019 | 101,327,286.83
-- | --
State | 2862668.77
State - GoMESA | 94728191.78
State 8(g) | 3736426.28

![image](https://user-images.githubusercontent.com/39419003/81230237-1a3dba80-8fbf-11ea-88e7-bc040fe82531.png)

The FY2019 disbursements on the current site show 
![image](https://user-images.githubusercontent.com/39419003/81230391-6426a080-8fbf-11ea-9364-f1ef19c16a56.png)

**Comment by lpgoldstein** [comment]
@mojobnichols I've attached a spreadsheet showing my calculations for the state summary cards. I'm using NM, LA and AK as my example states. https://doimspp-my.sharepoint.com/:x:/g/personal/goldstel_mms_gov/EWuHv2jFxplEnbS21Qhgl2cB28d_Yv3EB7DdlcvXAImIMQ?email=mojo.nichols%40onrr.gov&e=SKo4qd

**Comment by mojobnichols** [comment]
Fixed and commited to preview

https://421-422-423-databasechanges.app.cloud.gov/explore/

PR:

https://github.com/ONRR/nrrd/pull/443
