### ISSUE TITLE
Create presentation for TTS Research Guild

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#405]
Tentatively looking at presenting 5/26.  Topic will be something on design and research.

**Comment by mcharg** [comment]
"building a UX research practice in an org with few specialists in the discipline" could be a good topic/angle to come from. 18F and TTS does a lot of work to build capacity and capabilities with our partners, so I think the guild would love that topic.

**Comment by Maroyafaied** [comment]
@mcharg here is what I've worked on, we might still need to shorten it depending on how long they want us to present. 
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BC185F185-85C5-451E-89D3-58012932BB7E%7D&file=InternationalDesigninGovtPresentation.pptx&action=edit&mobileredirect=true
