### ISSUE TITLE
Horizontal bar charts are reversed in Edge, IE, and iPhone Safari

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#408]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/aa4cedc9-b001-4291-9557-21122434c986)

**Comment by mcharg** [comment]
Also an issue in IE.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b65a913f-aae5-4727-8ded-0025d4d71052)

**Comment by mcharg** [comment]
Also on iPhone Safari.

**Comment by jennmalcolm** [comment]
Also a problem in Safari on my MacBook.

**Comment by mcharg** [comment]
Duplicate of #381.
