### ISSUE TITLE
Year slider placement is weird in IE

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#410]
It's not centered and doesn't quite stick right.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/62f312df-a17a-4025-9d2d-340ef503f548)

**Comment by mcharg** [comment]
The year slider is now missing in IE.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4ffb79a1-2ead-4e49-a864-ee9cc8cd84b2)

**Comment by jlouis-onrr** [comment]
@mcharg, this looks to be resolved now after moving year slider to toolbar in PR #614

**Comment by mcharg** [comment]
Fixed in #614
