### ISSUE TITLE
More QA testing of dev

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#420]

**Comment by jennmalcolm** [comment]
Here some of the items from our checklist that we should make sure we check off when we review. I supplemented with some new stuff for explore data. Feel free to add items to the checklist.

Navigate between pages
- [ ] Check several types of location profile page to ensure data and liquid templates are working as expected
- [ ] Check links are working correctly
- [ ] Check drop downs menu and validate they work 

Text
- [ ] No misspelling
- [ ] Correct spacing
- [ ] Correct format
- [ ] Accurate dates displayed

Maps
- [ ] Appears on the page
- [ ] Shaded correctly
- [ ] Hover behavior works
- [ ] county/offshore area maps: hover behavior and do cards open

Explore data - Revenue
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
 - [ ] Check all of the above for sample set of commodities
 - [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 

Explore data - Production
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
 - [ ] Check all of the above for sample set of commodities
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

'Explore data - Disbursements
 - [ ] Check all cards and line charts for nationwide, Native American, and sample of states/offshore areas/counties
 - [ ] Check data on map hover for for sample of states/offshore areas/counties
 - [ ] Check all nationwide summary data on charts
- [ ] Check all of the above for sample set of 3-4 years including at least 1 before 2009 including at least 1 before 2009

Homepage charts
- [ ] Hover behavior is working 
- [ ] Data displayed is correct - revenue
- [ ] Data displayed is correct - production
- [ ] Data displayed is correct - disbursements
- [ ] Chart changes if you select yearly or monthly

Homepage trends
- [ ] spark lines trend appears correct - revenue 
- [ ] FY 20 data displayed is correct - revenue
- [ ] spark lines trend appears correct - disbursements
- [ ] FY 20 data displayed is correct - disbursements

Check all browsers
- [ ] Chrome
- [ ] Internet Explorer
- [ ] Safari
- [ ] Firefox
- [ ] Edge

Check all devices
- [ ] Dell Laptop
- [ ] Chromebook
- [ ] Macbook
- [ ] iPad
- [ ] iPhones
- [ ] Samsung phones

Check all responsive breakpoints
- [ ] < 480 px (switches to one-column layout)
- [ ] 600 px (changes bar chart layout from three column to accordion with one column)
- [ ] 768 px (converts side navigation from separate column to the right to a select list)
- [ ] > 768 (full site layout)

**Comment by Maroyafaied** [comment]
For production data: There is not a select all option for commodities, bar chart doesn't change as you select a different fiscal year, county data is not pulling correctly. I'll make separate issues for all those.

**Comment by jennmalcolm** [comment]
Ok thanks @Maroyafaied due to the different units though, there should not be an option to select all on production.

**Comment by Maroyafaied** [comment]
@jennmalcolm yes I just realized that, I took that part out of my comment.

**Comment by Maroyafaied** [comment]
@mojobnichols the offshore data is not working, I made an issue #453

**Comment by jennmalcolm** [comment]
For any "something went wrong" errors, document in #471.

**Comment by mcharg** [comment]
I checked all the links on the homepage and spot checked the ones in How It Works, Downloads, and About.  I created issues for a few that aren't going to the right place.  None of them are show stoppers.  Most are just wrong anchors to sections within the page.

**Comment by mcharg** [comment]
I reviewed a bunch of browsers and devices and all the viewport sizes and created issues.

**Comment by lpgoldstein** [comment]
April disbursements data is not displaying on the homepage

**Comment by jennmalcolm** [comment]
@lpgoldstein I told @mojobnichols that he can wait on updating the database with the new April disbursements data until after the soft launch. He wanted to get the other issues ironed out before adding anything new.
