### ISSUE TITLE
Combine Land Class and Land Category as one option

### ISSUE THREAD

**Issue by master12** [ONRR/nrrd#423]

**Comment by mcharg** [comment]
Name the combined field "land type".

**Comment by mcharg** [comment]
Will create a new column that combines the two.

**Comment by master12** [comment]
this is available in staging, closing

**Comment by mcharg** [comment]
@master12 Do you have a link to staging, so we can review?

**Comment by mcharg** [comment]
Not fixed in the PR that says it fixes it.

**Comment by jennmalcolm** [comment]
closing in favor of #478
