### ISSUE TITLE
Build production version of beta site

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#426]
Includes getting a production database.

**Comment by mojobnichols** [comment]
Swapped Jerome with Jeff so he can help and get knowledge of cloud.gov deployment environment.

**Comment by mojobnichols** [comment]
Jerome took care of this:

https://beta-nrrd.app.cloud.gov/

**Comment by mcharg** [comment]
@mojobnichols Should we use the beta link for QA now?
