### ISSUE TITLE
Add production units to explore data page

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#439]
Requires having a separate units column in the database.

**Comment by mcharg** [comment]
Need to create a checklist of the places to put the units.

**Comment by mcharg** [comment]
- [ ] Summary card
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ab28583e-a4d0-4e13-b4ef-5cd41f36ae36)
- [ ] Detail card
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1eea9fb4-e969-4c72-8e37-5db3f39afb29)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fbcd5d55-8337-4cbc-98c5-e643069562f5)
- [ ] Production over time
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/138543b9-66b9-45fa-ba35-f114c43f541c)
- [ ] Top nationwide locations
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/209394ca-ea7e-4bbc-95cb-b0deaa79aa7f)

**Comment by mojobnichols** [comment]
Okay added bbl to the line chart 1) that is a lot of units everywhere 2) on small chart in detail it wraps.   I suggest we just add it near FY 2019

**Comment by mojobnichols** [comment]
I added unit to the legend.   I think its over kill to put it on legend for every point.  I put it after the higest number but can easily add it to all three numbers or two.   It seemed to already be on the hover number

I removed parens on production over time chart
