### ISSUE TITLE
Make the year slider similar to the one on explore data

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#444]
Participants had to guess what year they are on as they are sliding, we should make it the same design as explore data to show what year the user is choosing as they are sliding.

**Comment by mcharg** [comment]
@master12 It looks like the slider may show the year on the pointer, but it's in black.  Could this be as simple as changing the text to white?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5b2d59e6-6fe9-4f66-8836-9be225b0ed55)

**Comment by mcharg** [comment]
Will use styling from Explore Data.
