### ISSUE TITLE
FIx production by land category bar chart 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#449]
As you hover over different year, it labels all of them as "2003" until you click on them. Also the bar chart doesn't change automatically like the other visuals when you select a different year.

![image](https://user-images.githubusercontent.com/40175688/82258922-f4e27200-9917-11ea-89a0-1c15cb23f9d5.png)

**Comment by jennmalcolm** [comment]
closing in favor of #480
