### ISSUE TITLE
Production county data is incorrect

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#450]
When comparing two states, the county data pulls incorrectly and duplicated for both states. This was comparing TX and CO

![image](https://user-images.githubusercontent.com/40175688/82259762-52c38980-9919-11ea-8d6b-346060295745.png)

**Comment by mojobnichols** [comment]
Fixed and commited to preview

https://421-422-423-databasechanges.app.cloud.gov/explore/

PR:

https://github.com/ONRR/nrrd/pull/443

**Comment by mcharg** [comment]
Fixes broke top locations circle chart for nationwide.
