### ISSUE TITLE
Disbursements over time chart pulling wrong data 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#452]
Disbursements over time chart is pulling the state onshore total as the over total. Spreadsheet attached with current calculations and correct calculations 
https://doimspp-my.sharepoint.com/:x:/g/personal/goldstel_mms_gov/EWuHv2jFxplEnbS21Qhgl2cB_Mg1YW_1uasBcgGyfaFbEg?e=VqnRgu

**Comment by mojobnichols** [comment]
Fixed and commited to preview

https://421-422-423-databasechanges.app.cloud.gov/explore/

PR:

https://github.com/ONRR/nrrd/pull/443

**Comment by mojobnichols** [comment]
combined state and counties on state card so total  is the top recipients
