### ISSUE TITLE
offshore data not working

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#453]
@mojobnichols offshore data for production and revenue is not working for Jennifer and I. 
![image](https://user-images.githubusercontent.com/40175688/82342958-76391380-99af-11ea-9d95-7ba8c106a798.png)

**Comment by mojobnichols** [comment]
Offshore production is at a different granularity then our map (planning vs region) and ifferent then revenue. 
So our options:

1) quick fix - distribute the data evenly to each region 
    pros - it would be relatively easy to do
    cons - it  would be misleading 

2) longer solution stitch the offsore planning areas together into one region.  Role up revenue to region 

3) quick fix 2 - remove the offshore option on production.

**Comment by mojobnichols** [comment]
Scratch the above comment.  It was late  we do have the planning areas at the right detail.

**Comment by jennmalcolm** [comment]
@mojobnichols can we meet about this?

**Comment by jennmalcolm** [comment]
Need to stitch map together to have Gulf, Pacific, Atlantic, and Alaska as the areas all together.

**Comment by mojobnichols** [comment]
Map is stitched together and function.   I had to disable the offshore cards until I make all the views use offshore region.   Also Alaska is being done a very hackish way so it would be nice make it use the same technique as the other offshore regions.

If this is acceptable for soft launch let's close this out and open the offshore cards issue.
