### ISSUE TITLE
Production cosemetic issues

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#469]
Remaining Production comsmetic issues:

- [ ] Stacked barchart doesn't have units

- [ ] Legened label is land_category

**Comment by mcharg** [comment]
The items above both refer to the bar chart.  Should we close in favor of #480?

**Comment by mojobnichols** [comment]
Yes makes sense those are customizations that can made to the  specific barchart so it's not a generalized thing that needs to be addressed.
