### ISSUE TITLE
Document and fix "something went wrong" errors

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#471]
Find all the instances when this error occurs and fix instances.

One example of steps to reproduce the something went wrong page

In Revenue:
2. Open county level maps
3. open sandoval county
4. swith back to states
1. Open New Mexico
4. Switch to Disbursements.
- [x] Fixed

In disbursements:
1. Select North Carolina from the map.
- [x] Fixed

**Comment by mcharg** [comment]
Estimate is 3 for each instance to be fixed.
