### ISSUE TITLE
Line up section headers on the detail chart

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#475]
So you can read across a row.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/489d5aab-d350-49cc-a461-e9c605d9c13a)

**Comment by jlouis-onrr** [comment]
@mcharg, this one is in dev and ready to review

https://dev-nrrd.app.cloud.gov/explore

**Comment by mcharg** [comment]
Looks good.
