### ISSUE TITLE
Figure out what to do with negative numbers on charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#476]
North Carolina in 2019 is an example.
Circle chart
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0d911c81-d787-438c-b058-c6a19e9fc1eb)

Line chart:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/79e1095f-e360-4ca8-8f21-4f16f1ad0ad0)
Note: The line chart is showing $0 for 2019 instead of -$158 that shows everywhere else.

**Comment by jennmalcolm** [comment]
Let's look at starting y axis as zero or negative if there is a negative.

**Comment by Baymatt** [comment]
I wasn't able to recreate the issue with the stacked bar chart that was shown in the intern meeting, but I agree that for bar charts and line charts, we should start the y-axis at a negative value if they exist in the data. 

For circle charts, we can have filled circles indicate positive values and unfilled circles indicate negative values which occurs in the demo. Or we could have all negative values be a certain distinct color.
<img width="447" alt="Negative Circle Chart Demo" src="https://user-images.githubusercontent.com/43329595/104555781-4f40e900-55f3-11eb-89e7-69d00015eb83.png">

**Comment by mcharg** [comment]
@Baymatt If you take a look at the monthly numbers in the preview link in the PR where @jlouis-onrr is building the new homepage trends, you can see instances of negative numbers in the bar chart.
https://github.com/ONRR/nrrd/pull/1250

**Comment by mcharg** [comment]
It also looks like we took out the below 0 range on the line chart.
![image](https://user-images.githubusercontent.com/38465926/104600109-95736800-5646-11eb-8ddd-e9d7211cf498.png)

**Comment by mcharg** [comment]
Created separate issues for implementing this on each type of chart. #1298, #1299, #1300, #1301
