### ISSUE TITLE
Update CY production data in DB

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#479]

**Comment by jennmalcolm** [comment]
[https://app.zenhub.com/files/215585796/28aa088a-da2b-4bde-81bc-34ffc185ff0e/download](https://app.zenhub.com/files/215585796/28aa088a-da2b-4bde-81bc-34ffc185ff0e/download)

**Comment by mojobnichols** [comment]
The latest for everything (except april disbusements) is in sandbox
