### ISSUE TITLE
Consider separating page controls and map controls

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#486]
We should consider options for differentiating between the dropdowns/menu select items that control only the map (e.g.) county, commodity, map level, offshore vs those that control the whole page (revenue/production/disbursements and FY/CY.

**Comment by jennmalcolm** [comment]
Since commodity is a page control for production but not for the other datasets, that's something we need to consider with our approach.

**Comment by mcharg** [comment]
@jennmalcolm Commodity should be a page control for revenue, there's an issue to fix that after the soft launch.

**Comment by jennmalcolm** [comment]
Ok, either way, the bigger issue to me is that it's not clear what the different controls are doing since they're all set into the map. That's the main thing I think we need to improve.

**Comment by mcharg** [comment]
@jennmalcolm What if we move the ones that control the map to the end and put in a vertical line to separate them?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d3c61997-77d2-4735-89db-3c9ac970925b)

**Comment by jennmalcolm** [comment]
Perhaps that would be enough @mcharg. Maybe we can build something into our beta study on how people are using these controls and if it makes sense for people to get what they want. My instinct is to do something more obvious/different in some way, but it might not be necessary.
