### ISSUE TITLE
Data for production nationwide summary is not matching, this example is FY 19 Gas

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/nrrd#489]
Data for production nationwide summary is not matching, this example is FY 19 Gas 
![image](https://user-images.githubusercontent.com/40175688/83179948-f19d7200-a0df-11ea-9d52-a95c17ee446a.png)

_Originally posted by @Maroyafaied in https://github.com/ONRR/nrrd/pull/481#issuecomment-635524375_

The nationwide summary is breaking data out by land_category for this and should be.

**Comment by mojobnichols** [comment]
Fixed in:  https://514-otherproduction.app.cloud.gov/explore/

**Comment by Maroyafaied** [comment]
This is fixed.
