### ISSUE TITLE
State GOMESA page links are broken

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#494]
Since we no longer have state pages, we'll need to update these to display either Explore Data or the Query Tool with the appropriate state and disbursements selected.
https://update-disbursed-link.app.cloud.gov/how-revenue-works/gomesa
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9bd5a1d6-cde3-4294-917b-87b73b78561b)

**Comment by mcharg** [comment]
I'm removing the links, for now, but will keep this open to put links back in once Explore Data and/or the Query Tool have the ability to link to the state.

**Comment by jennmalcolm** [comment]
Maybe the first set of links should go to explore for that state, and the second set should go to the query tool with disbursements and GOMESA selected?

**Comment by jennmalcolm** [comment]
Use query tool since we don't have a GOMESA filter on explore data

**Comment by jennmalcolm** [comment]
@mcharg I'm going to change this issue and put you to help figure out where the links should go instead of me.

**Comment by mcharg** [comment]
Data type: Disbursements
Source: GOMESA Offshore
State/offshore region: [the state the link is for]
Group by: County

![image](https://user-images.githubusercontent.com/38465926/87984499-0e36a480-caa8-11ea-9ba0-03a71c7036a4.png)

**Comment by mcharg** [comment]
@jennmalcolm Do we just want to show the current year or a range?

**Comment by mcharg** [comment]
@jennmalcolm Actually, if we don't have the FY20 numbers in the query tool yet, do we even want to link there?

**Comment by jennmalcolm** [comment]
No I guess not @mcharg. Even when we do get monthly data in the query tool, we will never be able to incorporate the data into the query tool in time for the press releases. We could find a place on the GOMESA page to link to the query tool with GOMESA filtered for past years, and we could just hard code the county/parish 2020 numbers into the GOMESA page just like we did for states?

**Comment by mcharg** [comment]
@jennmalcolm What about something like this?
https://f47xcw.axshare.com/#g=1&p=gomesa

**Comment by mcharg** [comment]
Created #704 to build these changes.
