### ISSUE TITLE
Explore disbursements data link on homepage is opening up to revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#495]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/30817909-1042-4759-8326-983e0b9c173e)
URL: https://dev-nrrd.app.cloud.gov/explore/#federal-disbursements

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1a92357f-f217-4a18-b800-e9c480973460)

**Comment by mcharg** [comment]
URL should be: https://453-productionoffshoredata.app.cloud.gov/explore?dataType=Disbursements

**Comment by jlouis-onrr** [comment]
@mcharg, believe this one went out too with the latest PR that was merged in

**Comment by mcharg** [comment]
Looks good.
