### ISSUE TITLE
Monthly disbursements and production bar charts are missing the year in the table

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#502]
We fixed it for revenue, but not for disbursements and production.

Revenue (correct):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4a8dad7f-8a0f-434c-ac27-63559ca2869f)

Disbursements (missing year):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ab411715-f994-4eab-bb1a-b4e9d230d6a9)

Production (missing year):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/424bb634-844d-47e8-8cfd-fe2aaf2dba5e)

**Comment by jennmalcolm** [comment]
Fixed in disbursements, but still a problem in production.
