### ISSUE TITLE
County disbursement summary cards showing "no disbursements"

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#513]
![image](https://user-images.githubusercontent.com/39419003/83429265-c7122880-a401-11ea-93e0-5d6120912f8c.png)

There is the correct summary number at the top but then the card reads "no disbursements"

**Comment by jennmalcolm** [comment]
@jlouis-onrr could you fix this pretty easily? I would like to get it into the soft launch if possible. It seems to me it is rather mis-leading.

**Comment by mcharg** [comment]
Related to #417 on Native American card
