### ISSUE TITLE
Top location production data for "other" is wrong

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#514]
It seems that the sum of the other locations is calculating wrong. 
![image](https://user-images.githubusercontent.com/40175688/83430550-14d36480-a3f3-11ea-8983-985bbfb3f0fe.png)

**Comment by mojobnichols** [comment]
I suspect this was because of duplicates if so 512 should fix it.

**Comment by Maroyafaied** [comment]
it looks like it fixed it for the state cards but the nationwide card other is wrong. I did it for oil FY 19 and the other should be 34,057,0360 and it's showing 59,778,046

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/83452659-5b868600-a416-11ea-94cb-09cbd24f2784.png)

**Comment by Maroyafaied** [comment]
The original issue is for production but I saw the same issue happen in revenue , the pic above is showing Colorado.

**Comment by Maroyafaied** [comment]
Looks like it's fixed for both both production and revenue. Thanks
