### ISSUE TITLE
Wrong data on detail cards - revenue

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#515]
The county detail cards are taking state data. This example below, a bunch of counties took the commodity data from CO. I first opened the counties (testing one-by-one) when CO was still open, and the data on the cards was correct at that point. Then, after I closed the CO card, the newly opened card wen to the CO data. I tried the example again with TX. I opened TX and three counties. The data looked fine. When I closed the TX card, the first county that had been right next to TX went to the TX numbers for both the commodity and revenue type data, but the other two remained ok.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/4777d35f-e2fa-49ce-91d0-d40bf1cb67d3)

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/37b577c9-6fb4-4850-a6e8-53d674b91a08)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/7e8f8306-c496-4529-be8a-9fd928c2583e)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/483a5953-f179-4b80-a1d5-5c6b9a16ad88)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/3a9ca532-4032-42d8-8a6b-9ab25ecb0f88)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/67002765-c87b-4ee8-bbfc-5963baddf954)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/d1ed392a-270f-42bd-9292-fc5a591b4425)

**Comment by mojobnichols** [comment]
Corrected
