### ISSUE TITLE
County data wrong in 2003

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#523]
Maybe this is related to #515, but I found that Yuma County CO data is wrong for 2003.  I checked a few other counties for 2003 that looked right, and I checked a few other years for Yuma County, and those looked right too.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/63a31f17-de61-4735-9817-994a74a4afab)

**Comment by mojobnichols** [comment]
So it would appear that  2003 is loaded twice.   Best guess is I started it and then restarted it (network, or I saw something wrong and forgot to clear data).   It will be easiest to fix by reloading, but first I will make a copy of sandbox to dev then work in sand box to reload revenue
