### ISSUE TITLE
Replicate logic from current query tool around selecting state for disbursements

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#533]
Currently, the state filter and grouping options only show up if you select State as the recipient.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cbc572b2-7682-4c49-8466-245079bc7158)

**Comment by mcharg** [comment]
Also applies to county.

**Comment by jennmalcolm** [comment]
closing in favor of #666

**Comment by mcharg** [comment]
Reopening because this is different from the issue with #666.  It doesn't make sense to pick a state unless you have "state and local governments" selected as recipient because that's the only recipient that has location data.

Also, the query tool is currently labeling the "state and local governments" recipient as "county", which isn't accurate.

**Comment by mcharg** [comment]
See #686 for solution
