### ISSUE TITLE
Write blog post about card sorting using GitHub

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#538]

**Comment by mcharg** [comment]
Draft (limited access):
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B285088A2-6BC2-4D70-9499-6F16EF06092E%7D&file=Card%20Sorting.docx&action=default&mobileredirect=true

@jennmalcolm @lpgoldstein Can you please review?

**Comment by jennmalcolm** [comment]
I reviewed and added my comments and suggestions.

**Comment by mcharg** [comment]
@jennmalcolm I addressed your comments.  This is now waiting for the new blog repo to finish being setup to get posted.

**Comment by mcharg** [comment]
Created a new issue for this sprint to publish.
