### ISSUE TITLE
Be consistent with including mixed exploratory

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#543]
The nationwide federal card production total in not including mixed exploratory but the state cards production total is including mixed exploratory. 
![image](https://user-images.githubusercontent.com/40175688/83779192-df27b900-a648-11ea-9268-75134069a8b2.png)

**Comment by jennmalcolm** [comment]
I don't think it should go into Nationwide federal since it is not necessarily federal. I'm unsure if it should go into the states, but I know there was already some discussion about that.

**Comment by jennmalcolm** [comment]
I might suggest that we have a card just for mixed exploratory, but that might be overkill--unless we've actually seen users looking for that information specifically.

**Comment by Maroyafaied** [comment]
We decided to keep mix exploratory volume included in the state card and counties and exclude it from the National Federal card.  We can explore in the future adding a mixed exploratory card option if we hear from users that it's a need.
