### ISSUE TITLE
Plan user interviews on beta site

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#564]

**Comment by lpgoldstein** [comment]
Draft doc https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/EVN1qq2S08REmLQgpQl59e4BEiZq2oH1FjwBwbX-cIw5qA?e=iSmoJK @Maroyafaied @mcharg

**Comment by mcharg** [comment]
@lpgoldstein I reviewed and commented in the doc.

**Comment by Maroyafaied** [comment]
@lpgoldstein I added my comments. Thanks!

**Comment by lpgoldstein** [comment]
@Maroyafaied @mcharg Thanks for your input - incorporated suggestions and reworked a bit.

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
