### ISSUE TITLE
Make sure we have redirects from how-it-works to how-revenue-works pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#566]
So, we don't break SEO when we have the hard launch.

**Comment by jennmalcolm** [comment]
@lpgoldstein to come up with list of how it works links that need redirects

**Comment by jlouis-onrr** [comment]
@lpgoldstein, @mcharg, I did a crawl across https://revenuedata.doi.gov/ and came up with the following urls that exist for 'how-it-works':

/how-it-works/revenues/
/how-it-works/ownership/
/how-it-works/coal/
/how-it-works/onshore-oil-gas/
/how-it-works/onshore-renewables/
/how-it-works/minerals/
/how-it-works/federal-revenue-by-company/
/how-it-works/land-and-water-conservation-fund/
/how-it-works/historic-preservation-fund/
/how-it-works/
/how-it-works/audits-and-assurances/
/how-it-works/aml-reclamation-program/
/how-it-works/coal-excise-tax/
/how-it-works/offshore-oil-gas/
/how-it-works/offshore-renewables/
/how-it-works/gomesa/
/how-it-works/federal-laws/
/how-it-works/federal-reforms/
/how-it-works/native-american-ownership-governance/
/how-it-works/native-american-production/
/how-it-works/native-american-revenue/
/how-it-works/native-american-economic-impact/
/how-it-works/disbursements/
/how-it-works/reclamation-fund/

all redirects worked and have a corresponding url in beta, EXCEPT for the following urls:
'/how-it-works/federal-revenue-by-company/'
'/how-it-works/land-and-water-conservation-fund/'
'/how-it-works/historic-preservation-fund/'
'/how-it-works/reclamation-fund/'

is it possible these haven't been migrated over or maybe they are housed under a new url or location?

**Comment by mcharg** [comment]
Revenue by company hasn't been migrated yet.  It's on the P2 list to add it.  We could redirect it to the download page until we get the data into the database and the page back up. https://beta-nrrd.app.cloud.gov/downloads/federal-revenue-by-company/

Looks like the fund names are using abbreviations for the others:
https://beta-nrrd.app.cloud.gov/how-revenue-works/lwcf
https://beta-nrrd.app.cloud.gov/how-revenue-works/hpf
https://beta-nrrd.app.cloud.gov/how-revenue-works/reclamation

**Comment by lpgoldstein** [comment]
These look good! closing issue
