### ISSUE TITLE
Fix capitalization for proper and common nouns, disbursements trends

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#568]
This pull request changes did not make it over the NRRD repo.

https://github.com/ONRR/doi-extractives-data/pull/4876

Changes capitalization in Disbursements trends
Changes "Reclamation fund" to "Reclamation Fund" because it's a proper noun
Changes "Other Funds" to "Other funds" because it is not a proper noun

**Comment by mojobnichols** [comment]
Fixed in PR

 https://github.com/ONRR/nrrd/pull/604

PREVIW: 

https://439-addproductionunits.app.cloud.gov/?tab=tab-disbursements

**Comment by mcharg** [comment]
@mojobnichols This appears to be fixed in dev, but it's not in a milestone.  Should it go in this sprint?
