### ISSUE TITLE
Add query production link for Native American production

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#572]
There's a link to query Native American production that's not on the beta site 

https://beta-nrrd.app.cloud.gov/how-revenue-works/native-american-production/

![image](https://user-images.githubusercontent.com/40175688/84181425-21386c80-aa46-11ea-97a8-e0dbd39e307f.png)

**Comment by jennmalcolm** [comment]
Also, do the same for revenue here https://beta-nrrd.app.cloud.gov/how-revenue-works/native-american-revenue/

**Comment by mcharg** [comment]
Added #684 for adding the Native American land type param
