### ISSUE TITLE
Review and publish Annie's blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#587]
Draft: https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B8BFD6D97-ABD7-4420-AA86-196F8E17E184%7D&file=My%20Bog_Virtual%20Student%20Federal%20Services%20(1).docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@jennmalcolm @lpgoldstein The draft is ready for you to review.

**Comment by lpgoldstein** [comment]
@mcharg Looks great. Another helpful reference for future projects.

**Comment by jennmalcolm** [comment]
I reviewed the blog and made a few changes and one comment.
