### ISSUE TITLE
Clean up query tool styling

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#592]
To match the rest of the site.

**Comment by jennmalcolm** [comment]
What is the "clear selected" choice for in the data type dropdown. It's confusing, since it just takes you back to the revenue data.

(https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/3f1ed7c2-7a48-4751-b35f-7d608fb82b36)

**Comment by jennmalcolm** [comment]
Maybe just say "Select a single state to view" to fit this message better. Also, State and County should not be capitalized.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/8e1fbfcf-83c6-4165-9e2d-7c3e74a4ab9a)

**Comment by mcharg** [comment]
Updated design:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5f848dc0-1ea8-41e7-8f29-3b418ebf9d97)
