### ISSUE TITLE
Write and send email to people who participated in user research about the beta site

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#594]
We did this before when we launched the new homepage as a way to thank participants and let them know what we're working on to participate in future studies.

**Comment by mcharg** [comment]
Draft email: https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B25234456-11A6-4B91-9DA9-C9A6B0642746%7D&file=Beta%20Thank%20You%20Email.docx&action=default&mobileredirect=true

@lpgoldstein @Maroyafaied Please review and make edits.

**Comment by Maroyafaied** [comment]
@mcharg it looks great, I made one small comment.

**Comment by lpgoldstein** [comment]
@mcharg looks good. I really like how you have specific details and a call to action for future studies.
