### ISSUE TITLE
Explore Data: Disbursements more ways to explore links

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#60]
Decide what the links are and where they go and implement.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1c646d78-6f6e-4487-b639-2b66c83b27bd)

**Comment by mcharg** [comment]
Final links:

[Query disbursements data](https://dev-nrrd.app.cloud.gov/query-data/?dataType=Disbursements)
[Downloads & documentation](https://dev-nrrd.app.cloud.gov/downloads/#Disbursements)
[How disbursements work](https://dev-nrrd.app.cloud.gov/how-it-works/#disbursements) - Will need to verify link after being brought over from cloud.gov.

**Comment by jlouis-onrr** [comment]
@mcharg You can see the new explore links in the following branch

https://60-disbursementsmorewaystoexplorelinks.app.cloud.gov/explore

**Comment by mcharg** [comment]
@jlouis-onrr Looks good.
