### ISSUE TITLE
Review and update LWCF

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#601]
some context from Jim:

This recent news , when POTUS signs the bill into law, will provide full funding , ie allowing/requiring NPS and others to spend all the $900m we deposit. This is outside ONRR’s control but an important update to the narrative we have put out there. 

Please track that, check my facts, and plan to include In a future nrrd release? Thanks, Team

https://www.outsideonline.com/2414708/great-american-outdoors-act

The bill itself: https://www.congress.gov/bill/116th-congress/senate-bill/3422

**Comment by Maroyafaied** [comment]
@jennmalcolm please review the draft paragraph. I put it under Annual Funding and deleted what was written before. https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={2acb53d5-53ab-4058-84d5-89e737f15861}&action=edit

**Comment by jennmalcolm** [comment]
@Maroyafaied the congress.gov website does not confirm that this bill was passed by the senate, only introduced, so I don't think we should delete what is on the page about the funding.

Can you find somewhere else to confirm that the bill passed in the senate? Even if it did, I don't think it has been passed by the house and signed by the president to become law. The House does have a companion bill https://www.congress.gov/bill/116th-congress/house-bill/3195?q=%7B%22search%22%3A%5B%22hr+3195%22%5D%7D&s=1&r=1. It doesn't look like that one has passed either.

Perhaps keep what we have but just add something to the bottom to summarize the pending legislation.

**Comment by Maroyafaied** [comment]
@jennmalcolm it shows here that it passed the senate https://www.congress.gov/bill/116th-congress/house-bill/1957. It has not passed the house.  And the companion bill has only been introduced. Let me know if I should still just summarized that it's pending  since it's not passed by the house.

**Comment by jennmalcolm** [comment]
Look into next sprint because the House may be voting on it this week, and we might be able to provide the update if the President signs.

**Comment by jennmalcolm** [comment]
The president is scheduled to sign the act tomorrow (8/4), so we can confirm that and then update.

**Comment by Maroyafaied** [comment]
@jennmalcolm please review. https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc=%7B2acb53d5-53ab-4058-84d5-89e737f15861%7D&action=edit

"On August 4, 2020, the president signed the [Great American Outdoors Act H.R. 1957)]( https://www.congress.gov/bill/116th-congress/house-bill/1957) bill into law which permanently and fully funds the Land and Water Conservation Fund at $900 million a year. The bill also provides funding to address a backlog of maintenance needs for national parks and other public lands."

**Comment by jennmalcolm** [comment]
@Maroyafaied I reviewed and made some suggestions. I looked at the bill, and it looks like the funding will not always be 900 million. It will be what the formulas result in up to the $900 million, so I made that change. For example, since offshore revenues are down this year, I think the formulas may result in less than the $900 million limit.

  Please review and see if what I wrote is clear.

**Comment by Maroyafaied** [comment]
@jennmalcolm thank you for clarifying. I'll create a PR for the changes.
