### ISSUE TITLE
Consider a new label for "oil & gas"

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#610]
We've seen many times in user interviews that users aren't sure whether this is adding up oil plus gas or something separate and if it's something separate why it is separate.  We should clarify it as "oil & gas (non-royalty)" or whatever the accurate clarification is.

**Comment by mcharg** [comment]
This is more prominent with the new order in the commodity drop-down.

**Comment by mcharg** [comment]
We want to change the label to: Oil or gas (pre-production)

@jennmalcolm Are you good with that?

**Comment by jennmalcolm** [comment]
Ok works for now
