### ISSUE TITLE
Ability to search counties without putting comma

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#612]
One participant in a user study, was not able to search for county without typing the comma on the search location drop down option on card. 
![image](https://user-images.githubusercontent.com/40175688/85762338-dcad0200-b6d0-11ea-8122-a74e72b1e87c.png)

**Comment by jennmalcolm** [comment]
It would also be nice if the state appeared first instead of all the counties when you type in a state name.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/0b2b0a1c-43e1-4870-b9e0-977a4fc233cb)
