### ISSUE TITLE
County map label is weird

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#613]
This is the Colorado card in beta.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f7eb5a58-7478-4867-8c28-91408eac52e1)

**Comment by jlouis-onrr** [comment]
@mcharg, can you reattach the image on this issue?  I'm not able to view or see it.

**Comment by mcharg** [comment]
Fixed in #614
