### ISSUE TITLE
Explore different coloring/patterns for circle charts

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#619]
That are more accessible and easier for sighted people to differentiate.

**Comment by mcharg** [comment]
I think we have two options for this. @jlouis-onrr 

1. Play with patterns with the colors we already have.  Axure can't do patterns, so I think it will be easier to test them out in D3 than to figure it out in Illustrator.

2. Try using this palette for all the circle and bar charts.  Since those charts aren't showing a range of values, they don't need to be a single hue.  This palette goes from dark to light with complementary hues, so it's still accessible-ish in black and white, but has different colors for sighted users.  We haven't seen users really notice the scheme behind the different color palettes for different data types, so we may be able to use one palette for all the charts.  We could also play with adding patterns to this palette.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/91266433-9f44-4ce2-8c60-dde32db873e4)

What it looks like for a circle chart:
![CircleChart.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/826e24ce-9978-4cba-8715-79b1e37e5f7e)

**Comment by mcharg** [comment]
Horizontal bar chart with a 4-color version of the palette using the same end point colors.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8481c971-f45e-4692-8dfc-5a1ac8687748)

**Comment by mcharg** [comment]
We should also consider adding white dividers between sections on the bar charts.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d313d63b-eb80-4cfd-829e-1901532636e9)

**Comment by jlouis-onrr** [comment]
@mcharg, for the county example.  Are you thinking about applying the same color pattern for the state and county maps as well?

**Comment by mcharg** [comment]
@jlouis-onrr I think the maps are fine as is.

**Comment by jlouis-onrr** [comment]
@mcharg, https://950-siteheader.app.cloud.gov/ now has the dark header with mobile and the circlecharts and horizontal charts using this color range palette

**Comment by mcharg** [comment]
@jlouis-onrr Can you specify to use the same color for the same thing in each graph.  For example, there are two different colors for onshore in the disbursements nationwide summary.
![image](https://user-images.githubusercontent.com/38465926/95331159-917dc000-0877-11eb-9ff4-9b09258fb409.png)

**Comment by mcharg** [comment]
This is what I get when I put 7 colors into the pallette generator with the same start and end colors as before.  They're about a 1.4:1 contrast between shades where we had about 1.5:1 before.  There isn't a standard amount of contrast for charts for accessibility, so it's hard to gauge whether it's enough.
![image](https://user-images.githubusercontent.com/38465926/95331719-65167380-0878-11eb-91d5-06376fe37426.png)

#37253c
#5e384b
#825056
#a16c5e
#b78d68
#c2b27b
#c4d99b

**Comment by mcharg** [comment]
Can we use these colors when we only have 4 in the graph?
![image](https://user-images.githubusercontent.com/38465926/95332246-246b2a00-0879-11eb-878c-33ddb53ed2a1.png)

#37253c
#825056
#b78d68
#c4d99b

**Comment by mcharg** [comment]
This is the palette generator I'm using. https://learnui.design/tools/data-color-picker.html

**Comment by mcharg** [comment]
Can the production over time charts use the color from the card header?  That way it's consistent with the lines on the joint chart below.
![image](https://user-images.githubusercontent.com/38465926/95333131-592bb100-087a-11eb-94ba-6384df487528.png)

**Comment by mcharg** [comment]
The county map should use the same greens as the nationwide map.
![image](https://user-images.githubusercontent.com/38465926/95333208-7a8c9d00-087a-11eb-82f7-a2a7d11f7c7f.png)

**Comment by mcharg** [comment]
FYI - The legend is missing from the map in this build.
![image](https://user-images.githubusercontent.com/38465926/95333357-ab6cd200-087a-11eb-8578-a396694da0a7.png)

**Comment by mcharg** [comment]
The colors in the bar charts are coming out lighter than the specified colors.  It's really hard to see the green on white.
![image](https://user-images.githubusercontent.com/38465926/95333448-cd665480-087a-11eb-89d3-0677a96c1c62.png)
