### ISSUE TITLE
Error when picking a commodity with no data for an open card

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#621]
Steps to reproduce:
- Go to production
- Pick some cards
- Switch to a commodity that doesn't exist in one of the cards
- Get error
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/87ebf3fc-cff2-4863-b5be-018be529ac15)

**Comment by jennmalcolm** [comment]
fixed
