### ISSUE TITLE
Consolidate findings for Beta Interviews

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#622]

**Comment by mcharg** [comment]
Findings spreadsheet (limited access): https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B0B6BC7E2-6443-42C2-8465-B968E2E87DDA%7D&file=Consolidated%20Findings.xlsx&action=default&mobileredirect=true
