### ISSUE TITLE
Something went wrong: switching between revenue/disbursements to production or among commodities

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#627]
When you have a location selected in revenue or disbursements and you switch to production, and there is no data for your selected area, you get a "something went wrong" error. It seems to work correctly when going between revenue and disbursements and doesn't error out but just comes up with a card with "no disbursements" message, so maybe you can just replicate that functionality. The same error messages occur when switching between commodities in production.
 
Examples to replicate problem:
1. Go to revenue, select Minnesota, then switch to production-->get error
2. Go to production, select North Dakota, change commodity to Quartz crystal-->get error

![image](https://user-images.githubusercontent.com/30806839/86637845-4b793d80-bfa4-11ea-926d-0ad392ecb73e.png)

**Comment by mojobnichols** [comment]
Introdcuded and Fixed in 439-AddProductionData.   Merged into dev closing issue
