### ISSUE TITLE
Fix so units on summary cards and legend don't run over with long unit names

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#628]
![image](https://user-images.githubusercontent.com/30806839/86638221-ea9e3500-bfa4-11ea-8132-1ced7c58f2db.png)
![image](https://user-images.githubusercontent.com/30806839/86638526-6c8e5e00-bfa5-11ea-9bca-b0689174e488.png)

Since this is probably just on this one commodity where the unit is "tons-equivalent," it's not the highest priority, but we will also have long units once we get geothermal correctly reflected.

**Comment by jennmalcolm** [comment]
ellipses with mouse over to reveal full name

**Comment by jlouis-onrr** [comment]
@mcharg, looks like this one has been fixed and is already in prod.  Could you verify this fix?

**Comment by mcharg** [comment]
It's wrapping, which I think works.
![image](https://user-images.githubusercontent.com/38465926/94043401-df37fa00-fd9a-11ea-99b1-e5c5b27ccfb5.png)
