### ISSUE TITLE
Fix geothermal units in database

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#629]
Commodities should be Geothermal - Direct Use and Geothermal - Electrical Generation. The parts in yellow should be the units.

![image](https://user-images.githubusercontent.com/30806839/86638648-b24b2680-bfa5-11ea-913b-6cfb57f3d416.png)

**Comment by jennmalcolm** [comment]
Our geothermal expert at ONRR gave me the following answer when I asked if there is a difference between direct use and direct utilization.

The short answer is:  there is no difference. The old Geothermal Payor Handbook and geothermal regulations called it Direct Utilization and the new Geothermal Payor Handbook and 2007 regulations changed it to Direct Use because that is what the Energy Policy Act of 2005 called it.

Based on this, I think we should change it all to direct use. Let's also look into combining millions of gallons and hundreds of gallons into one unit of gallons and see how that scale would affect things.

**Comment by mojobnichols** [comment]
All PR should have geothermal units now.
