### ISSUE TITLE
Communication plan for hard launch

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#639]
work with Chris to determine how to communicate new site with DOI community

**Comment by lpgoldstein** [comment]
@jennmalcolm this is ready for your review: https://doimspp-my.sharepoint.com/:w:/r/personal/goldstel_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B6B10E9DD-0B14-4006-A769-01CC8750813A%7D&file=Communications%20Plan%20for%20NRRD.docx&action=default&mobileredirect=true

We can add dates when we have a better idea about our timeline

**Comment by jennmalcolm** [comment]
I added my comments. I think it's looking good but would like to see some more things targeted to the wider DOI-community if we can think of some. If you didn't already talk to him, Chris might have some ideas.

**Comment by lpgoldstein** [comment]
@jennmalcolm I talked to Chris this morning and the social media series was his idea.
