### ISSUE TITLE
Plan user interviews for explore data

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#64]
We need to think about when we want to start showing what we're doing and what fidelity we want to show it in to users to get feedback and start recruiting storytellers.

**Comment by jennmalcolm** [comment]
Also includes recruiting participants.

**Comment by jennmalcolm** [comment]
I changed my mind and created #194 for recruiting participants. This issue will be to create the research plan.

**Comment by mcharg** [comment]
@jennmalcolm Should we also plan on testing the new query tool at the same time or should we plan a separate study for that.

**Comment by jennmalcolm** [comment]
I think we should focus on explore data as we should try to aim this round of research at storytellers/domain learners, which are not the target audience for the query. We could potential show the query tool to these people and ask a couple of limited questions around their potential use of it, but I think it would benefit us to have a separte round of research with question answerer types on the query too.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein the interview guide is ready for your review https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B03190668-87A8-4CD2-BE2F-9B1939A1F978%7D&file=Explore%20Data%20Interview%20Guide.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@Maroyafaied What you have is a great start.  I added some comments to the plan.

**Comment by Maroyafaied** [comment]
@mcharg thank you, I have incorporated your comments. @jennmalcolm if you have to review it, let me know if you have comments or changes you'd like me to make.

**Comment by mcharg** [comment]
@Maroyafaied I took a look at your edits and they look good.

**Comment by jennmalcolm** [comment]
Looks good. I just added a couple comments.
