### ISSUE TITLE
Explore Data: Make it clear what location search is for and how to add cards

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#646]
Participants:
* expected counties that didn't have data to come up in the search.
* didn't understand that the search was for adding cards.
* tried typing "United States" into the search to get the nationwide card.

In addition, two participants said they didn't know what a card was, so we should explore calling them something else.

**Comment by jennmalcolm** [comment]
Do some testing on new design with compare button to see if this helps before making more changes.

**Comment by mcharg** [comment]
@mojobnichols suggested changing the field label to "Add state or county".

**Comment by mcharg** [comment]
Proposal for removing the "card" label:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c71906dd-44ae-4dba-a5a1-3cc832632f2e)
