### ISSUE TITLE
Explore Data: The explore more button looks like a drop-down

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#647]
One participant pointed this out in user research and several participants didn't know there was more than the map, so we should explore other visuals.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/207251b1-87ca-483d-8676-1f8d51c273b1)

The arrow does look just like the ones on our drop-downs:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c67d894a-41ee-44bb-a187-be37beded109)

**Comment by jlouis-onrr** [comment]
@mcharg, maybe moving the arrow from the right to underneath and centered below the text and maybe even slightly animated top to bottom movement?

**Comment by mcharg** [comment]
@jlouis-onrr A quick search for scroll down arrows has lots using the double chevron and many in a circle like this:
![image](https://user-images.githubusercontent.com/38465926/87471648-b7832380-c5ec-11ea-91eb-0bba9b1e55a3.png)

**Comment by jlouis-onrr** [comment]
what about something like this?  Scroll down/Scroll up label instead of upper arrow and no outer border

![scrolldownjpg.jpg](https://images.zenhubusercontent.com/5d893e494c2d9e0001fa99ad/58b4d6fe-23dd-4701-b486-0b472c3a0720)

**Comment by mcharg** [comment]
@jlouis-onrr I like it.
