### ISSUE TITLE
Add "land" or "ownership" to % federal on detail cards

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#652]
People may not know what % federal means. One participant in a user interview thought it might be the percent of revenue.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/836f1209-a09b-4df2-89b4-5c7fa7c6ae70)

**Comment by jennmalcolm** [comment]
Also, should we have 100% federal on offshore.

**Comment by jennmalcolm** [comment]
Would it be easier to do a tool tip?
