### ISSUE TITLE
Data type drop-down doesn't update when linking from explore data to query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#664]
Clicking on the link to the query tool for disbursements from explore data, brings up the disbursements data, but the data type drop-down says revenue.
![image](https://user-images.githubusercontent.com/38465926/87795500-22fc0980-c816-11ea-8f79-ccf8383d854b.png)

Clicking on the link to the query tool for production from explore data, brings up the production data, but the data type drop-down says revenue.
![image](https://user-images.githubusercontent.com/38465926/87795657-63f41e00-c816-11ea-870d-c7b8f1725164.png)

**Comment by jennmalcolm** [comment]
This seems to be the same as #662. Which one do you want to keep @master12?

**Comment by master12** [comment]
Lets keep this one. I will close 662
