### ISSUE TITLE
Rounding in Query Tool

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#679]
Part 1: Why do we have more decimals than just cents in revenue file?

In comparing a pivot table from the download file to the download from the query tool, many number are off from $0.01 to $0.05.

This might have something to do with where we are rounding for the query tool, but I also think that a lot of it might be because in the revenue files, we go out more than to the cents decimal. I don't understand why this would be, and we should ask DORC about that.
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/67e58cb2-3853-474e-8cbe-25a88d6f33f7)

Part 2: Should we be adding amounts rounded to the dollar to get grand total or adding all amounts to the cent and then rounding to the dollar for the grand total? We seem to be doing the first right now, which results in different totals in Excel and query tool. If we did the latter, they would match Excel and Query tool, but if you added all amounts on the screen, you wouldn't arrive at the same total as displayed. 

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/56eca9ac-f61b-4d04-838c-0cdb620a8a49)

**Comment by jennmalcolm** [comment]
This is probably due to allocations, but I think we should ask DORC to round to the cents.

**Comment by Maroyafaied** [comment]
@mojobnichols round to nearast cents in database. @master12 look into code to round to cents.
