### ISSUE TITLE
Add Land Type = Native American param to query tool url for Native American production and revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#684]
The links added in #680 from the How Revenue Works pages need the parameter.

**Comment by master12** [comment]
DOne

**Comment by mcharg** [comment]
@master12 This isn't working in dev.

**Comment by mcharg** [comment]
@master12 Links are on these pages:
https://beta-nrrd.app.cloud.gov/how-revenue-works/native-american-production/#Production-on-Native-American-land
https://beta-nrrd.app.cloud.gov/how-revenue-works/native-american-revenue/#Revenue-data
