### ISSUE TITLE
Query tool - state/offshore changes 

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#696]
In the query tool, all Native American production will be "not tied to a location". That might cause confusion. The production is tied to a location; we just don't publish that data. Maybe we should not have that in the state/offshore dropdown for production.

Also, for disbursements, "not tied to location" gives everything besides the state data. We should think about use state rather than state/offshore in the disbursements since no offshore areas get disbursements. While the category is state/offshore, no offshore areas will show up in the filters. I also find the "not tied to a location" confusing for disbursements.

**Comment by mcharg** [comment]
#688 addresses the disbursements filter label

**Comment by mcharg** [comment]
#533 would address the not tied to a location issue for disbursements.

**Comment by mcharg** [comment]
For Native American production, what if we labeled it "Location not published"?

**Comment by jennmalcolm** [comment]
I think"location not published" works.

**Comment by mcharg** [comment]
Database change
