### ISSUE TITLE
Sort Grouping by state/offshore differently

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#697]
I think keeping all offshore together and all states together would make more sense than alphabetizing them.

![image](https://user-images.githubusercontent.com/30806839/88226481-20e0e300-cc3a-11ea-80c6-904fb3150881.png)

**Comment by mcharg** [comment]
I agree.

**Comment by mojobnichols** [comment]
![image.png](https://images.zenhubusercontent.com/5d1a3e771449416ed8985985/746d53eb-c789-4553-82ef-fe6b776f4a68)

I added column it sorts offshore first then state  followed by state county alphabetical
