### ISSUE TITLE
Fix colors not matching on circle chart and the labels on the table

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#698]
The colors on the circle charts and the table labels don't match for counties. It seems like this happens where there is 2 or less counties with productions.

![image](https://user-images.githubusercontent.com/40175688/88234532-4e2b9200-cc36-11ea-9f76-68b1770a88b0.png)

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/88235090-5f28d300-cc37-11ea-8a4a-3b1cd38341a0.png)

**Comment by mojobnichols** [comment]
Fixed in the PR:  https://github.com/ONRR/nrrd/pull/709
