### ISSUE TITLE
Spacing on downloads pages

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#707]
The spacing isn't quite right in spots on the downloads pages. We need to check all of the pages and apply consistent spacing.

Example - should have spaces between each definition
![image](https://user-images.githubusercontent.com/30806839/88725563-4bc7ad00-d0fa-11ea-8f54-e7242d0e12a4.png)

Might need to use html in the MDX files to get the spaces?

**Comment by mcharg** [comment]
Production by month has an extra indent:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/59782b55-35ce-425d-8656-16d25b9ac75e)

**Comment by Baymatt** [comment]
Went through all the pages and added spacing and fixed the extra indent in production by month. Pushed the changes to a branch named update-downloads-spacing and created a pull request for review.
