### ISSUE TITLE
Spark line issue

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#710]
1. The spark lines on revenue top commodities don't reflect the selected year.
![image](https://user-images.githubusercontent.com/30806839/88930815-fd292880-d249-11ea-8e83-3f9f924873fc.png)

**Comment by mcharg** [comment]
It's only doing this sometimes.

**Comment by mojobnichols** [comment]
Should be fixed in PR https://github.com/ONRR/nrrd/pull/736


https://624-zoominteration.app.cloud.gov/explore/
