### ISSUE TITLE
Selected period not transferring to disbursements and production

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#711]
Going to disbursements or production data does not keep the selected period (CY if selected and year). It always goes back to FY 2019. Going to revenue does keep the selection from the other data types.

**Comment by mcharg** [comment]
We need to define how we want this to work.  Currently, it's only keeping the selected cards and the period and commodity aren't shared.  If you go back to a dataset, it keeps the date you last had for that dataset.

**Comment by jennmalcolm** [comment]
After discussing with team, we will drop this issue. Due to the filters varying between data types, this would be complicated to implement, and we haven't seen other users confused by this. We will watch to see if our current implementation causes any problems for users.
