### ISSUE TITLE
Firefox is displaying the wrong month label for revenue and disbursements trends

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#728]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8fe0b88d-0cb7-4270-aa43-e2dc513c41af)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/85710802-20fb-4fbb-a84a-c14b7e28e760)

**Comment by jennmalcolm** [comment]
Also, bar graphs are wrong.

**Comment by mojobnichols** [comment]
![image.png](https://images.zenhubusercontent.com/5d1a3e771449416ed8985985/938e0eb9-9c94-4c90-afc4-a3ddb522f9c5)

I see this as identical to firefox

**Comment by mcharg** [comment]
@mojobnichols I'm getting June now, too, for the trends, but the months on the bar chart are all messed up.
![image](https://user-images.githubusercontent.com/38465926/89654072-178c8300-d896-11ea-8caa-eea822df8895.png)

**Comment by mcharg** [comment]
Same with disbursements.
![image](https://user-images.githubusercontent.com/38465926/89654163-38ed6f00-d896-11ea-8895-cc9b3e65180b.png)

And production is off, as well.  It should go through March 2020.
![image](https://user-images.githubusercontent.com/38465926/89654276-63d7c300-d896-11ea-9a7e-f84e985d4980.png)

**Comment by mojobnichols** [comment]
Okay we were doing an unecessary sort on data.  In chrome it had no effect in firefox for months it reversed the sort.    Since it was uncessary I removed it.


Fixed in PR https://github.com/ONRR/nrrd/pull/709
