### ISSUE TITLE
Create data checklist

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#735]
to utilize when reviewing PRs

**Comment by Maroyafaied** [comment]
@jennmalcolm @mcharg @lpgoldstein please review the new data check list, feel free to make any changes. 

https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={30716273-a7fb-41a4-86e7-5357c8fd3693}&action=edit

**Comment by lpgoldstein** [comment]
@Maroyafaied I really like how you made it easy to follow. I added something about downloads in the query section and basic edits. Thank you!

**Comment by mcharg** [comment]
@Maroyafaied Looks good.  I added some comments in the doc.

**Comment by jennmalcolm** [comment]
This looks good. Thanks for all the work, @Maroyafaied. I added a couple small comments. 

Could you add this to the Q/A issue? We may want to wait to start our thorough data checks until after we get Mojo to update the database with the newest monthly data, but once he does that, we can go through this checklist before the hard launch.  This will help a lot. If we notice anything missing while doing our reviews, we can add it. We should also get this in the Wiki.

**Comment by mcharg** [comment]
Should this be a wiki page, so it's easy to copy and paste the markdown into new QA issues?

**Comment by lpgoldstein** [comment]
Yes!

________________________________

**Comment by Maroyafaied** [comment]
@mcharg @jennmalcolm sure, I'll add it to the Q/A and wiki.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein @jennmalcolm the checklist is not on the wiki and also on the Q/A issue. https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#updating-data-files
