### ISSUE TITLE
Explore Data: Revenue links to other ways to explore

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#75]
Define links and where they go and build.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8d2a524a-b344-42ed-8f86-0d97b0632663)

**Comment by mcharg** [comment]
Pulling this into this sprint, since @jlouis-onrr is working on it now.

**Comment by jennmalcolm** [comment]
This issue is for deciding what the links should be.

**Comment by mcharg** [comment]
Final list of links:

[Query revenue data](https://dev-nrrd.app.cloud.gov/query-data/?dataType=Revenue)
[Downloads & documentation](https://dev-nrrd.app.cloud.gov/downloads/#Revenue)
[How revenue works](https://dev-nrrd.app.cloud.gov/how-it-works/#revenues) - I followed the same url pattern as the old site, but the link will need to be verified after being brought over to cloud.gov
[Revenue by company](https://dev-nrrd.app.cloud.gov/how-it-works//federal-revenue-by-company/2018/) - I followed the same url pattern as the old site, but the link will need to be verified after being brought over to cloud.gov

@jlouis-onrr Do you want to put in the links as part of this issue or should we create a new one for implementing?

**Comment by jlouis-onrr** [comment]
the final list of links have been committed within branch: #178

Check it out here: https://178-addplaceholderzoneforcomparison.app.cloud.gov/explore/

**Comment by mcharg** [comment]
Looks good.
