### ISSUE TITLE
Plan user testing on hard launch

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#766]

**Comment by mcharg** [comment]
Plan drafted.  @Maroyafaied @lpgoldstein Can you please review?
https://teams.microsoft.com/l/file/7A62FD88-2A43-48D2-8CF8-F762C9ADDF0B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F34_new_site%2FStudy%20Plan%20and%20Interview%20Guide%20Hard%20Launch.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg I added my comments/changes.
