### ISSUE TITLE
Explore Data: Design revenue full details, nationwide

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#77]
Define what charts to display and create a new scope for each chart.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f780285c-d198-47dc-9326-fd75a2be1e48)

**Comment by mcharg** [comment]
@jennmalcolm We should review what we have so far for this in sync up next week.

Revenue by type: https://935313.axshare.com/#g=1&p=revenue_by_type
Federal revenue by commodity and type: https://935313.axshare.com/#g=1&p=federal_revenue_by_commodity_and_type
Native American revenue: https://935313.axshare.com/#g=1&p=native_american_revenue_by_commodity_and_type
Revenue by company: https://935313.axshare.com/#g=1&p=revenue_by_company
Revenue by location: https://935313.axshare.com/#g=1&p=revenue_by_location
Revenue by month: https://935313.axshare.com/#g=1&p=revenue_by_month
Commodity bar charts: https://935313.axshare.com/#g=1&p=commodity_bar_charts
Nationwide ownership: https://935313.axshare.com/#g=1&p=land_ownership

**Comment by jennmalcolm** [comment]
Ok, thanks, @mcharg.

**Comment by mcharg** [comment]
Final set of charts: https://935313.axshare.com/#g=1&p=revenue_default

**Comment by mcharg** [comment]
Created new issues for each zone to be built.

Placeholder comparison zone: #178
National revenue summary: #179
Top locations concepts: #180
Top commodities concepts: #181
Revenue by company: #182
