### ISSUE TITLE
Broken link: State submerged lands 

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#776]
Location: Ownership page
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f3569484-82b4-4169-828e-7aa1e753a10a)

Link:https://www.boem.gov/uploadedfiles/submergedla.pdf

404 error:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1b62c59d-9b70-4403-b345-b54ea3071fa9)

**Comment by mcharg** [comment]
This page is the closest I could find to relevant content on the BOEM site, but it also has a broken link to the act.
https://www.boem.gov/oil-gas-energy/leasing/federal-offshore-lands

**Comment by mcharg** [comment]
Would this link work?
https://coast.noaa.gov/data/Documents/OceanLawSearch/Summary%20of%20Law%20-%20Submerged%20Lands%20Act.pdf

**Comment by Maroyafaied** [comment]
https://www.boem.gov/sites/default/files/uploadedFiles/BOEM/Oil_and_Gas_Energy_Program/Leasing/Outer_Continental_Shelf/Lands_Act_History/submerged.pdf
