### ISSUE TITLE
Broken link: Mineral Materials Act

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#780]
Location: Federal Laws page
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1e5ca73f-22a0-46a2-89d6-05ced2793818)

URL: http://legcounsel.house.gov/Comps/Act%20Of%20July%2031,%201937-(Materials%20Act%20Of%201947).pdf

404 page:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e2e9cbd8-6c25-45e4-a72f-6dbebaa5f5c1)

**Comment by mcharg** [comment]
Would this link work? https://doi.opengov.ibmcloud.com/sites/doi.opengov.ibmcloud.com/files/uploads/M-36998.pdf

**Comment by Maroyafaied** [comment]
https://ecfr.federalregister.gov/current/title-43/subtitle-B/chapter-II/subchapter-C/part-3600
