### ISSUE TITLE
Broken link: Submerged lands act

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#781]
Location: Federal Laws
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5a7b3418-9248-4ae4-ba1a-21dcff89d80c)

URL: http://www.boem.gov/uploadedFiles/submergedLA.pdf

404 page:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/eafbeaab-bf7e-4041-bee3-3e423966151f)

**Comment by mcharg** [comment]
Same link as #776

**Comment by Maroyafaied** [comment]
https://www.boem.gov/sites/default/files/uploadedFiles/BOEM/Oil_and_Gas_Energy_Program/Leasing/Outer_Continental_Shelf/Lands_Act_History/submerged.pdf
