### ISSUE TITLE
Broken link: Marine Mammal Protection Act

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#783]
Location: Federal Laws
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/011d2e31-f0a8-4a75-8d67-454b5419ec01)

Link: http://www.nmfs.noaa.gov/pr/pdfs/laws/mmpa.pdf

404 page: ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c9e3d4c2-3037-4060-87f5-dea8e34e59e0)

**Comment by mcharg** [comment]
Would this link work? https://www.fws.gov/international/laws-treaties-agreements/us-conservation-laws/marine-mammal-protection-act.html

**Comment by lpgoldstein** [comment]
The link above should work
