### ISSUE TITLE
Some counties are displaying the state name in the no data text

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#803]
San Juan County, CO
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4807e9ae-7eed-4473-8529-cbe50ef3109f)

**Comment by jlouis-onrr** [comment]
this should be fixed in #802

**Comment by mcharg** [comment]
@jlouis-onrr San Juan is fixed, but Hinsdale is doing a new wonkiness.
![image](https://user-images.githubusercontent.com/38465926/90179533-917fa900-dd7b-11ea-91e9-63c24f1a8541.png)
