### ISSUE TITLE
Fix capitalization on Explore Data page

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#804]
Per the content guide, the yellow highlighted items shouldn't be capitalized
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/af6dd7b3-24c7-41de-9b57-1e385a76fc7e)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1f1aedb6-5b99-42b2-8d14-0ab1f0c40560)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5db10ebd-85e4-4cac-94f9-b92437b377aa)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fe6ed30e-9404-4bf3-9537-240aae3b9091)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0ebb174b-7800-4431-9603-9f910310076f)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/06454137-ea29-462f-a36f-3001bbcdf9cc)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2ab19663-92d3-4de1-86d6-5a885fe6bbc8)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/65d0cd3e-4d28-45b4-8c9c-df9d3225888a)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6703ebbd-8104-4bdb-a03a-7307323191fa)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d65a8a69-86ac-4c96-a079-ba7442ba9f7a)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/65a78f57-325c-41a1-8f99-ae6d540703ff)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/30ce7856-4118-4dbb-968b-80bcf41f1df3)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4759511a-9589-4414-938c-db3859e79328)

**Comment by mcharg** [comment]
@jlouis-onrr Will update the ones he can and then create a new issue for ones that need to be updated in the database.

**Comment by mcharg** [comment]
Created #921 for database fixes.

**Comment by jennmalcolm** [comment]
Same for Top recipients

![image](https://user-images.githubusercontent.com/30806839/103017021-f6f55a80-4510-11eb-8a91-dceefd0ac3d4.png)
