### ISSUE TITLE
Disbursements recipients column cuts off values

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#809]
And you can't expand.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/edd06138-c15e-448a-b234-32811d22d622)

**Comment by master12** [comment]
@mcharg You should be able to expand but I can add in a bigger default column width

**Comment by mcharg** [comment]
@master12 I was trying to drag the column when I saw the cutoff text, but it appears you can only drag on the column header.  Is it possible to extend the drag function to the whole column?
