### ISSUE TITLE
Relocate federal revenue by company data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/nrrd#82]
We should consider moving federal revenue by company data out of [How it works](https://revenuedata.doi.gov/how-it-works/#revenues) to an explore data section. 

How it works is predominantly and nominally contextual narrative, while federal revenue by company data is, well, data.

Final design: https://ug2su1.axshare.com/#g=1&p=revenue_by_company_combined

Responsive behavior should follow the same pattern as the Disbursements Summary, where the switches to a single column view at 600 px.

**Comment by jennmalcolm** [comment]
Closing this due to new shaping on explore data. This should be an item covered in #75
