### ISSUE TITLE
Create redirects for LWCF and HPF pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#826]
The urls changed, so we should have redirects to prevent 404 pages.

LWCF:
Old url: https://dev-nrrd.app.cloud.gov/how-revenue-works/land-and-water-conservation-fund/
New url: https://dev-nrrd.app.cloud.gov/how-revenue-works/lwcf

HPF:
Old url: https://dev-nrrd.app.cloud.gov/how-revenue-works/historic-preservation-fund/
New url: https://dev-nrrd.app.cloud.gov/how-revenue-works/hpf

**Comment by jlouis-onrr** [comment]
@mcharg, wasnt these the old urls, not how-revenue-works

/how-it-works/land-and-water-conservation-fund/
/how-it-works/historic-preservation-fund/

at least thats what im seeing in the config for the redirects:
`createRedirect({ fromPath: '/how-it-works/land-and-water-conservation-fund/', toPath: '/how-revenue-works/lwcf', redirectInBrowser: true, isPermanent: true })
  createRedirect({ fromPath: '/how-it-works/historic-preservation-fund/', toPath: '/how-revenue-works/hpf', redirectInBrowser: true, isPermanent: true })`

**Comment by mcharg** [comment]
They were, but there were a couple relative links from within how it works that had the how-revenue-works portion that were returning 404.

**Comment by mcharg** [comment]
The links that were broken:
https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/792
https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/793

**Comment by jlouis-onrr** [comment]
gotcha ya!
