### ISSUE TITLE
Logo is centered on iPad

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#843]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e4543ae2-f5a3-483c-8d67-5194862ea492)

**Comment by jlouis-onrr** [comment]
@mcharg, whats the ios verstion and model?

**Comment by mcharg** [comment]
@jlouis-onrr iPad 2 iOS 9.3.5

**Comment by jlouis-onrr** [comment]
@mcharg, there was some minor adjustments with media queries in #376, can you let me know if that made things better for this issue in IOS 9.3.5? 

https://preview-nrrd.app.cloud.gov/

**Comment by mcharg** [comment]
@jlouis-onrr It's still centering.
