### ISSUE TITLE
You can have multiple bars selected on iPad

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#844]
The numbers update to the new year (2016 below), but the previous selected bar stays selected (2019 below) and the year in the table is the previously selected year.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ca059132-b147-43d2-8932-a60ff98bd8ff)

**Comment by jlouis-onrr** [comment]
@mcharg, seems like this is now fixed.  I happened to notice it while testing the cutoff cards in preview.  Can you verify this as well?

**Comment by mcharg** [comment]
Will probably be moot with new trends design.
