### ISSUE TITLE
The trends year displays time on iPad

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#845]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ceff44eb-3791-4ba2-ad73-96813ac57269)

**Comment by jlouis-onrr** [comment]
@mcharg, what version was this?  Currently, not seeing in Safari or IOS 13.5.1

**Comment by mcharg** [comment]
Whatever version iPad 2 stopped letting me update at.  We can close this issue if it's not in modern browsers.

**Comment by jlouis-onrr** [comment]
Ok, I think that was IOS version 9.3.5
