### ISSUE TITLE
Review production documentation on production download page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#848]
with new production files, we need to review the data documentation to see if all products are listed

**Comment by lpgoldstein** [comment]
take out withholding section as part of this

**Comment by Baymatt** [comment]
Doesn’t contain Offshore Planning Area as a column (Not sure if this is just a extension of Offshore Region or if it had its own column at one point)

Can’t find any instances of Drip or Scrubber Concentrate in Product

Geothermal documentation for some of the units is different from the website. 
Geothermal - Direct Utilization, (gal hundreds) => Geothermal - Direct Utilization, Hundreds of Gallons
Geothermal - Direct Utilization, (MMBtu) => Geothermal - Direct Utilization, Millions of BTUs
Geothermal - Electrical Generation, (kWh) => Geothermal - Electrical Generation, Kilowatt Hours
Geothermal - Electrical Generation, (lbs, thousand) => Geothermal - Electrical Generation, Thousands of Pounds
Geothermal - Electrical Generation, (Other) => Geothermal - Electrical Generation, Other
Geothermal - Sulfur, (long tons) => Geothermal - sulfur (long tons)

Can’t find any Gold and Silver Products that have tons as unit. Can find Gold Ore with tons as unit and can find Gold (oz).

Mine Water (tons) is missing from documentation.

Not sure how important these differences are,
On documentation, Calcium Chloride (lbs), but on data => Calcium Chloride (lb)
On documentation, Gold (ozs), but on data => Gold (oz)
On documentation, Gold Placer (ozs), but on data => Gold Placer (oz)
On documentation, Wavellite (spcmns), but on data => Wavellite (spcmn)
On documentation, Oil (bbls), but on data => Oil (bbl)
On documentation, Purge Liquor (tons), but on data => Purge Liquor (tons - equivalent)
On documentation, Quartz Crystal (tickets/lbs), but on data => Quartz Crystal (tickets/pounds)
On documentation, Sand/Gravel-Cubic Yards (cyds), but on data, => Sand/Gravel-Cubic Yards
