### ISSUE TITLE
Work with  DORC to clean up Geothermal in production and revenue data sets

### ISSUE THREAD

**Issue by mentastc** [ONRR/nrrd#849]
Geothermal production and revenue data line should change as follows:

From **>** To
Geothermal   - Direct Utilization, Hundreds of Gallons **>** Geothermal  - Direct Use (Hundreds of Gallons)
Geothermal  - Direct Use, Millions of Gallons **>** Geothermal  - Direct Use (Millions of Gallons)
Geothermal  - Electrical Generation, Kilowatt Hours **>** Geothermal - Electrical Generation (Kilowatt Hours)
Geothermal  - Electrical Generation, Other **>** Geothermal  - Electrical Generation (Other)
Geothermal  - Electrical Generation, Thousands of Pounds **>** Geothermal  - Electrical Generation (Thousands of Pounds)
Geothermal  - sulfur **>** Geothermal - Sulfur (tons)

- Additionally we could try and get the measurement of hundred of gallons rolled into millions of gallons

**Comment by mcharg** [comment]
@Maroyafaied Do we still need this now that we have the database?

**Comment by Maroyafaied** [comment]
@mcharg we don't need DORC to make the changes but we can have @mojobnichols make the changes in the database since we'll be downloading files from there. I'll assign Mojo to it.

**Comment by mcharg** [comment]
@Maroyafaied We have #629 for the database.

**Comment by Maroyafaied** [comment]
@mcharg ok then I'll close this one. Thanks
