### ISSUE TITLE
Native American location field in revenue

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#860]
We've changed it in production so that the location field for Native American says "location not published." We should be consistent and use the same in revenue rather than not tied to a location for Native American. Other not tied to a location should stay that way.
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/7cc4df0c-9de7-4cf2-a9fe-ed2e4e4185a9)

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/adf892e5-f4cf-4041-869c-d62abc70f059)

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/92bc7b9f-40cc-4977-8877-fbb600ac03f0)

**Comment by mojobnichols** [comment]
No PR because it is a simple database update.    It is in dev and hasura-nrrd-a waiting for release.
