### ISSUE TITLE
Revenue other issue

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#861]
@mojobnichols i'm checking fiscal year revenue data, and the top nationwide location "other" is not summing up correctly. I checked the dev site for "other" in production data and it was correct. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f48ab3cc-0cad-4d53-94be-c311341b6f5e)

**Comment by Maroyafaied** [comment]
@mojobnichols I was not including "not tied to a location" revenue when calculating other but @jennmalcolm said it should be included so it's correct.
