### ISSUE TITLE
Start rebooting pattern library

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#901]

**Comment by mcharg** [comment]
Start a plan for getting the pattern library back online.

Old pattern library:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/aml-spark/styleguide/

**Comment by mcharg** [comment]
@master12 Has one started.

**Comment by mcharg** [comment]
What @master12 started.
https://revenuedata.doi.gov/patterns/

**Comment by mcharg** [comment]
Menu that Ryan and I designed a long time ago.
https://dpj08p.axshare.com/#g=1&p=home
