### ISSUE TITLE
Design & build glossaries in query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#91]

**Comment by mcharg** [comment]
Need to update to reflect new query tool and put together a list of the things we need help for.

**Comment by mcharg** [comment]
Also need to consider help for D3 graphs that can't have the help icon.

**Comment by mcharg** [comment]
@jnwang01 Can you link to your design for the glossary in the query tool here?

**Comment by jnwang01** [comment]
https://dp89gd.axshare.com/ here is a prototype for a glossary on the query tool

**Comment by mcharg** [comment]
@master12 This spreadsheet has the terms we want glossaries on (work in progress). https://teams.microsoft.com/l/file/73985E53-3C81-40A9-8853-A10482F267AB?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FGlossaries%2Fglossary.terms.query.tool.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@master12 Looks like I already put a link to the glossary terms above.
