### ISSUE TITLE
Fix capitalization in the database

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#921]
Everything should be sentence case except for proper nouns like Native American.

**Comment by jennmalcolm** [comment]
Here are items that need to be fixed.

We should use sentence case on the list of commodities.

![image](https://user-images.githubusercontent.com/30806839/103016350-e8f30a00-450f-11eb-9607-a54e15c00d09.png)

Revenue types should be sentence case. 

![image](https://user-images.githubusercontent.com/30806839/103016717-80585d00-4510-11eb-8631-287a2da31b57.png)

Federal offshore/onshore should be sentence case 
![image](https://user-images.githubusercontent.com/30806839/103016817-ad0c7480-4510-11eb-850c-991182a83538.png)

Land type should be sentence case except Native American
