### ISSUE TITLE
Figure out how to get glossaries into D3

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#922]
Or an alternative

**Comment by jennmalcolm** [comment]
@mcharg what were you thinking @jnwang01 would be doing on this issue now?

**Comment by mcharg** [comment]
@jennmalcolm Reviewing whatever the developers come up with.

**Comment by jennmalcolm** [comment]
Ok, thanks @mcharg. @jnwang01 it looks like there's nothing you need to do on this yet.

**Comment by master12** [comment]
We are going to use React D3 library to implement this change. If that doesn't work as expected we will just write the glossary term into D3 like we did the tooltip
