### ISSUE TITLE
Update monthly revenue, production, and disbursements files

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#933]
- [x] @lpgoldstein review files and then add to this issue

- [ ] @mojobnichols database updates

- [x] @lpgoldstein  file updates

**Comment by lpgoldstein** [comment]
[monthly_production.xlsx](https://github.com/ONRR/nrrd/files/5176718/monthly_production.xlsx)
[monthly_revenue.xlsx](https://github.com/ONRR/nrrd/files/5176720/monthly_revenue.xlsx)
 
Updated monthly files for monthly revenue and production

**Comment by lpgoldstein** [comment]
production file 
[monthly_production.xlsx](https://github.com/ONRR/nrrd/files/5176846/monthly_production.xlsx)

**Comment by jennmalcolm** [comment]
@lpgoldstein I merged your PR for the file updates for production and revenue. Could you also please update disbursements and add it to this file so @mojobnichols can update the db? He uses the csv files.

**Comment by lpgoldstein** [comment]
@jennmalcolm for some reason I thought I already did it and it was live. I will do that right now.

**Comment by lpgoldstein** [comment]
[monthly_disbursements.xlsx](https://github.com/ONRR/nrrd/files/5191488/monthly_disbursements.xlsx)
