### ISSUE TITLE
Revisit data flow page/how data all fits together

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#938]
Here's our previous work: https://github.com/ONRR/doi-extractives-data/issues/4725

We want to explain to someone who's new to ONRR's data how all the pieces fit together. We should also not leave out OGOR B (a subset of production) and sales data (a new data set), which we should be getting soon.

**Comment by mcharg** [comment]
Some other things we've tried.

For the top of Explore Data (before we landed on the map concept):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/eb7f357a-1d48-4df7-b4b3-314ab1e5ce71)

Tabs with descriptions on the homepage (I don't think we ever tested these descriptions with users):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/275f21a0-6e9c-4126-89bb-88c5d9e96566)

Top of homepage:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2c842bca-7d00-4d5f-a94c-0860e8f17fbd)

Within homepage incorporating data:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e83e1643-b8e6-4a3d-abde-66061def2477)

Homepage cards (that nobody ever read):
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/da7fa64e-50a3-4b25-9643-0a43e34efcc3)
