### ISSUE TITLE
Add monthly data to query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#96]

**Comment by mcharg** [comment]
Here's an old design that has monthly data.
https://ud95qi.axshare.com/#g=1&p=cleaner_table

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/803429f6-91a2-446b-b8fa-cbccdfe37c93)

**Comment by Maroyafaied** [comment]
Only production and disbursement, wait for the revenue monthly file.
