### ISSUE TITLE
Get familiar with cloud.gov 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#985]
Get access to could.gov
Get familiar with cloud.gov and Hasura
Get familiar with running CF boundary commands

**Comment by Baymatt** [comment]
Late update: Received access to cloud.gov, was added to the organization and was able to access the Hasura sandbox. With Mojo, I went through the steps described in nrrd/README.cloud.gov to create a tunnel and open a Postgres connection through the tunnel.

Plan to get familiar with the example found at nrrd/database/ddl/revenue_by_company.table.sql
Attempt to find a play set of data and build a similar Extract Load And transform routine.
