### ISSUE TITLE
Onboarding checklist missing Content Guide link

### ISSUE THREAD

**Issue by devynpowell** [ONRR/nrrd#986]
Content guide link in onboarding checklist goes to a blank new page creation page, not the content guide

**Comment by lpgoldstein** [comment]
https://github.com/ONRR/nrrd/wiki/Content-guide

This is a blank page linked from the onboarding checklist

**Comment by lpgoldstein** [comment]
https://github.com/ONRR/nrrd/wiki/Content-style-guide
