### ISSUE TITLE
Implement new label for oil & gas

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#989]
Change it to "oil or gas (pre-production)"

**Comment by jennmalcolm** [comment]
Update database and review data documentation to see what needs to be updated there.

**Comment by Maroyafaied** [comment]
Here is a list of documentations that will need to be updates mentioning "Oil & Gas"

- [ ] Revenue by month csv and xls files in the commodity (column F)

- [ ] Revenue by calendar year csv and xls files under commodity (column M)

- [ ] Revenue by fiscal year csv and xls files under commodity (column M)

- [ ] Revenue by company csv and xls files under commodity (column D)

- [ ] Monthly disbursement csv and xls files under commodity (column H)

- [ ] Download pages :Revenue by year & Revenue by month & Revenue by company download pages under scope (Why is there a Gas value, an Oil value and an Oil & Gas value?) and under list of commodities.
![image](https://user-images.githubusercontent.com/40175688/95892429-c55b5880-0d43-11eb-9056-a80e9ea16ab2.png)
![image](https://user-images.githubusercontent.com/40175688/95892471-d86e2880-0d43-11eb-9461-a889ee8f7978.png)

- [ ] Download page disbursement monthly : under commodity definition and list of commodities
![image](https://user-images.githubusercontent.com/40175688/95892319-980eaa80-0d43-11eb-80f7-62d7d8133020.png)
