### ISSUE TITLE
Brainstorm replacements for "How revenue works"

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#997]
In order to test concepts in our next round of user research, I want to do some brainstorming on other terms to replace "how revenue works." The other main sections of our site all use verbs, so I would like to be consistent. Please add any ideas you have into this issue for tracking purposes.

**Comment by jennmalcolm** [comment]
Here are a few of my ideas:
Learn about revenues
Learn more
Research process
Find out more
Find more information
Read more
Learn background

**Comment by mcharg** [comment]
Some other options:
- Understand
- Get context
- Revenue process
- Master the process
- Resources to revenue
- Converting resources to revenue
- Background
